// Snippets the SQL Editor ships with (docs/ui-redesign.md, phase 3), as
// Studio's "Templates" and "Quickstarts". Each opens as a new query.

export type Template = { title: string; description: string; sql: string };

export const TEMPLATES: Template[] = [
  {
    title: "Create a table",
    description: "A table with an identity key and a creation time",
    sql: `create table public.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);`,
  },
  {
    title: "Add a column",
    description: "Add a column with a default",
    sql: `alter table public.todos
  add column priority int not null default 0;`,
  },
  {
    title: "Create an index",
    description: "Build an index without blocking writes",
    sql: `create index concurrently todos_done_idx
  on public.todos (done);`,
  },
  {
    title: "Table sizes",
    description: "The biggest tables, with their indexes",
    sql: `select
  n.nspname as schema,
  c.relname as table,
  pg_size_pretty(pg_total_relation_size(c.oid)) as total,
  pg_size_pretty(pg_relation_size(c.oid)) as data,
  c.reltuples::bigint as rows_estimate
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where c.relkind in ('r', 'p', 'm')
  and n.nspname not in ('pg_catalog', 'information_schema')
order by pg_total_relation_size(c.oid) desc
limit 20;`,
  },
  {
    title: "Running queries",
    description: "What the database is doing now, longest first",
    sql: `select
  pid,
  now() - query_start as running_for,
  state,
  wait_event_type,
  left(query, 200) as query
from pg_stat_activity
where datname = current_database()
  and pid <> pg_backend_pid()
  and state <> 'idle'
order by query_start;`,
  },
  {
    title: "Unused indexes",
    description: "Indexes never scanned since statistics were reset",
    sql: `select
  schemaname as schema,
  relname as table,
  indexrelname as index,
  pg_size_pretty(pg_relation_size(indexrelid)) as size
from pg_stat_user_indexes
where idx_scan = 0
order by pg_relation_size(indexrelid) desc;`,
  },
  {
    title: "Slowest queries",
    description: "Needs the pg_stat_statements extension (Settings)",
    sql: `select
  calls,
  round(total_exec_time::numeric, 1) as total_ms,
  round(mean_exec_time::numeric, 1) as mean_ms,
  left(query, 200) as query
from pg_stat_statements
order by total_exec_time desc
limit 20;`,
  },
];
