package api

import "github.com/israel-duff/pgdock/internal/authz"

// scope says how a route's resource is found before authz.Can runs.
type scope int

const (
	scopePublic    scope = iota // no session needed
	scopeSelf                   // a signed-in user acting on their own account
	scopePlatform               // platform admin only
	scopeOrgPath                // {org} in the path
	scopeOrgQuery               // ?org=, the user's personal organisation by default
	scopeProject                // {id} is a project
	scopeBackup                 // {id} is a backup; its project's organisation
	scopeOperation              // {id} is an operation; its project's organisation
	scopeBody                   // the organisation is in the request body; the handler checks
)

// rule is a route's authorization: where its resource is and what action
// it performs (V2 §2.6: every route declares its action).
type rule struct {
	scope  scope
	action authz.Action
	// beforeTerms routes work while the user still has to accept new terms.
	beforeTerms bool
	// branchAction, when set, replaces action on a project that is a
	// branch (V2 §2.3: developers delete branches, not projects).
	branchAction authz.Action
	// token is the scope an API token needs on a scopeSelf route; empty
	// means the route is for browser sessions only. Other scopes are
	// checked by authz.Can (V2 §7.2).
	token string
}

// routeRules covers every route in api/openapi.yaml; TestEveryRouteDeclaresAnAction
// fails when one is missing, and the guard refuses undeclared routes.
var routeRules = map[string]rule{
	// Public.
	"GET /healthz":        {scope: scopePublic},
	"GET /readyz":         {scope: scopePublic},
	"GET /api/v1/version": {scope: scopePublic},
	"GET /api/v1/pricing": {scope: scopePublic},
	// Payment providers' webhooks, authenticated by their signatures.
	"POST /api/v1/payments/webhooks/{provider}": {scope: scopePublic},
	// pgdock-edge's feed (V4 §2.1): signed with the edge secret, checked in
	// the handler.
	"GET /api/v1/edge/config":         {scope: scopePublic},
	"POST /api/v1/edge/report":        {scope: scopePublic},
	"POST /api/v1/edge/wake":          {scope: scopePublic},
	"POST /api/v1/edge/auth-message":  {scope: scopePublic},
	"POST /api/v1/edge/auth-hook":     {scope: scopePublic},
	"POST /api/v1/edge/storage-event": {scope: scopePublic},
	// Support's inbound channels (V3 §7.1), authenticated per channel.
	"POST /api/v1/support/inbound/email": {scope: scopePublic},
	"GET /api/v1/support/whatsapp":       {scope: scopePublic},
	"POST /api/v1/support/whatsapp":      {scope: scopePublic},
	// Support tickets (V3 §7.1): members open and follow their own,
	// admins see the organisation's.
	"GET /api/v1/orgs/{org}/support/tickets":                       {scope: scopeOrgPath, action: authz.OrgView},
	"POST /api/v1/orgs/{org}/support/tickets":                      {scope: scopeOrgPath, action: authz.OrgView},
	"GET /api/v1/orgs/{org}/support/tickets/{ticket_id}":           {scope: scopeOrgPath, action: authz.OrgView},
	"POST /api/v1/orgs/{org}/support/tickets/{ticket_id}/messages": {scope: scopeOrgPath, action: authz.OrgView},
	"GET /api/v1/orgs/{org}/support/phones":                        {scope: scopeOrgPath, action: authz.OrgView},
	"POST /api/v1/orgs/{org}/support/phones":                       {scope: scopeOrgPath, action: authz.OrgManage},
	"DELETE /api/v1/orgs/{org}/support/phones/{phone}":             {scope: scopeOrgPath, action: authz.OrgManage},
	"GET /api/v1/admin/support/tickets":                            {scope: scopePlatform, action: authz.SupportConsole},
	"GET /api/v1/admin/support/tickets/{ticket_id}":                {scope: scopePlatform, action: authz.SupportConsole},
	"PATCH /api/v1/admin/support/tickets/{ticket_id}":              {scope: scopePlatform, action: authz.SupportConsole},
	"POST /api/v1/admin/support/tickets/{ticket_id}/messages":      {scope: scopePlatform, action: authz.SupportConsole},
	"GET /api/v1/admin/revenue":                                    {scope: scopePlatform, action: authz.PlatformManage},
	// Legal documents (V3 §7.3): owners accept the SLA, DPA and order form.
	"GET /api/v1/legal":                                  {scope: scopePublic, beforeTerms: true},
	"GET /api/v1/orgs/{org}/legal":                       {scope: scopeOrgPath, action: authz.OrgView},
	"POST /api/v1/orgs/{org}/legal/{document_id}/accept": {scope: scopeOrgPath, action: authz.OrgOwnerOnly},
	"GET /api/v1/admin/legal":                            {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/legal":                           {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/legal/{document_id}":              {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/orgs/{org}/order-form":           {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/support/staff":                    {scope: scopePlatform, action: authz.SupportConsole},
	"GET /api/v1/session":                                {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/auth/login":                            {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/auth/totp":                             {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/setup/begin":                           {scope: scopePublic},
	"POST /api/v1/setup/complete":                        {scope: scopePublic},
	"POST /api/v1/agent/register":                        {scope: scopePublic},
	"POST /api/v1/auth/signup":                           {scope: scopePublic},
	"POST /api/v1/auth/verify-email":                     {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/auth/verify-email/resend":              {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/auth/password-reset":                   {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/auth/password-reset/confirm":           {scope: scopePublic, beforeTerms: true},
	"GET /api/v1/terms":                                  {scope: scopePublic, beforeTerms: true},
	"POST /api/v1/invitations/preview":                   {scope: scopePublic},
	"POST /api/v1/invitations/accept":                    {scope: scopePublic},
	// The CLI's device login; the approval itself needs a session.
	"POST /api/v1/auth/device":       {scope: scopePublic},
	"POST /api/v1/auth/device/token": {scope: scopePublic},
	// /metrics takes a bearer token instead; the handler checks it or the session.
	"GET /metrics": {scope: scopePublic},

	// The signed-in user.
	"POST /api/v1/auth/reauth":                           {scope: scopeSelf, action: authz.Self, beforeTerms: true},
	"POST /api/v1/auth/logout":                           {scope: scopeSelf, action: authz.Self, beforeTerms: true},
	"GET /api/v1/me":                                     {scope: scopeSelf, action: authz.Self, beforeTerms: true, token: authz.ScopeRead},
	"PATCH /api/v1/me":                                   {scope: scopeSelf, action: authz.Self},
	"POST /api/v1/me/password":                           {scope: scopeSelf, action: authz.Self},
	"GET /api/v1/me/sessions":                            {scope: scopeSelf, action: authz.Self},
	"DELETE /api/v1/me/sessions/{session_id}":            {scope: scopeSelf, action: authz.Self},
	"GET /api/v1/me/recovery-codes":                      {scope: scopeSelf, action: authz.Self},
	"POST /api/v1/me/recovery-codes":                     {scope: scopeSelf, action: authz.Self},
	"POST /api/v1/me/terms/accept":                       {scope: scopeSelf, action: authz.Self, beforeTerms: true},
	"GET /api/v1/me/invitations":                         {scope: scopeSelf, action: authz.Self},
	"POST /api/v1/me/invitations/{invitation_id}/accept": {scope: scopeSelf, action: authz.Self},
	"GET /api/v1/orgs":                                   {scope: scopeSelf, action: authz.Self, token: authz.ScopeRead},
	"POST /api/v1/orgs":                                  {scope: scopeSelf, action: authz.Self},
	"GET /api/v1/settings/general":                       {scope: scopeSelf, action: authz.Self, token: authz.ScopeRead},
	"GET /api/v1/profiles":                               {scope: scopeSelf, action: authz.Self, token: authz.ScopeRead},
	"GET /api/v1/regions":                                {scope: scopeSelf, action: authz.Self, token: authz.ScopeRead},
	"POST /api/v1/imports/preflight":                     {scope: scopeSelf, action: authz.Self},
	// API tokens (V2 §7.2): a token may manage its user's tokens in its own
	// organisation, never exceeding itself (the handlers check).
	"GET /api/v1/tokens":                           {scope: scopeSelf, action: authz.Self, token: authz.ScopeRead},
	"POST /api/v1/tokens":                          {scope: scopeSelf, action: authz.Self, token: authz.ScopeWrite},
	"DELETE /api/v1/tokens/{token_id}":             {scope: scopeSelf, action: authz.Self, token: authz.ScopeRead},
	"GET /api/v1/auth/device/requests/{user_code}": {scope: scopeSelf, action: authz.Self},
	"POST /api/v1/auth/device/approve":             {scope: scopeSelf, action: authz.Self},

	// Organisations.
	"GET /api/v1/orgs/{org}":                                                {scope: scopeOrgPath, action: authz.OrgView},
	"PATCH /api/v1/orgs/{org}":                                              {scope: scopeOrgPath, action: authz.OrgManage},
	"GET /api/v1/orgs/{org}/members":                                        {scope: scopeOrgPath, action: authz.OrgView},
	"POST /api/v1/orgs/{org}/members":                                       {scope: scopeOrgPath, action: authz.OrgManage},
	"PATCH /api/v1/orgs/{org}/members/{user}":                               {scope: scopeOrgPath, action: authz.OrgManage},
	"DELETE /api/v1/orgs/{org}/members/{user}":                              {scope: scopeOrgPath, action: authz.OrgManage},
	"POST /api/v1/orgs/{org}/leave":                                         {scope: scopeOrgPath, action: authz.OrgView},
	"POST /api/v1/orgs/{org}/transfer-ownership":                            {scope: scopeOrgPath, action: authz.OrgOwnerOnly},
	"GET /api/v1/orgs/{org}/invitations":                                    {scope: scopeOrgPath, action: authz.OrgManage},
	"DELETE /api/v1/orgs/{org}/invitations/{invitation_id}":                 {scope: scopeOrgPath, action: authz.OrgManage},
	"GET /api/v1/orgs/{org}/audit":                                          {scope: scopeOrgPath, action: authz.OrgAudit},
	"DELETE /api/v1/orgs/{org}":                                             {scope: scopeOrgPath, action: authz.OrgOwnerOnly},
	"POST /api/v1/orgs/{org}/cancel-deletion":                               {scope: scopeOrgPath, action: authz.OrgOwnerOnly},
	"POST /api/v1/orgs/{org}/break-glass/{session_id}/end":                  {scope: scopeOrgPath, action: authz.OrgOwnerOnly},
	"GET /api/v1/orgs/{org}/quotas":                                         {scope: scopeOrgPath, action: authz.OrgView},
	"GET /api/v1/orgs/{org}/billing":                                        {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"PATCH /api/v1/orgs/{org}/billing":                                      {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"POST /api/v1/orgs/{org}/billing/plan":                                  {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/contacts":                               {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"POST /api/v1/orgs/{org}/billing/contacts":                              {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"DELETE /api/v1/orgs/{org}/billing/contacts/{email}":                    {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/invoices":                               {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"POST /api/v1/orgs/{org}/billing/checkout":                              {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"POST /api/v1/orgs/{org}/billing/virtual-account":                       {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/payment-methods":                        {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"DELETE /api/v1/orgs/{org}/billing/payment-methods/{method_id}":         {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"POST /api/v1/orgs/{org}/billing/payment-methods/{method_id}/default":   {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"PUT /api/v1/orgs/{org}/billing/auto-topup":                             {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"DELETE /api/v1/orgs/{org}/billing/auto-topup":                          {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/payments":                               {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/payments/{payment_id}/receipt":          {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"POST /api/v1/orgs/{org}/billing/invoices/{invoice_id}/wht-certificate": {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/forecast":                               {scope: scopeOrgPath, action: authz.OrgBillingManage},
	// Prices are public: anyone in the org sees what an action will cost.
	"POST /api/v1/orgs/{org}/billing/estimate":                 {scope: scopeOrgPath, action: authz.OrgView},
	"GET /api/v1/orgs/{org}/billing/invoices/{invoice_id}":     {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/billing/invoices/{invoice_id}/pdf": {scope: scopeOrgPath, action: authz.OrgBillingManage},
	"GET /api/v1/orgs/{org}/usage":                             {scope: scopeOrgPath, action: authz.OrgAudit},
	"GET /api/v1/orgs/{org}/dedicated-requests":                {scope: scopeOrgPath, action: authz.OrgAudit},
	"GET /api/v1/orgs/{org}/tokens":                            {scope: scopeOrgPath, action: authz.OrgManage},
	"DELETE /api/v1/orgs/{org}/tokens/{token_id}":              {scope: scopeOrgPath, action: authz.OrgManage},
	// Org storage targets (V2 §6): owners and admins.
	"GET /api/v1/orgs/{org}/storage-targets":                {scope: scopeOrgPath, action: authz.OrgManage},
	"POST /api/v1/orgs/{org}/storage-targets":               {scope: scopeOrgPath, action: authz.OrgManage},
	"GET /api/v1/orgs/{org}/storage-targets/{target_id}":    {scope: scopeOrgPath, action: authz.OrgManage},
	"PATCH /api/v1/orgs/{org}/storage-targets/{target_id}":  {scope: scopeOrgPath, action: authz.OrgManage},
	"DELETE /api/v1/orgs/{org}/storage-targets/{target_id}": {scope: scopeOrgPath, action: authz.OrgManage},
	"POST /api/v1/storage-targets/test":                     {scope: scopeOrgQuery, action: authz.OrgManage},
	"GET /api/v1/projects":                                  {scope: scopeOrgQuery, action: authz.OrgView},
	"GET /api/v1/operations":                                {scope: scopeOrgQuery, action: authz.OrgView},
	"GET /api/v1/backups":                                   {scope: scopeOrgQuery, action: authz.OrgView},
	"GET /api/v1/backups/overview":                          {scope: scopeOrgQuery, action: authz.OrgView},
	"POST /api/v1/projects":                                 {scope: scopeBody, action: authz.OrgCreateProject},
	"POST /api/v1/imports":                                  {scope: scopeBody, action: authz.OrgCreateProject},

	// Projects.
	"GET /api/v1/projects/{id}":            {scope: scopeProject, action: authz.ProjectView},
	"DELETE /api/v1/projects/{id}":         {scope: scopeProject, action: authz.ProjectDelete, branchAction: authz.BranchManage},
	"PATCH /api/v1/projects/{id}/settings": {scope: scopeProject, action: authz.ProjectSettings},
	// Backend services (V4 §2.2, §2.4, §8.3).
	"GET /api/v1/projects/{id}/services":                  {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/services":                 {scope: scopeProject, action: authz.ServicesManage},
	"PATCH /api/v1/projects/{id}/services":                {scope: scopeProject, action: authz.ServicesManage},
	"DELETE /api/v1/projects/{id}/services":               {scope: scopeProject, action: authz.ServicesManage},
	"POST /api/v1/projects/{id}/services/keys":            {scope: scopeProject, action: authz.ServicesManage},
	"DELETE /api/v1/projects/{id}/services/keys/{key_id}": {scope: scopeProject, action: authz.ServicesManage},
	"GET /api/v1/projects/{id}/services/logs":             {scope: scopeProject, action: authz.ServicesLogs},
	"GET /api/v1/projects/{id}/services/types":            {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/services/advisor":          {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/services/explore":         {scope: scopeProject, action: authz.ConsoleWrite},
	// Auth (V4 §4.9).
	"GET /api/v1/projects/{id}/auth/config":                        {scope: scopeProject, action: authz.ServicesLogs},
	"GET /api/v1/projects/{id}/auth/hooks":                         {scope: scopeProject, action: authz.ServicesLogs},
	"PATCH /api/v1/projects/{id}/auth/config":                      {scope: scopeProject, action: authz.ServicesManage},
	"POST /api/v1/projects/{id}/auth/smtp/test":                    {scope: scopeProject, action: authz.ServicesManage},
	"POST /api/v1/projects/{id}/auth/templates/preview":            {scope: scopeProject, action: authz.ServicesManage},
	"GET /api/v1/projects/{id}/auth/signing-keys":                  {scope: scopeProject, action: authz.ServicesLogs},
	"POST /api/v1/projects/{id}/auth/signing-keys/rotate":          {scope: scopeProject, action: authz.ServicesManage},
	"GET /api/v1/projects/{id}/auth/users":                         {scope: scopeProject, action: authz.AuthUsers},
	"GET /api/v1/projects/{id}/files":                              {scope: scopeProject, action: authz.FilesView},
	"GET /api/v1/projects/{id}/realtime":                           {scope: scopeProject, action: authz.RealtimeView},
	"PUT /api/v1/projects/{id}/realtime/tables/{schema}/{table}":   {scope: scopeProject, action: authz.RealtimeManage},
	"PUT /api/v1/projects/{id}/realtime/persisted-topics":          {scope: scopeProject, action: authz.RealtimeManage},
	"POST /api/v1/projects/{id}/files/buckets":                     {scope: scopeProject, action: authz.FilesManage},
	"PATCH /api/v1/projects/{id}/files/buckets/{bucket}":           {scope: scopeProject, action: authz.FilesManage},
	"DELETE /api/v1/projects/{id}/files/buckets/{bucket}":          {scope: scopeProject, action: authz.FilesManage},
	"GET /api/v1/projects/{id}/files/buckets/{bucket}/objects":     {scope: scopeProject, action: authz.FilesView},
	"DELETE /api/v1/projects/{id}/files/buckets/{bucket}/objects":  {scope: scopeProject, action: authz.FilesManage},
	"GET /api/v1/projects/{id}/files/buckets/{bucket}/object":      {scope: scopeProject, action: authz.FilesView},
	"PUT /api/v1/projects/{id}/files/buckets/{bucket}/object":      {scope: scopeProject, action: authz.FilesManage},
	"POST /api/v1/projects/{id}/files/buckets/{bucket}/sign":       {scope: scopeProject, action: authz.FilesView},
	"POST /api/v1/projects/{id}/auth/users":                        {scope: scopeProject, action: authz.AuthUsersManage},
	"GET /api/v1/projects/{id}/auth/users/{userId}":                {scope: scopeProject, action: authz.AuthUsers},
	"PATCH /api/v1/projects/{id}/auth/users/{userId}":              {scope: scopeProject, action: authz.AuthUsersManage},
	"DELETE /api/v1/projects/{id}/auth/users/{userId}":             {scope: scopeProject, action: authz.AuthUsersManage},
	"POST /api/v1/projects/{id}/auth/users/{userId}/signout":       {scope: scopeProject, action: authz.AuthUsersManage},
	"GET /api/v1/projects/{id}/auth/audit":                         {scope: scopeProject, action: authz.AuthUsers},
	"POST /api/v1/projects/{id}/rotate-password":                   {scope: scopeProject, action: authz.ProjectSettings},
	"POST /api/v1/projects/{id}/backups":                           {scope: scopeProject, action: authz.BackupCreate},
	"POST /api/v1/projects/{id}/pitr":                              {scope: scopeProject, action: authz.BackupCreate},
	"GET /api/v1/projects/{id}/promote":                            {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/promote":                           {scope: scopeProject, action: authz.ProjectPromote},
	"GET /api/v1/projects/{id}/ha":                                 {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/ha":                                {scope: scopeProject, action: authz.ProjectPromote},
	"PATCH /api/v1/projects/{id}/ha":                               {scope: scopeProject, action: authz.ProjectPromote},
	"PATCH /api/v1/projects/{id}/instance":                         {scope: scopeProject, action: authz.ProjectPromote},
	"DELETE /api/v1/projects/{id}/ha":                              {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/switchover":                        {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/ha/etcd-move":                      {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/migrate/supabase":                  {scope: scopeProject, action: authz.ServicesManage},
	"GET /api/v1/projects/{id}/replicas":                           {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/replicas":                          {scope: scopeProject, action: authz.ProjectPromote},
	"DELETE /api/v1/projects/{id}/replicas/{replica_id}":           {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/replicas/{replica_id}/detach":      {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/resume":                            {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/upgrade/preflight":                 {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/upgrade":                           {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/admin/projects/{project_id}/move":                {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/projects/{id}/moves":                              {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/demote/preflight":                  {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/demote":                            {scope: scopeProject, action: authz.ProjectPromote},
	"POST /api/v1/projects/{id}/instance":                          {scope: scopeProject, action: authz.ProjectSettings},
	"POST /api/v1/projects/{id}/sql":                               {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/sql/cancel":                        {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/schema":                             {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/tables/{schema}/{table}/rows":       {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/tables/{schema}/{table}":            {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/tables/{schema}/{table}/export":     {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/tables/{schema}/{table}/count":      {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/tables/{schema}/{table}/definition": {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/tables/{schema}/{table}/changes":   {scope: scopeProject, action: authz.TableEdit},
	"GET /api/v1/projects/{id}/queries":                            {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/queries":                           {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/queries/{query_id}":                 {scope: scopeProject, action: authz.ConsoleRead},
	"PATCH /api/v1/projects/{id}/queries/{query_id}":               {scope: scopeProject, action: authz.ConsoleRead},
	"DELETE /api/v1/projects/{id}/queries/{query_id}":              {scope: scopeProject, action: authz.ConsoleRead},
	"PUT /api/v1/projects/{id}/queries/{query_id}/favorite":        {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/schema/preview":                    {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/schema/migration":                  {scope: scopeProject, action: authz.ConsoleRead},
	// Query insights (V3 §8): statements, plans and sessions of the
	// project's own database, like the console's reads.
	"GET /api/v1/projects/{id}/insights/queries":            {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/insights/queries/{query_id}": {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/insights/explain":           {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/insights/slow":               {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/insights/indexes":            {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/insights/bloat":              {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/insights/locks":              {scope: scopeProject, action: authz.ConsoleRead},
	"POST /api/v1/projects/{id}/schema/apply":               {scope: scopeProject, action: authz.TableEdit},
	"GET /api/v1/projects/{id}/editor-preferences":          {scope: scopeProject, action: authz.ConsoleRead},
	"GET /api/v1/projects/{id}/extensions":                  {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/extensions":                 {scope: scopeProject, action: authz.ProjectSettings},
	"GET /api/v1/projects/{id}/metrics":                     {scope: scopeProject, action: authz.ProjectView},
	"GET /api/v1/projects/{id}/members":                     {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/members":                    {scope: scopeProject, action: authz.ProjectMembers},
	"PATCH /api/v1/projects/{id}/members/{user}":            {scope: scopeProject, action: authz.ProjectMembers},
	"DELETE /api/v1/projects/{id}/members/{user}":           {scope: scopeProject, action: authz.ProjectMembers},
	"GET /api/v1/projects/{id}/credentials":                 {scope: scopeProject, action: authz.ProjectCredentials},
	"POST /api/v1/projects/{id}/credentials":                {scope: scopeProject, action: authz.ProjectCredentials},
	"POST /api/v1/projects/{id}/transfer":                   {scope: scopeProject, action: authz.ProjectDelete},
	"GET /api/v1/projects/{id}/audit":                       {scope: scopeProject, action: authz.ProjectAudit},
	"POST /api/v1/projects/{id}/switch-credentials":         {scope: scopeProject, action: authz.ProjectSettings},
	"GET /api/v1/projects/{id}/storage":                     {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/reclaim-space":              {scope: scopeProject, action: authz.ProjectSettings},
	"GET /api/v1/projects/{id}/reaped":                      {scope: scopeProject, action: authz.ProjectView},
	"GET /api/v1/projects/{id}/branches":                    {scope: scopeProject, action: authz.ProjectView},
	"POST /api/v1/projects/{id}/branches":                   {scope: scopeProject, action: authz.BranchManage},
	"POST /api/v1/projects/{id}/reset":                      {scope: scopeProject, action: authz.BranchManage},
	"POST /api/v1/projects/{id}/detach":                     {scope: scopeProject, action: authz.BranchManage},

	// Webhooks and scheduled jobs (V2 §9).
	"GET /api/v1/projects/{id}/webhooks":                             {scope: scopeProject, action: authz.AutomationManage},
	"POST /api/v1/projects/{id}/webhooks":                            {scope: scopeProject, action: authz.AutomationManage},
	"GET /api/v1/projects/{id}/webhooks/{webhook_id}":                {scope: scopeProject, action: authz.AutomationManage},
	"PATCH /api/v1/projects/{id}/webhooks/{webhook_id}":              {scope: scopeProject, action: authz.AutomationManage},
	"DELETE /api/v1/projects/{id}/webhooks/{webhook_id}":             {scope: scopeProject, action: authz.AutomationManage},
	"POST /api/v1/projects/{id}/webhooks/{webhook_id}/test":          {scope: scopeProject, action: authz.AutomationManage},
	"POST /api/v1/projects/{id}/webhooks/{webhook_id}/rotate-secret": {scope: scopeProject, action: authz.AutomationManage},
	"GET /api/v1/projects/{id}/webhooks/{webhook_id}/deliveries":     {scope: scopeProject, action: authz.AutomationManage},
	"POST /api/v1/projects/{id}/webhooks/{webhook_id}/replay":        {scope: scopeProject, action: authz.AutomationManage},
	"GET /api/v1/projects/{id}/jobs":                                 {scope: scopeProject, action: authz.AutomationManage},
	"POST /api/v1/projects/{id}/jobs":                                {scope: scopeProject, action: authz.AutomationManage},
	"GET /api/v1/projects/{id}/jobs/{job_id}":                        {scope: scopeProject, action: authz.AutomationManage},
	"PATCH /api/v1/projects/{id}/jobs/{job_id}":                      {scope: scopeProject, action: authz.AutomationManage},
	"DELETE /api/v1/projects/{id}/jobs/{job_id}":                     {scope: scopeProject, action: authz.AutomationManage},
	"POST /api/v1/projects/{id}/jobs/{job_id}/run":                   {scope: scopeProject, action: authz.AutomationManage},
	"GET /api/v1/projects/{id}/jobs/{job_id}/runs":                   {scope: scopeProject, action: authz.AutomationManage},
	"GET /api/v1/projects/{id}/storage-target":                       {scope: scopeProject, action: authz.ProjectView},
	"PUT /api/v1/projects/{id}/storage-target":                       {scope: scopeProject, action: authz.BackupStorage},
	"POST /api/v1/projects/{id}/backup-key":                          {scope: scopeProject, action: authz.BackupStorage},
	"GET /api/v1/projects/{id}/backup-key/download":                  {scope: scopeProject, action: authz.BackupStorage},
	// Restoring in place needs the project admin role; the handler checks
	// it for that mode.
	"POST /api/v1/backups/{id}/restore":   {scope: scopeBackup, action: authz.BackupCreate},
	"GET /api/v1/backups/{id}/download":   {scope: scopeBackup, action: authz.ProjectExport},
	"PUT /api/v1/projects/{id}/residency": {scope: scopeProject, action: authz.ProjectResidency},
	"GET /api/v1/operations/{id}":         {scope: scopeOperation, action: authz.ProjectView},
	"GET /api/v1/operations/{id}/stream":  {scope: scopeOperation, action: authz.ProjectView},

	// The platform.
	"PUT /api/v1/settings/db-host":             {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/settings/db-host/check":      {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/dev/operations":              {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/restore-tests":               {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/settings/storage":             {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/settings/storage":             {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/settings/storage/test":       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/settings/backup-key":          {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/settings/backup-key":         {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/settings/backup-key/export":  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/settings/backup-key/confirm": {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/nodes":                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/nodes":                       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/nodes/{id}":                   {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/nodes/{id}":                 {scope: scopePlatform, action: authz.PlatformManage},
	"DELETE /api/v1/nodes/{id}":                {scope: scopePlatform, action: authz.PlatformManage},
	// Capacity automation and cost attribution (V3 §5, §7.2).
	"GET /api/v1/admin/capacity":                                   {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/regions":                                    {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/regions/{region_id}":                        {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/regions/{region_id}/readiness":              {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/capacity/settings":                          {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/capacity/evaluate":                         {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/capacity/proposals/{proposal_id}/approve":  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/capacity/proposals/{proposal_id}/reject":   {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/capacity/rebalance":                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/capacity/batches/{batch_id}":               {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/cloud/catalog":                              {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/nodes/{id}/drain":                                {scope: scopePlatform, action: authz.PlatformManage},
	"DELETE /api/v1/nodes/{id}/drain":                              {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/nodes/{id}/cost":                                  {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/costs":                                      {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/costs/attribute":                           {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/costs/settings":                             {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/costs/settings":                             {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/fx-rates":                                   {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/fx-rates":                                  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/nodes/{id}/shared-cluster":                       {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/nodes/{id}/registration-token":                   {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/nodes/{id}/metrics":                               {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/security/isolation-checks":                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/security/isolation-checks":                       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/alerts":                                           {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/incidents":                                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/incidents":                                       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/incidents/{id}":                                   {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/incidents/{id}":                                 {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/incidents/{id}/updates":                          {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/pooler-hosts":                                     {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/settings/alerts":                                  {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/settings/alerts":                                  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/settings/alerts/test":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/audit":                                      {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/users":                                      {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/admin/users/{user}":                             {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/users/{user}/reset-2fa":                    {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/invitations":                                {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/invitations":                               {scope: scopePlatform, action: authz.PlatformManage},
	"DELETE /api/v1/admin/invitations/{invitation_id}":             {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/settings/signup":                            {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/settings/signup":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/settings/mail":                              {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/settings/mail":                              {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/settings/terms":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/orgs":                                       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/orgs/{org}":                                 {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/admin/orgs/{org}":                               {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/orgs/{org}/suspend":                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/orgs/{org}/reinstate":                      {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/orgs/{org}/cluster":                        {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/orgs/{org}/outbound":                        {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/orgs/{org}/outbound":                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/orgs/{org}/break-glass":                    {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/plans":                                      {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/plans":                                     {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/admin/plans/{plan_id}":                          {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/dedicated-requests":                         {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/dedicated-requests/{request_id}/approve":   {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/dedicated-requests/{request_id}/reject":    {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/usage":                                      {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/etcd":                                       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/failure-domains":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/maintenance/announcements":                  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/maintenance/announcements":                 {scope: scopePlatform, action: authz.PlatformManage},
	"DELETE /api/v1/admin/maintenance/announcements/{incident_id}": {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/etcd/members/{node_id}/replace":            {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/etcd":                                      {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/maintenance":                                {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/billing/settings":                           {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/billing/settings":                           {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/price-books":                                {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/price-books":                               {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/price-books/{version}":                      {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/price-books/{version}":                      {scope: scopePlatform, action: authz.PlatformManage},
	"DELETE /api/v1/admin/price-books/{version}":                   {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/price-books/{version}/publish":             {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/orgs/{org}/billing":                         {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/admin/orgs/{org}/billing":                       {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/price-books/{version}/preview":             {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/invoices":                                   {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/invoices/draft":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/invoices/{invoice_id}":                      {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/invoices/{invoice_id}/pdf":                  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/invoices/{invoice_id}/hold":                {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/invoices/{invoice_id}/issue":               {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/invoices/{invoice_id}/credit-notes":        {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/ledger/check":                               {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/payments":                                   {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/payments":                                  {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/billing/documents":                         {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/payments/{payment_id}/refund":              {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/payment-events":                             {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/payment-events/{event_id}/attribute":       {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/wht":                                        {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/invoices/{invoice_id}/wht-certificate":     {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/reconciliation":                             {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/reconciliation":                            {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/orgs/{org}/billing/grace":                   {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/maintenance/window":                         {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/instances/{instance_id}/minor-upgrade":     {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/shared-clusters":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/settings/tokens":                            {scope: scopePlatform, action: authz.PlatformManage},
	"PUT /api/v1/admin/settings/tokens":                            {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/storage-targets":                            {scope: scopePlatform, action: authz.PlatformManage},
	"POST /api/v1/admin/storage-targets":                           {scope: scopePlatform, action: authz.PlatformManage},
	"GET /api/v1/admin/storage-targets/{target_id}":                {scope: scopePlatform, action: authz.PlatformManage},
	"PATCH /api/v1/admin/storage-targets/{target_id}":              {scope: scopePlatform, action: authz.PlatformManage},
	"DELETE /api/v1/admin/storage-targets/{target_id}":             {scope: scopePlatform, action: authz.PlatformManage},
}
