package agentsvc

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net/netip"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"text/template"
	"time"

	"github.com/israel-duff/pgdock/internal/pooler"
)

// KeepalivedConfig describes one pooler host's VRRP instance (V3 §2.1).
type KeepalivedConfig struct {
	// Interface carries the VRRP adverts and, if VIP is set, the address.
	Interface string
	// SelfIP and PeerIP are the two hosts' private addresses: VRRP runs
	// unicast (Hetzner networks have no multicast).
	SelfIP, PeerIP string
	// VIP is the address keepalived adds on becoming MASTER: the floating
	// IP on Hetzner (configured on both hosts, routed to one), or a shared
	// address on a test network. Empty leaves addresses alone.
	VIP string
	// RouterID (1–255) must be the same on both hosts and unique on the
	// network.
	RouterID int
	// Priority breaks ties at start (1–254); nopreempt keeps the current
	// MASTER when the other host returns.
	Priority int
	// Password authenticates adverts (keepalived uses at most 8 bytes).
	Password string
	// CheckURL and NotifyURL are the agent's loopback API.
	CheckURL, NotifyURL string
}

var ifaceName = regexp.MustCompile(`^[a-zA-Z0-9_.@-]{1,15}$`)

func (c *KeepalivedConfig) validate() error {
	var errs []error
	if !ifaceName.MatchString(c.Interface) {
		errs = append(errs, fmt.Errorf("interface %q is not an interface name", c.Interface))
	}
	for name, ip := range map[string]string{"self": c.SelfIP, "peer": c.PeerIP} {
		if _, err := netip.ParseAddr(ip); err != nil {
			errs = append(errs, fmt.Errorf("%s IP %q: %w", name, ip, err))
		}
	}
	if c.SelfIP == c.PeerIP {
		errs = append(errs, errors.New("self and peer IPs are the same"))
	}
	if c.VIP != "" {
		if _, err := netip.ParseAddr(c.VIP); err != nil {
			errs = append(errs, fmt.Errorf("VIP %q: %w", c.VIP, err))
		}
	}
	if c.RouterID < 1 || c.RouterID > 255 {
		errs = append(errs, fmt.Errorf("router ID %d is not 1–255", c.RouterID))
	}
	if c.Priority < 1 || c.Priority > 254 {
		errs = append(errs, fmt.Errorf("priority %d is not 1–254", c.Priority))
	}
	if c.Password == "" || len(c.Password) > 8 || strings.ContainsAny(c.Password, "\" \t\n\\") {
		errs = append(errs, errors.New("the VRRP password must be 1–8 characters without spaces, quotes or backslashes"))
	}
	for _, u := range []string{c.CheckURL, c.NotifyURL} {
		if !strings.HasPrefix(u, "http://127.0.0.1:") && !strings.HasPrefix(u, "http://[::1]:") {
			errs = append(errs, fmt.Errorf("%q is not the agent's loopback API", u))
		}
	}
	return errors.Join(errs...)
}

// The scripts call busybox directly: keepalived resolves the /usr/bin/wget
// symlink and would run busybox without the applet name.
//
// keepalived checks readiness every second and needs two failures to drop
// out: with 1s adverts the peer takes over about 3–4s after a host dies, or
// 2–3s after its PgBouncer or config goes bad.
var keepalivedTmpl = template.Must(template.New("k").Parse(`# Generated by pgdock-agent keepalived-config (V3 §2.1). Do not edit.
global_defs {
  enable_script_security
  script_user root
}

vrrp_script pgdock_ready {
  script "/bin/busybox wget -q -T 2 -O /dev/null {{.CheckURL}}"
  interval 1
  timeout 2
  fall 2
  rise 2
}

vrrp_instance pgdock_edge {
  state BACKUP
  nopreempt
  interface {{.Interface}}
  virtual_router_id {{.RouterID}}
  priority {{.Priority}}
  advert_int 1
  unicast_src_ip {{.SelfIP}}
  unicast_peer {
    {{.PeerIP}}
  }
  authentication {
    auth_type PASS
    auth_pass "{{.Password}}"
  }
{{- if .VIP}}
  virtual_ipaddress {
    {{.VIP}}/32 dev {{.Interface}}
  }
{{- end}}
  track_script {
    pgdock_ready
  }
  notify_master "/bin/busybox wget -q -T 5 -O /dev/null --post-data= {{.NotifyURL}}/vrrp/MASTER"
  notify_backup "/bin/busybox wget -q -T 5 -O /dev/null --post-data= {{.NotifyURL}}/vrrp/BACKUP"
  notify_fault  "/bin/busybox wget -q -T 5 -O /dev/null --post-data= {{.NotifyURL}}/vrrp/FAULT"
  notify_stop   "/bin/busybox wget -q -T 5 -O /dev/null --post-data= {{.NotifyURL}}/vrrp/STOP"
}
`))

// RenderKeepalived returns keepalived.conf for one pooler host.
func RenderKeepalived(c KeepalivedConfig) ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	var b bytes.Buffer
	if err := keepalivedTmpl.Execute(&b, c); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// SeedPoolerDir writes placeholder files so the PgBouncers can start before
// pgdock-server's first push: no routes, no users, and a short-lived
// self-signed certificate. Existing files are kept. The host is not ready
// (generation 0) until a real configuration arrives.
func SeedPoolerDir(dir string, mode os.FileMode) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	exists := func(name string) bool {
		_, err := os.Stat(filepath.Join(dir, name))
		return err == nil
	}
	write := func(name string, data []byte) error {
		if exists(name) {
			return nil
		}
		_, err := pooler.WriteFileAtomic(filepath.Join(dir, name), data, mode)
		return err
	}
	if err := write("databases.ini", []byte("[databases]\n")); err != nil {
		return err
	}
	if err := write("userlist.txt", nil); err != nil {
		return err
	}
	if exists("server.crt") && exists("server.key") {
		return nil
	}
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return err
	}
	tmpl := &x509.Certificate{
		SerialNumber: big.NewInt(time.Now().UnixNano()),
		Subject:      pkix.Name{CommonName: "pgdock-pooler-placeholder"},
		NotBefore:    time.Now().Add(-time.Minute),
		NotAfter:     time.Now().Add(7 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return err
	}
	kder, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return err
	}
	if _, err := pooler.WriteFileAtomic(filepath.Join(dir, "server.key"), pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: kder}), mode); err != nil {
		return err
	}
	_, err = pooler.WriteFileAtomic(filepath.Join(dir, "server.crt"), pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), mode)
	return err
}

// signalPgBouncers sends SIGHUP (PgBouncer's reload) to the processes
// whose PIDs are in pidfiles. pgdock-server RELOADs over the admin console
// too, but it can only log in once the auth file has its admin user, so the
// first configuration needs this.
func signalPgBouncers(pidfiles []string) error {
	var errs []error
	for _, f := range pidfiles {
		b, err := os.ReadFile(f)
		if err != nil {
			errs = append(errs, err)
			continue
		}
		pid, err := strconv.Atoi(strings.TrimSpace(string(b)))
		if err != nil || pid <= 1 {
			errs = append(errs, fmt.Errorf("%s: not a PID", f))
			continue
		}
		if err := syscall.Kill(pid, syscall.SIGHUP); err != nil {
			errs = append(errs, fmt.Errorf("%s (pid %d): %w", f, pid, err))
		}
	}
	return errors.Join(errs...)
}
