package schemaedit

import (
	"fmt"
	"strings"
	"time"
)

// Migration formats (V2 §4.3).
const (
	FormatSQL    = "sql"
	FormatGoose  = "goose"
	FormatDbmate = "dbmate"
)

// Formats lists the migration formats.
var Formats = []string{FormatSQL, FormatGoose, FormatDbmate}

// Migration is a rendered migration file.
type Migration struct {
	Filename string `json:"filename"`
	Content  string `json:"content"`
	Format   string `json:"format"`
}

func stmt(sql string) string { return strings.TrimRight(sql, "; \n") + ";" }

// Render writes p as a migration file in format, timestamped at.
func Render(p Plan, format string, at time.Time) (Migration, error) {
	at = at.UTC()
	var b strings.Builder
	header := fmt.Sprintf("Generated by PGDock on %s.", at.Format("2006-01-02 15:04 UTC"))
	todo := func(prefix string) {
		for _, t := range p.DownTODO {
			b.WriteString(prefix + "TODO: " + t + "\n")
		}
	}
	switch format {
	case FormatSQL:
		b.WriteString("-- " + p.Slug + "\n-- " + header + "\n")
		if !p.Transactional() {
			b.WriteString("-- Run outside a transaction (CONCURRENTLY).\n")
		}
		b.WriteString("\n")
		for _, s := range p.Statements {
			b.WriteString(stmt(s.SQL) + "\n")
		}
		b.WriteString("\n-- Down:\n")
		for _, d := range p.Down {
			b.WriteString("-- " + strings.ReplaceAll(stmt(d), "\n", "\n-- ") + "\n")
		}
		todo("-- ")
	case FormatGoose:
		b.WriteString("-- " + header + "\n")
		if !p.Transactional() {
			b.WriteString("-- +goose NO TRANSACTION\n")
		}
		b.WriteString("-- +goose Up\n")
		gooseStmts(&b, statementsSQL(p.Statements))
		b.WriteString("\n-- +goose Down\n")
		todo("-- ")
		gooseStmts(&b, p.Down)
	case FormatDbmate:
		b.WriteString("-- " + header + "\n")
		up := "-- migrate:up"
		if !p.Transactional() {
			up += " transaction:false"
		}
		b.WriteString(up + "\n")
		for _, s := range p.Statements {
			b.WriteString(stmt(s.SQL) + "\n")
		}
		b.WriteString("\n-- migrate:down\n")
		todo("-- ")
		for _, d := range p.Down {
			b.WriteString(stmt(d) + "\n")
		}
	default:
		return Migration{}, fmt.Errorf("%w: format is sql, goose or dbmate", ErrInvalid)
	}
	return Migration{Filename: at.Format("20060102150405") + "_" + p.Slug + ".sql", Content: b.String(), Format: format}, nil
}

func statementsSQL(stmts []Statement) []string {
	out := make([]string, len(stmts))
	for i, s := range stmts {
		out[i] = s.SQL
	}
	return out
}

// gooseStmts writes statements for goose, wrapping any with a semicolon
// inside (a string literal, a function body) in StatementBegin/End.
func gooseStmts(b *strings.Builder, stmts []string) {
	for _, s := range stmts {
		s = stmt(s)
		if strings.Contains(strings.TrimSuffix(s, ";"), ";") {
			b.WriteString("-- +goose StatementBegin\n" + s + "\n-- +goose StatementEnd\n")
			continue
		}
		b.WriteString(s + "\n")
	}
}
