#!/bin/sh
# Install or upgrade PGDock on this host with Docker Compose (spec §11.1).
#
#   cd deploy/compose && ./install.sh
#
# On first run it asks for the web UI hostname and an email for Let's
# Encrypt (or reads PGDOCK_UI_DOMAIN and PGDOCK_ACME_EMAIL from the
# environment), writes .env with fresh secrets, builds the images, starts
# the stack, and prints the one-time setup code. Run it again after
# `git checkout <new tag>` to upgrade: .env is kept.
#
# PGDOCK_BUILD_FLAGS is passed to `docker build` (e.g. a proxy CA secret);
# COMPOSE_FILE and COMPOSE_PROJECT_NAME work as for docker compose.
set -eu
cd "$(dirname "$0")"

command -v docker >/dev/null || { echo "Docker is required: https://docs.docker.com/engine/install/" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 is required." >&2; exit 1; }

rand() { head -c "$1" /dev/urandom | base64 | tr -d '\n'; }
rand_url() { rand "$1" | tr '+/' '-_' | tr -d '='; }

if [ ! -f .env ]; then
	ui_domain=${PGDOCK_UI_DOMAIN:-}
	email=${PGDOCK_ACME_EMAIL:-}
	if [ -z "$ui_domain" ]; then
		printf 'Web UI hostname (e.g. pgdock.example.com): '
		read -r ui_domain
	fi
	if [ -z "$email" ]; then
		printf 'Email for Let'"'"'s Encrypt notices: '
		read -r email
	fi
	case "$ui_domain" in
	"" | *[!A-Za-z0-9.-]*) echo "invalid hostname: '$ui_domain'" >&2; exit 1 ;;
	esac
	case "$email" in
	*@*.*) ;;
	*) echo "invalid email: '$email'" >&2; exit 1 ;;
	esac
	public_ip=${PGDOCK_PUBLIC_IPS:-$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)}
	umask 077
	cat > .env <<ENV
# Generated by install.sh. Back this file up: PGDOCK_MASTER_KEY decrypts
# every secret PGDock stores, and losing it loses them.
PGDOCK_UI_DOMAIN=${ui_domain}
PGDOCK_ACME_EMAIL=${email}
PGDOCK_PUBLIC_IPS=${public_ip}
PGDOCK_MASTER_KEY=$(rand 32)
METADATA_DB_PASSWORD=$(rand_url 24)
SHARED_ADMIN_PASSWORD=$(rand_url 24)
POOLER_ADMIN_PASSWORD=$(rand_url 24)
ENV
	echo "Wrote .env (mode 600)."
fi
# Added in later releases; older .env files lack them.
grep -q '^AGENT_BOOTSTRAP_TOKEN=' .env || echo "AGENT_BOOTSTRAP_TOKEN=$(rand_url 32)" >> .env
grep -q '^PGDOCK_PUBLIC_URL=' .env || echo "PGDOCK_PUBLIC_URL=https://$(grep '^PGDOCK_UI_DOMAIN=' .env | cut -d= -f2-)" >> .env

# Dedicated instances and agent-run shared clusters run this image
# (PostgreSQL 18 + WAL-G).
# shellcheck disable=SC2086 # PGDOCK_BUILD_FLAGS is a list of flags
docker build ${PGDOCK_BUILD_FLAGS:-} -t pgdock-postgres:18-walg3.0.9 ../images/postgres
# shellcheck disable=SC2086
docker build ${PGDOCK_BUILD_FLAGS:-} -t "${PGDOCK_IMAGE:-pgdock:local}" ../..
# shellcheck disable=SC2086
docker build ${PGDOCK_BUILD_FLAGS:-} --target agent -t "${PGDOCK_AGENT_IMAGE:-pgdock-agent:local}" ../..
docker compose up -d --no-build --wait

echo
echo "PGDock is running: https://$(grep '^PGDOCK_UI_DOMAIN=' .env | cut -d= -f2-)"
# The server logs JSON ("setup_code":"…") or text (setup_code=…).
code=$(docker compose logs pgdock-server 2>/dev/null | grep -oE 'setup_code"?[=:]"?[A-Za-z0-9_-]+' | tail -1 | sed -E 's/.*[=:]"?//')
if [ -n "$code" ]; then
	echo "First-run setup code: $code"
else
	echo "(Setup is already done, or see: docker compose logs pgdock-server | grep setup_code)"
fi
