import type { ColumnRef, SchemaChange, SchemaColumnDef, TableInfo } from "../../api/client";

// The Create / Edit table and column side panels (docs/ui-redesign.md,
// phase 2): what the user fills in, and the schema changes it becomes.

export type FkAction = NonNullable<ColumnRef["on_delete"]>;

export type ColumnDraft = {
  /** A stable key for the form row. */
  key: string;
  /** The column's name when the panel opened; undefined for a new one. */
  original?: string;
  name: string;
  /** The type without an array suffix. */
  type: string;
  isArray: boolean;
  defaultValue: string;
  /** "identity" makes the column GENERATED BY DEFAULT AS IDENTITY. */
  identity: boolean;
  nullable: boolean;
  unique: boolean;
  primaryKey: boolean;
  check: string;
  comment: string;
  ref: { schema: string; table: string; column: string; onDelete: FkAction; onUpdate: FkAction } | null;
};

export type TableDraft = { schema: string; name: string; comment: string; columns: ColumnDraft[] };

let seq = 0;
const nextKey = () => `c${++seq}`;

export function blankColumn(patch: Partial<ColumnDraft> = {}): ColumnDraft {
  return {
    key: nextKey(),
    name: "",
    type: "text",
    isArray: false,
    defaultValue: "",
    identity: false,
    nullable: true,
    unique: false,
    primaryKey: false,
    check: "",
    comment: "",
    ref: null,
    ...patch,
  };
}

/** Studio's starting columns for a new table: an identity key and a
 * creation time. */
export function newTableColumns(): ColumnDraft[] {
  return [
    blankColumn({ name: "id", type: "int8", identity: true, nullable: false, primaryKey: true }),
    blankColumn({ name: "created_at", type: "timestamptz", defaultValue: "now()", nullable: false }),
  ];
}

const fullType = (c: ColumnDraft) => c.type.trim() + (c.isArray ? "[]" : "");

function columnDef(c: ColumnDraft): SchemaColumnDef {
  const def: SchemaColumnDef = {
    name: c.name.trim(),
    type: fullType(c) + (c.identity ? " generated by default as identity" : ""),
    nullable: c.nullable && !c.primaryKey,
  };
  if (!c.identity && c.defaultValue.trim()) def.default = c.defaultValue.trim();
  if (c.primaryKey) def.primary_key = true;
  if (c.unique && !c.primaryKey) def.unique = true;
  if (c.check.trim()) def.check = c.check.trim();
  if (c.comment.trim()) def.comment = c.comment.trim();
  if (c.ref && c.ref.table && c.ref.column) {
    def.references = { schema: c.ref.schema || undefined, table: c.ref.table, column: c.ref.column, on_delete: c.ref.onDelete, on_update: c.ref.onUpdate };
  }
  return def;
}

/** Problems that stop the form from being saved. */
export function validateTable(t: TableDraft, creating: boolean): string[] {
  const errs: string[] = [];
  if (!t.name.trim()) errs.push("Give the table a name.");
  if (t.columns.length === 0) errs.push("A table needs at least one column.");
  const seen = new Set<string>();
  for (const c of t.columns) {
    const n = c.name.trim();
    if (!n) errs.push("Every column needs a name.");
    else if (seen.has(n)) errs.push(`Column ${n} appears twice.`);
    seen.add(n);
    if (!c.type.trim()) errs.push(`Choose a type for ${n || "every column"}.`);
    if (c.ref && (!c.ref.table || !c.ref.column)) errs.push(`Finish the foreign key on ${n || "a column"}, or remove it.`);
  }
  if (creating && !t.columns.some((c) => c.primaryKey)) {
    // Allowed, but the grid can't edit such a table; the review says so.
  }
  return [...new Set(errs)];
}

export function createTableChange(t: TableDraft): SchemaChange {
  return {
    kind: "create_table",
    schema: t.schema,
    table: t.name.trim(),
    comment: t.comment.trim() || undefined,
    columns: t.columns.map(columnDef),
  };
}

/** The draft of an existing table, to edit. */
export function draftFromTable(info: TableInfo): TableDraft {
  return {
    schema: info.schema,
    name: info.name,
    comment: info.comment ?? "",
    columns: info.columns.map((c) => draftFromColumn(info, c.name)),
  };
}

const singleCol = (cols: string[] | undefined, name: string) => cols?.length === 1 && cols[0] === name;

/** A column's draft, with its single-column constraints. */
export function draftFromColumn(info: TableInfo, name: string): ColumnDraft {
  const c = info.columns.find((x) => x.name === name)!;
  const array = c.category === "A" || c.type.endsWith("[]");
  const fk = info.foreign_keys.find((f) => singleCol(f.columns, name));
  const check = info.constraints.find((k) => k.kind === "check" && singleCol(k.columns, name));
  return blankColumn({
    original: c.name,
    name: c.name,
    type: array ? c.type.replace(/\[\]$/, "") : c.type,
    isArray: array,
    defaultValue: c.default ?? "",
    identity: !!c.identity,
    nullable: c.nullable,
    unique: info.constraints.some((k) => k.kind === "unique" && singleCol(k.columns, name)),
    primaryKey: info.primary_key.includes(name),
    check: check ? checkExpression(check.definition) : "",
    comment: c.comment ?? "",
    ref: fk
      ? { schema: fk.ref_schema, table: fk.ref_table, column: fk.ref_columns[0], onDelete: fk.on_delete as FkAction, onUpdate: fk.on_update as FkAction }
      : null,
  });
}

/** "CHECK ((price > 0))" → "price > 0". */
export function checkExpression(def: string): string {
  const m = /^CHECK \((.*)\)( NOT VALID)?$/s.exec(def.trim());
  if (!m) return def;
  let e = m[1];
  while (e.startsWith("(") && e.endsWith(")") && balanced(e.slice(1, -1))) e = e.slice(1, -1);
  return e;
}

function balanced(s: string): boolean {
  let d = 0;
  for (const ch of s) {
    if (ch === "(") d++;
    if (ch === ")" && --d < 0) return false;
  }
  return d === 0;
}

/** The changes that turn the table into the draft, in an order that
 * works: drops, then changes to existing columns (by their old names),
 * renames, new columns, constraints and comments by the new names, and the
 * table's own rename last. */
export function editTableChanges(info: TableInfo, t: TableDraft): SchemaChange[] {
  const out: SchemaChange[] = [];
  const kept = t.columns.filter((c) => c.original);
  const added = t.columns.filter((c) => !c.original);
  for (const c of info.columns) {
    if (!kept.some((k) => k.original === c.name)) out.push({ kind: "drop_column", column_name: c.name });
  }
  const after: SchemaChange[] = [];
  const renames: SchemaChange[] = [];
  for (const d of kept) {
    const was = draftFromColumn(info, d.original!);
    const { changes, constraints } = columnChanges(info, was, d);
    out.push(...changes);
    if (d.name.trim() !== d.original) renames.push({ kind: "rename_column", column_name: d.original, new_name: d.name.trim() });
    after.push(...constraints);
  }
  out.push(...renames);
  for (const d of added) out.push({ kind: "add_column", column: columnDef(d) });
  out.push(...after);
  if ((info.comment ?? "") !== t.comment.trim()) out.push({ kind: "set_comment", comment: t.comment.trim() });
  if (t.name.trim() !== info.name) out.push({ kind: "rename_table", new_name: t.name.trim() });
  return out;
}

/** One existing column's changes: an alter_column (by its old name), and
 * constraint and comment changes (by its new name, after any rename). */
export function columnChanges(info: TableInfo, was: ColumnDraft, now: ColumnDraft): { changes: SchemaChange[]; constraints: SchemaChange[] } {
  const changes: SchemaChange[] = [];
  const constraints: SchemaChange[] = [];
  const name = now.name.trim();
  const alter: SchemaChange = { kind: "alter_column", column_name: was.name };
  let altered = false;
  if (fullType(now) !== fullType(was)) {
    alter.type = fullType(now);
    altered = true;
  }
  if (!now.identity && now.defaultValue.trim() !== was.defaultValue.trim()) {
    if (now.defaultValue.trim()) alter.default = now.defaultValue.trim();
    else alter.drop_default = true;
    altered = true;
  }
  const nullable = now.nullable && !now.primaryKey;
  if (nullable !== was.nullable) {
    alter.nullable = nullable;
    altered = true;
  }
  if (altered) changes.push(alter);

  const named = (kind: string, pred: (k: TableInfo["constraints"][number]) => boolean) =>
    info.constraints.find((k) => k.kind === kind && singleCol(k.columns, was.name) && pred(k))?.name;
  if (now.unique !== was.unique && !now.primaryKey) {
    if (now.unique) constraints.push({ kind: "add_unique", key_columns: [name] });
    else {
      const n = named("unique", () => true);
      if (n) changes.push({ kind: "drop_constraint", name: n });
    }
  }
  if (now.check.trim() !== was.check.trim()) {
    const n = named("check", () => true);
    if (n) changes.push({ kind: "drop_constraint", name: n });
    if (now.check.trim()) constraints.push({ kind: "add_check", expression: now.check.trim() });
  }
  const refKey = (r: ColumnDraft["ref"]) => (r ? [r.schema, r.table, r.column, r.onDelete, r.onUpdate].join("|") : "");
  if (refKey(now.ref) !== refKey(was.ref)) {
    const fk = info.foreign_keys.find((f) => singleCol(f.columns, was.name));
    if (fk) changes.push({ kind: "drop_constraint", name: fk.name });
    if (now.ref && now.ref.table && now.ref.column) {
      constraints.push({
        kind: "add_foreign_key",
        key_columns: [name],
        ref_schema: now.ref.schema || undefined,
        ref_table: now.ref.table,
        ref_columns: [now.ref.column],
        on_delete: now.ref.onDelete,
        on_update: now.ref.onUpdate,
      });
    }
  }
  if (now.comment.trim() !== was.comment.trim()) constraints.push({ kind: "set_comment", column_name: name, comment: now.comment.trim() });
  return { changes, constraints };
}

/** A batch for an edited table, or the single change when there is one.
 * Null when nothing changed. */
export function asChange(info: TableInfo, changes: SchemaChange[]): SchemaChange | null {
  if (changes.length === 0) return null;
  const scoped = changes.map((c) => ({ ...c, schema: info.schema, table: info.name }));
  if (scoped.length === 1) return scoped[0];
  return { kind: "batch", schema: info.schema, table: info.name, changes: scoped };
}

/** Add-column panel: the change for one new column. */
export function addColumnChange(info: Pick<TableInfo, "schema" | "name">, c: ColumnDraft): SchemaChange {
  return { kind: "add_column", schema: info.schema, table: info.name, column: columnDef(c) };
}

/** Edit-column panel: the changes for one existing column. */
export function editColumnChanges(info: TableInfo, c: ColumnDraft): SchemaChange[] {
  const was = draftFromColumn(info, c.original!);
  const { changes, constraints } = columnChanges(info, was, c);
  const out = [...changes];
  if (c.name.trim() !== c.original) out.push({ kind: "rename_column", column_name: c.original, new_name: c.name.trim() });
  return [...out, ...constraints];
}

/** The types offered by the type picker, grouped as Studio groups them. */
export const TYPE_GROUPS: { label: string; types: { name: string; hint: string }[] }[] = [
  {
    label: "Number",
    types: [
      { name: "int2", hint: "Signed two-byte integer" },
      { name: "int4", hint: "Signed four-byte integer" },
      { name: "int8", hint: "Signed eight-byte integer" },
      { name: "float4", hint: "Single precision floating-point number" },
      { name: "float8", hint: "Double precision floating-point number" },
      { name: "numeric", hint: "Exact numeric of selectable precision" },
    ],
  },
  {
    label: "JSON",
    types: [
      { name: "json", hint: "Textual JSON data" },
      { name: "jsonb", hint: "Binary JSON data, decomposed" },
    ],
  },
  {
    label: "Text",
    types: [
      { name: "text", hint: "Variable-length character string" },
      { name: "varchar", hint: "Variable-length character string" },
      { name: "uuid", hint: "Universally unique identifier" },
    ],
  },
  {
    label: "Time",
    types: [
      { name: "date", hint: "Calendar date (year, month, day)" },
      { name: "time", hint: "Time of day (no time zone)" },
      { name: "timetz", hint: "Time of day, including time zone" },
      { name: "timestamp", hint: "Date and time (no time zone)" },
      { name: "timestamptz", hint: "Date and time, including time zone" },
    ],
  },
  {
    label: "Other",
    types: [
      { name: "bool", hint: "Logical boolean (true/false)" },
      { name: "bytea", hint: "Variable-length binary string" },
    ],
  },
];

export const FK_ACTIONS: FkAction[] = ["NO ACTION", "RESTRICT", "CASCADE", "SET NULL", "SET DEFAULT"];
