// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package store

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addQueryStats = `-- name: AddQueryStats :batchexec
INSERT INTO query_stats (project_id, queryid, bucket, calls, total_ms, rows, shared_blks_hit, shared_blks_read, max_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, queryid, bucket) DO UPDATE SET
  calls = query_stats.calls + EXCLUDED.calls, total_ms = query_stats.total_ms + EXCLUDED.total_ms,
  rows = query_stats.rows + EXCLUDED.rows, shared_blks_hit = query_stats.shared_blks_hit + EXCLUDED.shared_blks_hit,
  shared_blks_read = query_stats.shared_blks_read + EXCLUDED.shared_blks_read, max_ms = GREATEST(query_stats.max_ms, EXCLUDED.max_ms)
`

type AddQueryStatsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddQueryStatsParams struct {
	ProjectID      uuid.UUID
	Queryid        int64
	Bucket         time.Time
	Calls          int64
	TotalMs        float64
	Rows           int64
	SharedBlksHit  int64
	SharedBlksRead int64
	MaxMs          float64
}

// tenant: system - the query insights collector adds a snapshot's deltas.
func (q *Queries) AddQueryStats(ctx context.Context, arg []AddQueryStatsParams) *AddQueryStatsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProjectID,
			a.Queryid,
			a.Bucket,
			a.Calls,
			a.TotalMs,
			a.Rows,
			a.SharedBlksHit,
			a.SharedBlksRead,
			a.MaxMs,
		}
		batch.Queue(addQueryStats, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddQueryStatsBatchResults{br, len(arg), false}
}

func (b *AddQueryStatsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddQueryStatsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertQueryTexts = `-- name: UpsertQueryTexts :batchexec
INSERT INTO query_texts (project_id, queryid, query)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, queryid) DO UPDATE SET query = EXCLUDED.query, last_seen = now()
`

type UpsertQueryTextsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertQueryTextsParams struct {
	ProjectID uuid.UUID
	Queryid   int64
	Query     string
}

// tenant: system - the query insights collector records normalised texts.
func (q *Queries) UpsertQueryTexts(ctx context.Context, arg []UpsertQueryTextsParams) *UpsertQueryTextsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProjectID,
			a.Queryid,
			a.Query,
		}
		batch.Queue(upsertQueryTexts, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertQueryTextsBatchResults{br, len(arg), false}
}

func (b *UpsertQueryTextsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertQueryTextsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
