// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countLedgerTxn = `-- name: CountLedgerTxn :one
SELECT count(*)::int FROM ledger_entries WHERE txn_id = $1
`

// tenant: system - the ledger's posting function.
func (q *Queries) CountLedgerTxn(ctx context.Context, txnID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLedgerTxn, txnID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (txn_id, org_id, account, direction, amount_minor, source_type, source_id, idempotency_key, memo, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id
`

type InsertLedgerEntryParams struct {
	TxnID          uuid.UUID
	OrgID          *uuid.UUID
	Account        string
	Direction      string
	AmountMinor    int64
	SourceType     string
	SourceID       string
	IdempotencyKey string
	Memo           *string
	CreatedBy      *uuid.UUID
}

// tenant: system - the ledger's posting function (rows carry org_id).
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.TxnID,
		arg.OrgID,
		arg.Account,
		arg.Direction,
		arg.AmountMinor,
		arg.SourceType,
		arg.SourceID,
		arg.IdempotencyKey,
		arg.Memo,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ledgerAccountTotals = `-- name: LedgerAccountTotals :many
SELECT account, (coalesce(sum(amount_minor) FILTER (WHERE direction = 'debit'), 0) -
        coalesce(sum(amount_minor) FILTER (WHERE direction = 'credit'), 0))::bigint AS balance
FROM ledger_entries WHERE org_id IS NOT DISTINCT FROM $1 OR $1::uuid IS NULL
GROUP BY account ORDER BY account
`

type LedgerAccountTotalsRow struct {
	Account string
	Balance int64
}

// tenant: system - the ledger check and finance views.
func (q *Queries) LedgerAccountTotals(ctx context.Context, orgID *uuid.UUID) ([]LedgerAccountTotalsRow, error) {
	rows, err := q.db.Query(ctx, ledgerAccountTotals, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerAccountTotalsRow
	for rows.Next() {
		var i LedgerAccountTotalsRow
		if err := rows.Scan(&i.Account, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerBalance = `-- name: LedgerBalance :one
SELECT (coalesce(sum(amount_minor) FILTER (WHERE direction = 'debit'), 0) -
        coalesce(sum(amount_minor) FILTER (WHERE direction = 'credit'), 0))::bigint AS balance
FROM ledger_entries WHERE ($1::uuid IS NULL OR org_id = $1) AND account = $2
`

type LedgerBalanceParams struct {
	OrgID   *uuid.UUID
	Account string
}

// tenant: system - balances of an org the caller resolved (debits minus
// credits); with no org, the account across all of them.
func (q *Queries) LedgerBalance(ctx context.Context, arg LedgerBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, ledgerBalance, arg.OrgID, arg.Account)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const ledgerTotals = `-- name: LedgerTotals :one
SELECT coalesce(sum(amount_minor) FILTER (WHERE direction = 'debit'), 0)::bigint AS debits,
       coalesce(sum(amount_minor) FILTER (WHERE direction = 'credit'), 0)::bigint AS credits,
       count(DISTINCT txn_id)::int AS txns
FROM ledger_entries
`

type LedgerTotalsRow struct {
	Debits  int64
	Credits int64
	Txns    int32
}

// tenant: system - the ledger's invariant check.
func (q *Queries) LedgerTotals(ctx context.Context) (LedgerTotalsRow, error) {
	row := q.db.QueryRow(ctx, ledgerTotals)
	var i LedgerTotalsRow
	err := row.Scan(&i.Debits, &i.Credits, &i.Txns)
	return i, err
}

const orgLedger = `-- name: OrgLedger :many
SELECT id, txn_id, org_id, account, direction, amount_minor, source_type, source_id, idempotency_key, memo, created_by, created_at FROM ledger_entries WHERE org_id = $1 ORDER BY id DESC LIMIT $2
`

type OrgLedgerParams struct {
	OrgID *uuid.UUID
	Lim   int32
}

// tenant: system - the ledger of an org the request already authorized.
func (q *Queries) OrgLedger(ctx context.Context, arg OrgLedgerParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, orgLedger, arg.OrgID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TxnID,
			&i.OrgID,
			&i.Account,
			&i.Direction,
			&i.AmountMinor,
			&i.SourceType,
			&i.SourceID,
			&i.IdempotencyKey,
			&i.Memo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbalancedLedgerTxns = `-- name: UnbalancedLedgerTxns :many
SELECT txn_id, sum(amount_minor) FILTER (WHERE direction = 'debit')::bigint AS debits,
       sum(amount_minor) FILTER (WHERE direction = 'credit')::bigint AS credits
FROM ledger_entries GROUP BY txn_id
HAVING coalesce(sum(amount_minor) FILTER (WHERE direction = 'debit'), 0) <> coalesce(sum(amount_minor) FILTER (WHERE direction = 'credit'), 0)
`

type UnbalancedLedgerTxnsRow struct {
	TxnID   uuid.UUID
	Debits  int64
	Credits int64
}

// tenant: system - the ledger's invariant check.
func (q *Queries) UnbalancedLedgerTxns(ctx context.Context) ([]UnbalancedLedgerTxnsRow, error) {
	rows, err := q.db.Query(ctx, unbalancedLedgerTxns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnbalancedLedgerTxnsRow
	for rows.Next() {
		var i UnbalancedLedgerTxnsRow
		if err := rows.Scan(&i.TxnID, &i.Debits, &i.Credits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
