// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertQuerySnapshots implements pgx.CopyFromSource.
type iteratorForInsertQuerySnapshots struct {
	rows                 []InsertQuerySnapshotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertQuerySnapshots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertQuerySnapshots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].InstanceID,
		r.rows[0].Dbid,
		r.rows[0].Userid,
		r.rows[0].Queryid,
		r.rows[0].Toplevel,
		r.rows[0].Calls,
		r.rows[0].TotalMs,
		r.rows[0].Rows,
		r.rows[0].SharedBlksHit,
		r.rows[0].SharedBlksRead,
		r.rows[0].MaxMs,
		r.rows[0].TakenAt,
	}, nil
}

func (r iteratorForInsertQuerySnapshots) Err() error {
	return nil
}

// tenant: system - the query insights collector keeps the cumulative counters.
func (q *Queries) InsertQuerySnapshots(ctx context.Context, arg []InsertQuerySnapshotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"query_snapshots"}, []string{"instance_id", "dbid", "userid", "queryid", "toplevel", "calls", "total_ms", "rows", "shared_blks_hit", "shared_blks_read", "max_ms", "taken_at"}, &iteratorForInsertQuerySnapshots{rows: arg})
}
