// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costs.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attributedDays = `-- name: AttributedDays :many
SELECT DISTINCT day FROM cost_allocations WHERE day >= $1 AND day < $2 ORDER BY day
`

type AttributedDaysParams struct {
	FromDay pgtype.Date
	ToDay   pgtype.Date
}

// tenant: system - which days have been attributed.
func (q *Queries) AttributedDays(ctx context.Context, arg AttributedDaysParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, attributedDays, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costAllocationsBetween = `-- name: CostAllocationsBetween :many
SELECT day, org_id, category, region, currency, amount_minor, quantity
FROM cost_allocations WHERE day >= $1 AND day < $2 ORDER BY day
`

type CostAllocationsBetweenParams struct {
	FromDay pgtype.Date
	ToDay   pgtype.Date
}

// tenant: system - the margin dashboard, across organisations.
func (q *Queries) CostAllocationsBetween(ctx context.Context, arg CostAllocationsBetweenParams) ([]CostAllocation, error) {
	rows, err := q.db.Query(ctx, costAllocationsBetween, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostAllocation
	for rows.Next() {
		var i CostAllocation
		if err := rows.Scan(
			&i.Day,
			&i.OrgID,
			&i.Category,
			&i.Region,
			&i.Currency,
			&i.AmountMinor,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costConnectionHours = `-- name: CostConnectionHours :many
SELECT scope_id AS project_id, sum(value)::float8 AS connection_hours
FROM metric_points
WHERE scope = 'project' AND resolution = '1h' AND metric IN ('connections_active', 'connections_idle')
  AND ts >= $1 AND ts < $2
GROUP BY scope_id
`

type CostConnectionHoursParams struct {
	DayStart time.Time
	DayEnd   time.Time
}

type CostConnectionHoursRow struct {
	ProjectID       uuid.UUID
	ConnectionHours float64
}

// tenant: system - each project's client connection-hours on a day (hourly
// averages of active and idle backends), for cost attribution.
func (q *Queries) CostConnectionHours(ctx context.Context, arg CostConnectionHoursParams) ([]CostConnectionHoursRow, error) {
	rows, err := q.db.Query(ctx, costConnectionHours, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostConnectionHoursRow
	for rows.Next() {
		var i CostConnectionHoursRow
		if err := rows.Scan(&i.ProjectID, &i.ConnectionHours); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costInstances = `-- name: CostInstances :many
SELECT i.id, i.node_id, i.kind, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.ha_enabled,
  p.id AS project_id, p.org_id
FROM instances i LEFT JOIN projects p ON p.instance_id = i.id AND p.deleted_at IS NULL
WHERE i.deleted_at IS NULL
`

type CostInstancesRow struct {
	ID         uuid.UUID
	NodeID     uuid.UUID
	Kind       string
	CpuLimit   pgtype.Numeric
	MemLimitMb *int32
	VolumeGb   *int32
	HaEnabled  bool
	ProjectID  *uuid.UUID
	OrgID      *uuid.UUID
}

// tenant: system - every live instance and the project on it, for cost attribution.
func (q *Queries) CostInstances(ctx context.Context) ([]CostInstancesRow, error) {
	rows, err := q.db.Query(ctx, costInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostInstancesRow
	for rows.Next() {
		var i CostInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.HaEnabled,
			&i.ProjectID,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costMembers = `-- name: CostMembers :many
SELECT m.node_id, m.instance_id FROM instance_members m WHERE m.deleted_at IS NULL AND m.role <> 'stopped'
`

type CostMembersRow struct {
	NodeID     uuid.UUID
	InstanceID uuid.UUID
}

// tenant: system - HA instances' members (the primary and its standbys):
// the node each runs on, for cost attribution.
func (q *Queries) CostMembers(ctx context.Context) ([]CostMembersRow, error) {
	rows, err := q.db.Query(ctx, costMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostMembersRow
	for rows.Next() {
		var i CostMembersRow
		if err := rows.Scan(&i.NodeID, &i.InstanceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costNodesForDay = `-- name: CostNodesForDay :many
SELECT n.id, n.name, n.region, n.role, n.status, n.monthly_cost_minor, n.cost_currency, n.capacity, n.created_at
FROM nodes n
WHERE n.role <> 'pooler' AND n.monthly_cost_minor IS NOT NULL AND n.created_at < $1
`

type CostNodesForDayRow struct {
	ID               uuid.UUID
	Name             string
	Region           string
	Role             string
	Status           string
	MonthlyCostMinor *int64
	CostCurrency     string
	Capacity         json.RawMessage
	CreatedAt        time.Time
}

// Nodes that existed on the day, with what they cost and what runs there.
func (q *Queries) CostNodesForDay(ctx context.Context, dayEnd time.Time) ([]CostNodesForDayRow, error) {
	rows, err := q.db.Query(ctx, costNodesForDay, dayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostNodesForDayRow
	for rows.Next() {
		var i CostNodesForDayRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Role,
			&i.Status,
			&i.MonthlyCostMinor,
			&i.CostCurrency,
			&i.Capacity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costOrgs = `-- name: CostOrgs :many
SELECT o.id, o.name, o.status, coalesce(b.plan, 'free')::text AS plan
FROM organizations o LEFT JOIN billing_accounts b ON b.org_id = o.id
WHERE o.status <> 'deleted' OR EXISTS (SELECT 1 FROM cost_allocations c WHERE c.org_id = o.id AND c.day >= $1)
`

type CostOrgsRow struct {
	ID     uuid.UUID
	Name   string
	Status string
	Plan   string
}

// tenant: system - organisations with their plan, for the margin dashboard.
func (q *Queries) CostOrgs(ctx context.Context, fromDay pgtype.Date) ([]CostOrgsRow, error) {
	rows, err := q.db.Query(ctx, costOrgs, fromDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostOrgsRow
	for rows.Next() {
		var i CostOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costUsageForDay = `-- name: CostUsageForDay :many
SELECT org_id, project_id, metric, sum(quantity)::float8 AS quantity
FROM usage_records
WHERE period_start >= $1 AND period_start < $2
  AND metric IN ('shared_storage_gb_hours', 'backup_storage_gb_hours', 'pooler_transfer_gb', 'branch_gb_hours')
GROUP BY org_id, project_id, metric
`

type CostUsageForDayParams struct {
	DayStart time.Time
	DayEnd   time.Time
}

type CostUsageForDayRow struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Metric    string
	Quantity  float64
}

// tenant: system - every organisation's usage on a day, for cost attribution.
func (q *Queries) CostUsageForDay(ctx context.Context, arg CostUsageForDayParams) ([]CostUsageForDayRow, error) {
	rows, err := q.db.Query(ctx, costUsageForDay, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostUsageForDayRow
	for rows.Next() {
		var i CostUsageForDayRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ProjectID,
			&i.Metric,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCostAllocations = `-- name: DeleteCostAllocations :exec
DELETE FROM cost_allocations WHERE day = $1
`

// tenant: system - a day's attribution is recomputed whole.
func (q *Queries) DeleteCostAllocations(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteCostAllocations, day)
	return err
}

const fXRateHistory = `-- name: FXRateHistory :many
SELECT id, currency, ngn_per_unit, effective_at, source, set_by, created_at FROM fx_rates ORDER BY effective_at DESC, id DESC LIMIT 200
`

func (q *Queries) FXRateHistory(ctx context.Context) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, fXRateHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FxRate
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.NgnPerUnit,
			&i.EffectiveAt,
			&i.Source,
			&i.SetBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCostAllocation = `-- name: InsertCostAllocation :exec
INSERT INTO cost_allocations (day, org_id, category, region, currency, amount_minor, quantity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (day, org_id, category, region, currency) DO UPDATE
SET amount_minor = cost_allocations.amount_minor + EXCLUDED.amount_minor, quantity = cost_allocations.quantity + EXCLUDED.quantity
`

type InsertCostAllocationParams struct {
	Day         pgtype.Date
	OrgID       uuid.UUID
	Category    string
	Region      string
	Currency    string
	AmountMinor pgtype.Numeric
	Quantity    pgtype.Numeric
}

// tenant: system - the daily cost attribution.
func (q *Queries) InsertCostAllocation(ctx context.Context, arg InsertCostAllocationParams) error {
	_, err := q.db.Exec(ctx, insertCostAllocation,
		arg.Day,
		arg.OrgID,
		arg.Category,
		arg.Region,
		arg.Currency,
		arg.AmountMinor,
		arg.Quantity,
	)
	return err
}

const insertFXRate = `-- name: InsertFXRate :one

INSERT INTO fx_rates (currency, ngn_per_unit, effective_at, source, set_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, currency, ngn_per_unit, effective_at, source, set_by, created_at
`

type InsertFXRateParams struct {
	Currency    string
	NgnPerUnit  pgtype.Numeric
	EffectiveAt time.Time
	Source      string
	SetBy       *uuid.UUID
}

// Cost attribution and exchange rates (V3 §5.4, §7.2).
func (q *Queries) InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, insertFXRate,
		arg.Currency,
		arg.NgnPerUnit,
		arg.EffectiveAt,
		arg.Source,
		arg.SetBy,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.NgnPerUnit,
		&i.EffectiveAt,
		&i.Source,
		&i.SetBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestFXRates = `-- name: LatestFXRates :many
SELECT DISTINCT ON (currency) id, currency, ngn_per_unit, effective_at, source, set_by, created_at FROM fx_rates WHERE effective_at <= $1 ORDER BY currency, effective_at DESC, id DESC
`

func (q *Queries) LatestFXRates(ctx context.Context, at time.Time) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, latestFXRates, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FxRate
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.NgnPerUnit,
			&i.EffectiveAt,
			&i.Source,
			&i.SetBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgCostAllocations = `-- name: OrgCostAllocations :many
SELECT day, category, region, currency, amount_minor, quantity
FROM cost_allocations WHERE org_id = $1 AND day >= $2 AND day < $3 ORDER BY day
`

type OrgCostAllocationsParams struct {
	OrgID   uuid.UUID
	FromDay pgtype.Date
	ToDay   pgtype.Date
}

type OrgCostAllocationsRow struct {
	Day         pgtype.Date
	Category    string
	Region      string
	Currency    string
	AmountMinor pgtype.Numeric
	Quantity    pgtype.Numeric
}

func (q *Queries) OrgCostAllocations(ctx context.Context, arg OrgCostAllocationsParams) ([]OrgCostAllocationsRow, error) {
	rows, err := q.db.Query(ctx, orgCostAllocations, arg.OrgID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgCostAllocationsRow
	for rows.Next() {
		var i OrgCostAllocationsRow
		if err := rows.Scan(
			&i.Day,
			&i.Category,
			&i.Region,
			&i.Currency,
			&i.AmountMinor,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
