// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: freetier.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archivedProjects = `-- name: ArchivedProjects :many
SELECT p.id, p.name, p.slug, p.db_name, p.owner_role, p.scram_verifier, p.tier, p.instance_id, p.status, p.settings, p.storage_target_id, p.extensions, p.description, p.created_by, p.created_at, p.deleted_at, p.org_id, p.alias_db_name, p.legacy_owner_role, p.legacy_scram_verifier, p.legacy_until, p.storage_state, p.storage_state_at, p.backup_key_id, p.parent_project_id, p.branch_source, p.branch_schema_only, p.expires_at, p.expiry_notified_at, p.branch_backups, p.sensitive_data, p.probe_verifier, p.lifecycle, p.last_active_at, p.pause_warned_at, p.paused_at, p.archived_at, p.archive_backup_id, p.archive_notice_days FROM projects p
WHERE p.deleted_at IS NULL AND p.lifecycle = 'archived'
ORDER BY p.archived_at
`

// tenant: system - the Free tier sweep across organisations: every archived project, oldest first.
func (q *Queries) ArchivedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, archivedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
			&i.Lifecycle,
			&i.LastActiveAt,
			&i.PauseWarnedAt,
			&i.PausedAt,
			&i.ArchivedAt,
			&i.ArchiveBackupID,
			&i.ArchiveNoticeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSleepingProjects = `-- name: CountSleepingProjects :one
SELECT count(*) FILTER (WHERE lifecycle = 'paused')::bigint AS paused, count(*) FILTER (WHERE lifecycle = 'archived')::bigint AS archived
FROM projects WHERE deleted_at IS NULL
`

type CountSleepingProjectsRow struct {
	Paused   int64
	Archived int64
}

// tenant: system - admin console totals of paused and archived projects.
func (q *Queries) CountSleepingProjects(ctx context.Context) (CountSleepingProjectsRow, error) {
	row := q.db.QueryRow(ctx, countSleepingProjects)
	var i CountSleepingProjectsRow
	err := row.Scan(&i.Paused, &i.Archived)
	return i, err
}

const freeProjectsIdleSince = `-- name: FreeProjectsIdleSince :many
SELECT p.id, p.name, p.slug, p.db_name, p.owner_role, p.scram_verifier, p.tier, p.instance_id, p.status, p.settings, p.storage_target_id, p.extensions, p.description, p.created_by, p.created_at, p.deleted_at, p.org_id, p.alias_db_name, p.legacy_owner_role, p.legacy_scram_verifier, p.legacy_until, p.storage_state, p.storage_state_at, p.backup_key_id, p.parent_project_id, p.branch_source, p.branch_schema_only, p.expires_at, p.expiry_notified_at, p.branch_backups, p.sensitive_data, p.probe_verifier, p.lifecycle, p.last_active_at, p.pause_warned_at, p.paused_at, p.archived_at, p.archive_backup_id, p.archive_notice_days FROM projects p
JOIN organizations o ON o.id = p.org_id
LEFT JOIN billing_accounts b ON b.org_id = p.org_id
WHERE p.deleted_at IS NULL AND p.status = 'active' AND p.lifecycle = 'active' AND p.tier = 'shared'
  AND o.status = 'active' AND coalesce(b.plan, 'free') = 'free'
  AND coalesce(p.last_active_at, p.created_at) < $1
ORDER BY p.created_at
`

// tenant: system - the Free tier sweep across organisations: active Free projects idle since before @idle_before.
func (q *Queries) FreeProjectsIdleSince(ctx context.Context, idleBefore *time.Time) ([]Project, error) {
	rows, err := q.db.Query(ctx, freeProjectsIdleSince, idleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
			&i.Lifecycle,
			&i.LastActiveAt,
			&i.PauseWarnedAt,
			&i.PausedAt,
			&i.ArchivedAt,
			&i.ArchiveBackupID,
			&i.ArchiveNoticeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const freeProjectsPausedSince = `-- name: FreeProjectsPausedSince :many
SELECT p.id, p.name, p.slug, p.db_name, p.owner_role, p.scram_verifier, p.tier, p.instance_id, p.status, p.settings, p.storage_target_id, p.extensions, p.description, p.created_by, p.created_at, p.deleted_at, p.org_id, p.alias_db_name, p.legacy_owner_role, p.legacy_scram_verifier, p.legacy_until, p.storage_state, p.storage_state_at, p.backup_key_id, p.parent_project_id, p.branch_source, p.branch_schema_only, p.expires_at, p.expiry_notified_at, p.branch_backups, p.sensitive_data, p.probe_verifier, p.lifecycle, p.last_active_at, p.pause_warned_at, p.paused_at, p.archived_at, p.archive_backup_id, p.archive_notice_days FROM projects p
LEFT JOIN billing_accounts b ON b.org_id = p.org_id
WHERE p.deleted_at IS NULL AND p.status = 'active' AND p.lifecycle = 'paused' AND p.paused_at < $1
  AND coalesce(b.plan, 'free') = 'free'
ORDER BY p.paused_at
`

// tenant: system - the Free tier sweep across organisations: Free projects paused before @paused_before.
func (q *Queries) FreeProjectsPausedSince(ctx context.Context, pausedBefore *time.Time) ([]Project, error) {
	rows, err := q.db.Query(ctx, freeProjectsPausedSince, pausedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
			&i.Lifecycle,
			&i.LastActiveAt,
			&i.PauseWarnedAt,
			&i.PausedAt,
			&i.ArchivedAt,
			&i.ArchiveBackupID,
			&i.ArchiveNoticeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPauseWarned = `-- name: MarkPauseWarned :exec
UPDATE projects SET pause_warned_at = now() WHERE id = $1
`

// tenant: system - the Free tier sweep records the 24-hour notice.
func (q *Queries) MarkPauseWarned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPauseWarned, id)
	return err
}

const projectByDatabase = `-- name: ProjectByDatabase :one
SELECT id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier, lifecycle, last_active_at, pause_warned_at, paused_at, archived_at, archive_backup_id, archive_notice_days FROM projects WHERE (db_name = $1 OR alias_db_name = $1) AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT 1
`

// tenant: system - the waker looks up a client-facing database name across organisations.
func (q *Queries) ProjectByDatabase(ctx context.Context, db string) (Project, error) {
	row := q.db.QueryRow(ctx, projectByDatabase, db)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbName,
		&i.OwnerRole,
		&i.ScramVerifier,
		&i.Tier,
		&i.InstanceID,
		&i.Status,
		&i.Settings,
		&i.StorageTargetID,
		&i.Extensions,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.AliasDbName,
		&i.LegacyOwnerRole,
		&i.LegacyScramVerifier,
		&i.LegacyUntil,
		&i.StorageState,
		&i.StorageStateAt,
		&i.BackupKeyID,
		&i.ParentProjectID,
		&i.BranchSource,
		&i.BranchSchemaOnly,
		&i.ExpiresAt,
		&i.ExpiryNotifiedAt,
		&i.BranchBackups,
		&i.SensitiveData,
		&i.ProbeVerifier,
		&i.Lifecycle,
		&i.LastActiveAt,
		&i.PauseWarnedAt,
		&i.PausedAt,
		&i.ArchivedAt,
		&i.ArchiveBackupID,
		&i.ArchiveNoticeDays,
	)
	return i, err
}

const setArchiveNotice = `-- name: SetArchiveNotice :exec
UPDATE projects SET archive_notice_days = $1 WHERE id = $2
`

type SetArchiveNoticeParams struct {
	Days *int32
	ID   uuid.UUID
}

// tenant: system - the Free tier sweep records a deletion notice sent.
func (q *Queries) SetArchiveNotice(ctx context.Context, arg SetArchiveNoticeParams) error {
	_, err := q.db.Exec(ctx, setArchiveNotice, arg.Days, arg.ID)
	return err
}

const setProjectArchived = `-- name: SetProjectArchived :one
UPDATE projects SET lifecycle = 'archived', archived_at = now(), archive_backup_id = $1
WHERE id = $2 AND lifecycle = 'paused' RETURNING id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier, lifecycle, last_active_at, pause_warned_at, paused_at, archived_at, archive_backup_id, archive_notice_days
`

type SetProjectArchivedParams struct {
	BackupID *uuid.UUID
	ID       uuid.UUID
}

// tenant: system - an archive operation on a project it already loaded.
func (q *Queries) SetProjectArchived(ctx context.Context, arg SetProjectArchivedParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectArchived, arg.BackupID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbName,
		&i.OwnerRole,
		&i.ScramVerifier,
		&i.Tier,
		&i.InstanceID,
		&i.Status,
		&i.Settings,
		&i.StorageTargetID,
		&i.Extensions,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.AliasDbName,
		&i.LegacyOwnerRole,
		&i.LegacyScramVerifier,
		&i.LegacyUntil,
		&i.StorageState,
		&i.StorageStateAt,
		&i.BackupKeyID,
		&i.ParentProjectID,
		&i.BranchSource,
		&i.BranchSchemaOnly,
		&i.ExpiresAt,
		&i.ExpiryNotifiedAt,
		&i.BranchBackups,
		&i.SensitiveData,
		&i.ProbeVerifier,
		&i.Lifecycle,
		&i.LastActiveAt,
		&i.PauseWarnedAt,
		&i.PausedAt,
		&i.ArchivedAt,
		&i.ArchiveBackupID,
		&i.ArchiveNoticeDays,
	)
	return i, err
}

const setProjectAwake = `-- name: SetProjectAwake :one
UPDATE projects SET lifecycle = 'active', paused_at = NULL, archived_at = NULL, pause_warned_at = NULL,
  archive_notice_days = NULL, last_active_at = now()
WHERE id = $1 RETURNING id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier, lifecycle, last_active_at, pause_warned_at, paused_at, archived_at, archive_backup_id, archive_notice_days
`

// tenant: system - a resume or unarchive operation on a project it already loaded.
func (q *Queries) SetProjectAwake(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectAwake, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbName,
		&i.OwnerRole,
		&i.ScramVerifier,
		&i.Tier,
		&i.InstanceID,
		&i.Status,
		&i.Settings,
		&i.StorageTargetID,
		&i.Extensions,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.AliasDbName,
		&i.LegacyOwnerRole,
		&i.LegacyScramVerifier,
		&i.LegacyUntil,
		&i.StorageState,
		&i.StorageStateAt,
		&i.BackupKeyID,
		&i.ParentProjectID,
		&i.BranchSource,
		&i.BranchSchemaOnly,
		&i.ExpiresAt,
		&i.ExpiryNotifiedAt,
		&i.BranchBackups,
		&i.SensitiveData,
		&i.ProbeVerifier,
		&i.Lifecycle,
		&i.LastActiveAt,
		&i.PauseWarnedAt,
		&i.PausedAt,
		&i.ArchivedAt,
		&i.ArchiveBackupID,
		&i.ArchiveNoticeDays,
	)
	return i, err
}

const setProjectPaused = `-- name: SetProjectPaused :one
UPDATE projects SET lifecycle = 'paused', paused_at = now() WHERE id = $1 AND lifecycle = 'active' RETURNING id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier, lifecycle, last_active_at, pause_warned_at, paused_at, archived_at, archive_backup_id, archive_notice_days
`

// tenant: system - a pause operation on a project it already loaded.
func (q *Queries) SetProjectPaused(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectPaused, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbName,
		&i.OwnerRole,
		&i.ScramVerifier,
		&i.Tier,
		&i.InstanceID,
		&i.Status,
		&i.Settings,
		&i.StorageTargetID,
		&i.Extensions,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.AliasDbName,
		&i.LegacyOwnerRole,
		&i.LegacyScramVerifier,
		&i.LegacyUntil,
		&i.StorageState,
		&i.StorageStateAt,
		&i.BackupKeyID,
		&i.ParentProjectID,
		&i.BranchSource,
		&i.BranchSchemaOnly,
		&i.ExpiresAt,
		&i.ExpiryNotifiedAt,
		&i.BranchBackups,
		&i.SensitiveData,
		&i.ProbeVerifier,
		&i.Lifecycle,
		&i.LastActiveAt,
		&i.PauseWarnedAt,
		&i.PausedAt,
		&i.ArchivedAt,
		&i.ArchiveBackupID,
		&i.ArchiveNoticeDays,
	)
	return i, err
}

const sleepingPaidProjects = `-- name: SleepingPaidProjects :many
SELECT p.id, p.name, p.slug, p.db_name, p.owner_role, p.scram_verifier, p.tier, p.instance_id, p.status, p.settings, p.storage_target_id, p.extensions, p.description, p.created_by, p.created_at, p.deleted_at, p.org_id, p.alias_db_name, p.legacy_owner_role, p.legacy_scram_verifier, p.legacy_until, p.storage_state, p.storage_state_at, p.backup_key_id, p.parent_project_id, p.branch_source, p.branch_schema_only, p.expires_at, p.expiry_notified_at, p.branch_backups, p.sensitive_data, p.probe_verifier, p.lifecycle, p.last_active_at, p.pause_warned_at, p.paused_at, p.archived_at, p.archive_backup_id, p.archive_notice_days FROM projects p
JOIN billing_accounts b ON b.org_id = p.org_id
WHERE p.deleted_at IS NULL AND p.status = 'active' AND p.lifecycle <> 'active' AND b.plan <> 'free'
`

// tenant: system - the Free tier sweep across organisations: paused or archived projects whose organisation now pays.
func (q *Queries) SleepingPaidProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, sleepingPaidProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
			&i.Lifecycle,
			&i.LastActiveAt,
			&i.PauseWarnedAt,
			&i.PausedAt,
			&i.ArchivedAt,
			&i.ArchiveBackupID,
			&i.ArchiveNoticeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProjectsActive = `-- name: TouchProjectsActive :exec

UPDATE projects SET last_active_at = now(), pause_warned_at = NULL
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

// The Free tier's pause and archive (V3 §4).
// tenant: system - the metrics collector marks projects clients used, across organisations.
func (q *Queries) TouchProjectsActive(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchProjectsActive, ids)
	return err
}
