// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const announcedMaintenanceFor = `-- name: AnnouncedMaintenanceFor :one
SELECT i.id FROM incidents i, projects p, (SELECT $1::timestamptz AS at) w
WHERE p.id = $2 AND i.severity = 'maintenance' AND i.announced_at IS NOT NULL AND i.cancelled_at IS NULL
  AND w.at >= i.scheduled_start AND w.at < i.scheduled_end
  AND i.announced_at <= w.at - interval '72 hours' AND maintenance_covers(i, p)
ORDER BY i.announced_at LIMIT 1
`

type AnnouncedMaintenanceForParams struct {
	At        time.Time
	ProjectID uuid.UUID
}

// tenant: system - the announcement, made 72 hours ahead, covering a project at a moment (the maintenance window's gate).
func (q *Queries) AnnouncedMaintenanceFor(ctx context.Context, arg AnnouncedMaintenanceForParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, announcedMaintenanceFor, arg.At, arg.ProjectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const cancelMaintenance = `-- name: CancelMaintenance :one
UPDATE incidents SET cancelled_at = now(), status = 'resolved', resolved_at = now(), updated_at = now()
WHERE id = $1 AND severity = 'maintenance' AND announced_at IS NOT NULL AND cancelled_at IS NULL AND resolved_at IS NULL
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

// tenant: system - a maintenance announcement called off.
func (q *Queries) CancelMaintenance(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, cancelMaintenance, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const confirmDraft = `-- name: ConfirmDraft :one
UPDATE incidents SET status = 'identified', announced_at = now(), pushed_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'draft' AND scheduled_start > now()
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

// tenant: system - a draft announced: from now its notice counts.
func (q *Queries) ConfirmDraft(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, confirmDraft, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const dedicatedNodeHealth = `-- name: DedicatedNodeHealth :one
SELECT count(*) AS total,
  count(*) FILTER (WHERE EXISTS (
    SELECT 1 FROM alerts a WHERE a.status = 'firing' AND a.kind = 'node_unreachable' AND a.target_id = n.id::text
  )) AS unreachable
FROM nodes n WHERE n.role IN ('dedicated', 'both') AND n.status <> 'removed'
`

type DedicatedNodeHealthRow struct {
	Total       int64
	Unreachable int64
}

// tenant: system - the status heartbeat counts unreachable nodes from the platform's own alerts.
// How many dedicated-capable nodes there are and how many are unreachable
// (a firing node_unreachable alert), for the status heartbeat.
func (q *Queries) DedicatedNodeHealth(ctx context.Context) (DedicatedNodeHealthRow, error) {
	row := q.db.QueryRow(ctx, dedicatedNodeHealth)
	var i DedicatedNodeHealthRow
	err := row.Scan(&i.Total, &i.Unreachable)
	return i, err
}

const discardDraft = `-- name: DiscardDraft :one
UPDATE incidents SET status = 'resolved', resolved_at = now(), cancelled_at = now(), updated_at = now()
WHERE id = $1 AND status = 'draft'
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

// tenant: system - a draft thrown away; the work it was for keeps waiting.
func (q *Queries) DiscardDraft(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, discardDraft, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const expireDrafts = `-- name: ExpireDrafts :execrows
UPDATE incidents SET status = 'resolved', resolved_at = now(), cancelled_at = now(), updated_at = now()
WHERE status = 'draft' AND scheduled_start <= $1::timestamptz
`

// tenant: system - drafts whose window started unconfirmed.
func (q *Queries) ExpireDrafts(ctx context.Context, at time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireDrafts, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIncident = `-- name: GetIncident :one
SELECT id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const incidentScope = `-- name: IncidentScope :many
SELECT incident_id, project_id, node_id FROM incident_scope WHERE incident_id = $1
`

// tenant: system - what a maintenance announcement covers.
func (q *Queries) IncidentScope(ctx context.Context, incidentID uuid.UUID) ([]IncidentScope, error) {
	rows, err := q.db.Query(ctx, incidentScope, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentScope
	for rows.Next() {
		var i IncidentScope
		if err := rows.Scan(&i.IncidentID, &i.ProjectID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incidentUpdates = `-- name: IncidentUpdates :many
SELECT u.id, u.incident_id, u.status, u.body, u.posted_by, u.posted_at, users.email AS posted_by_email
FROM incident_updates u LEFT JOIN users ON users.id = u.posted_by
WHERE u.incident_id = $1
ORDER BY u.posted_at, u.id
`

type IncidentUpdatesRow struct {
	ID            int64
	IncidentID    uuid.UUID
	Status        string
	Body          string
	PostedBy      *uuid.UUID
	PostedAt      time.Time
	PostedByEmail *string
}

func (q *Queries) IncidentUpdates(ctx context.Context, incidentID uuid.UUID) ([]IncidentUpdatesRow, error) {
	rows, err := q.db.Query(ctx, incidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentUpdatesRow
	for rows.Next() {
		var i IncidentUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Body,
			&i.PostedBy,
			&i.PostedAt,
			&i.PostedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIncident = `-- name: InsertIncident :one

INSERT INTO incidents (title, components, region_id, severity, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

type InsertIncidentParams struct {
	Title      string
	Components []string
	RegionID   *string
	Severity   string
	Status     string
	CreatedBy  *uuid.UUID
}

// Incidents (V3 §2.6): the platform admin's, pushed to pgdock-status.
func (q *Queries) InsertIncident(ctx context.Context, arg InsertIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, insertIncident,
		arg.Title,
		arg.Components,
		arg.RegionID,
		arg.Severity,
		arg.Status,
		arg.CreatedBy,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const insertIncidentScope = `-- name: InsertIncidentScope :exec
INSERT INTO incident_scope (incident_id, project_id, node_id) VALUES ($1, $2, $3)
`

type InsertIncidentScopeParams struct {
	IncidentID uuid.UUID
	ProjectID  *uuid.UUID
	NodeID     *uuid.UUID
}

// tenant: system - what a maintenance announcement covers.
func (q *Queries) InsertIncidentScope(ctx context.Context, arg InsertIncidentScopeParams) error {
	_, err := q.db.Exec(ctx, insertIncidentScope, arg.IncidentID, arg.ProjectID, arg.NodeID)
	return err
}

const insertIncidentUpdate = `-- name: InsertIncidentUpdate :one
INSERT INTO incident_updates (incident_id, status, body, posted_by)
VALUES ($1, $2, $3, $4)
RETURNING id, incident_id, status, body, posted_by, posted_at
`

type InsertIncidentUpdateParams struct {
	IncidentID uuid.UUID
	Status     string
	Body       string
	PostedBy   *uuid.UUID
}

func (q *Queries) InsertIncidentUpdate(ctx context.Context, arg InsertIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRow(ctx, insertIncidentUpdate,
		arg.IncidentID,
		arg.Status,
		arg.Body,
		arg.PostedBy,
	)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Body,
		&i.PostedBy,
		&i.PostedAt,
	)
	return i, err
}

const insertMaintenance = `-- name: InsertMaintenance :one

INSERT INTO incidents (title, components, region_id, severity, status, created_by, started_at, scheduled_start, scheduled_end, announced_at, replaces)
VALUES ($1, $2, $3, 'maintenance', 'identified', $4, $5, $5, $6, now(), $7)
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

type InsertMaintenanceParams struct {
	Title          string
	Components     []string
	RegionID       *string
	CreatedBy      *uuid.UUID
	ScheduledStart time.Time
	ScheduledEnd   *time.Time
	Replaces       *uuid.UUID
}

// ---- Announced maintenance (V3.1 4) -----------------------------------------
// tenant: system - platform maintenance announcements.
func (q *Queries) InsertMaintenance(ctx context.Context, arg InsertMaintenanceParams) (Incident, error) {
	row := q.db.QueryRow(ctx, insertMaintenance,
		arg.Title,
		arg.Components,
		arg.RegionID,
		arg.CreatedBy,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.Replaces,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const insertMaintenanceDraft = `-- name: InsertMaintenanceDraft :one
INSERT INTO incidents (title, components, region_id, severity, status, started_at, scheduled_start, scheduled_end, proposed_for)
VALUES ($1, $2, NULL, 'maintenance', 'draft', $3, $3, $4, $5)
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

type InsertMaintenanceDraftParams struct {
	Title          string
	Components     []string
	ScheduledStart time.Time
	ScheduledEnd   *time.Time
	ProposedFor    *string
}

// tenant: system - maintenance PGDock proposes; not announced until confirmed.
func (q *Queries) InsertMaintenanceDraft(ctx context.Context, arg InsertMaintenanceDraftParams) (Incident, error) {
	row := q.db.QueryRow(ctx, insertMaintenanceDraft,
		arg.Title,
		arg.Components,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.ProposedFor,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for FROM incidents WHERE NOT (severity = 'maintenance' AND announced_at IS NULL)
ORDER BY (resolved_at IS NULL) DESC, started_at DESC LIMIT $1
`

func (q *Queries) ListIncidents(ctx context.Context, lim int32) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Components,
			&i.RegionID,
			&i.Severity,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.PushedAt,
			&i.PushError,
			&i.UpdatedAt,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.AnnouncedAt,
			&i.CancelledAt,
			&i.Replaces,
			&i.ProposedFor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenance = `-- name: ListMaintenance :many
SELECT id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for FROM incidents WHERE (announced_at IS NOT NULL OR proposed_for IS NOT NULL) AND scheduled_end >= $1::timestamptz
ORDER BY scheduled_start DESC LIMIT $2
`

type ListMaintenanceParams struct {
	Since time.Time
	Lim   int32
}

// tenant: system - maintenance announcements, newest window first.
func (q *Queries) ListMaintenance(ctx context.Context, arg ListMaintenanceParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listMaintenance, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Components,
			&i.RegionID,
			&i.Severity,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.PushedAt,
			&i.PushError,
			&i.UpdatedAt,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.AnnouncedAt,
			&i.CancelledAt,
			&i.Replaces,
			&i.ProposedFor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenanceDone = `-- name: MaintenanceDone :many
UPDATE incidents SET status = 'resolved', resolved_at = scheduled_end, updated_at = now()
WHERE severity = 'maintenance' AND announced_at IS NOT NULL AND resolved_at IS NULL AND scheduled_end <= $1::timestamptz
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

// tenant: system - announced maintenance whose window has ended.
func (q *Queries) MaintenanceDone(ctx context.Context, at time.Time) ([]Incident, error) {
	rows, err := q.db.Query(ctx, maintenanceDone, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Components,
			&i.RegionID,
			&i.Severity,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.PushedAt,
			&i.PushError,
			&i.UpdatedAt,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.AnnouncedAt,
			&i.CancelledAt,
			&i.Replaces,
			&i.ProposedFor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenanceOrgEmails = `-- name: MaintenanceOrgEmails :many
SELECT DISTINCT u.email FROM users u
JOIN org_members m ON m.user_id = u.id AND m.role IN ('owner', 'admin')
JOIN projects p ON p.org_id = m.org_id AND p.deleted_at IS NULL
JOIN incidents i ON i.id = $1
WHERE u.disabled_at IS NULL AND maintenance_covers(i, p)
ORDER BY u.email
`

// tenant: system - who is told of an announcement: owners and admins of the organisations with live projects it covers.
func (q *Queries) MaintenanceOrgEmails(ctx context.Context, incidentID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, maintenanceOrgEmails, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenancePlannedFor = `-- name: MaintenancePlannedFor :one
SELECT EXISTS (
  SELECT 1 FROM incidents i, projects p
  WHERE p.id = $1 AND i.severity = 'maintenance' AND i.scheduled_end > $2::timestamptz
    AND (i.announced_at IS NOT NULL OR i.status = 'draft' OR i.proposed_for IS NOT NULL)
    AND (i.cancelled_at IS NULL OR (i.announced_at IS NULL AND i.scheduled_start = $3::timestamptz))
    AND maintenance_covers(i, p))::bool
`

type MaintenancePlannedForParams struct {
	ProjectID   uuid.UUID
	Now         time.Time
	WindowStart time.Time
}

// tenant: system - whether a project already has maintenance ahead (announced, or a draft), or had a draft for that window discarded.
func (q *Queries) MaintenancePlannedFor(ctx context.Context, arg MaintenancePlannedForParams) (bool, error) {
	row := q.db.QueryRow(ctx, maintenancePlannedFor, arg.ProjectID, arg.Now, arg.WindowStart)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const maintenanceRecipients = `-- name: MaintenanceRecipients :many
SELECT DISTINCT m.org_id, u.email::text AS email FROM users u
JOIN org_members m ON m.user_id = u.id AND m.role IN ('owner', 'admin')
JOIN projects p ON p.org_id = m.org_id AND p.deleted_at IS NULL
WHERE u.disabled_at IS NULL AND (
  CASE WHEN cardinality($1::uuid[]) + cardinality($2::uuid[]) > 0 THEN
    p.id = ANY($1::uuid[])
    OR EXISTS (SELECT 1 FROM instance_members im WHERE im.instance_id = p.instance_id AND im.deleted_at IS NULL AND im.node_id = ANY($2::uuid[]))
    OR (SELECT n.node_id FROM instances n WHERE n.id = p.instance_id) = ANY($2::uuid[])
  ELSE $3::text IS NULL OR p.region = $3::text END)
ORDER BY email
`

type MaintenanceRecipientsParams struct {
	ProjectIds []uuid.UUID
	NodeIds    []uuid.UUID
	Region     *string
}

type MaintenanceRecipientsRow struct {
	OrgID uuid.UUID
	Email string
}

// tenant: system - who an announcement of this scope would reach: owners and admins of organisations with live projects it covers (as maintenance_covers).
func (q *Queries) MaintenanceRecipients(ctx context.Context, arg MaintenanceRecipientsParams) ([]MaintenanceRecipientsRow, error) {
	rows, err := q.db.Query(ctx, maintenanceRecipients, arg.ProjectIds, arg.NodeIds, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceRecipientsRow
	for rows.Next() {
		var i MaintenanceRecipientsRow
		if err := rows.Scan(&i.OrgID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIncidentPushFailed = `-- name: MarkIncidentPushFailed :exec
UPDATE incidents SET push_error = $1 WHERE id = $2
`

type MarkIncidentPushFailedParams struct {
	PushError *string
	ID        uuid.UUID
}

func (q *Queries) MarkIncidentPushFailed(ctx context.Context, arg MarkIncidentPushFailedParams) error {
	_, err := q.db.Exec(ctx, markIncidentPushFailed, arg.PushError, arg.ID)
	return err
}

const markIncidentPushed = `-- name: MarkIncidentPushed :exec
UPDATE incidents SET pushed_at = now(), push_error = NULL WHERE id = $1 AND updated_at = $2
`

type MarkIncidentPushedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

// Only if nothing changed while the push was in flight.
func (q *Queries) MarkIncidentPushed(ctx context.Context, arg MarkIncidentPushedParams) error {
	_, err := q.db.Exec(ctx, markIncidentPushed, arg.ID, arg.UpdatedAt)
	return err
}

const openDraftFor = `-- name: OpenDraftFor :one
SELECT id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for FROM incidents WHERE status = 'draft' AND proposed_for = $1 AND scheduled_start = $2
ORDER BY started_at, id LIMIT 1
`

type OpenDraftForParams struct {
	ProposedFor    *string
	ScheduledStart *time.Time
}

// tenant: system - the open draft proposed for a window and a reason, to add projects to.
func (q *Queries) OpenDraftFor(ctx context.Context, arg OpenDraftForParams) (Incident, error) {
	row := q.db.QueryRow(ctx, openDraftFor, arg.ProposedFor, arg.ScheduledStart)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}

const overdueJobs = `-- name: OverdueJobs :one
SELECT count(*) FROM scheduled_jobs j JOIN projects p ON p.id = j.project_id
WHERE j.enabled AND j.next_run_at < now() - interval '5 minutes' AND p.deleted_at IS NULL
`

// tenant: system - the status heartbeat counts platform-wide scheduler lag, not any organisation's data.
// The same jobs DueJobs picks: a deleted project's jobs never run.
func (q *Queries) OverdueJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, overdueJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unpushedIncidents = `-- name: UnpushedIncidents :many
SELECT id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for FROM incidents WHERE pushed_at IS NULL AND NOT (severity = 'maintenance' AND announced_at IS NULL)
ORDER BY updated_at LIMIT 20
`

// Changed since the last push (or never pushed), oldest change first.
// Maintenance drafts (never announced) stay off the status page.
func (q *Queries) UnpushedIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, unpushedIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Components,
			&i.RegionID,
			&i.Severity,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.PushedAt,
			&i.PushError,
			&i.UpdatedAt,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.AnnouncedAt,
			&i.CancelledAt,
			&i.Replaces,
			&i.ProposedFor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents SET title = $1, components = $2, region_id = $3, severity = $4,
  status = $5, resolved_at = $6, pushed_at = NULL, updated_at = now()
WHERE id = $7
RETURNING id, title, components, region_id, severity, status, started_at, resolved_at, created_by, pushed_at, push_error, updated_at, scheduled_start, scheduled_end, announced_at, cancelled_at, replaces, proposed_for
`

type UpdateIncidentParams struct {
	Title      string
	Components []string
	RegionID   *string
	Severity   string
	Status     string
	ResolvedAt *time.Time
	ID         uuid.UUID
}

// A change clears pushed_at so the pusher sends it again.
func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Title,
		arg.Components,
		arg.RegionID,
		arg.Severity,
		arg.Status,
		arg.ResolvedAt,
		arg.ID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Components,
		&i.RegionID,
		&i.Severity,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.PushedAt,
		&i.PushError,
		&i.UpdatedAt,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.AnnouncedAt,
		&i.CancelledAt,
		&i.Replaces,
		&i.ProposedFor,
	)
	return i, err
}
