// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: infra.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getInstanceTarget = `-- name: GetInstanceTarget :one
SELECT i.id, i.kind, i.port, i.admin_host, i.admin_port,
       n.id AS node_id, n.name AS node_name, n.private_addr, n.pg_admin_secret
FROM instances i JOIN nodes n ON n.id = i.node_id
WHERE i.id = $1
`

type GetInstanceTargetRow struct {
	ID            uuid.UUID
	Kind          string
	Port          int32
	AdminHost     *string
	AdminPort     *int32
	NodeID        uuid.UUID
	NodeName      string
	PrivateAddr   string
	PgAdminSecret []byte
}

func (q *Queries) GetInstanceTarget(ctx context.Context, id uuid.UUID) (GetInstanceTargetRow, error) {
	row := q.db.QueryRow(ctx, getInstanceTarget, id)
	var i GetInstanceTargetRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Port,
		&i.AdminHost,
		&i.AdminPort,
		&i.NodeID,
		&i.NodeName,
		&i.PrivateAddr,
		&i.PgAdminSecret,
	)
	return i, err
}

const pickSharedInstance = `-- name: PickSharedInstance :one
SELECT i.id, i.node_id, i.kind, i.pg_version, i.port, i.container_id, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.status, i.created_at, i.admin_host, i.admin_port FROM instances i
JOIN nodes n ON n.id = i.node_id
WHERE i.kind = 'shared' AND i.status = 'running' AND n.status = 'healthy'
ORDER BY (SELECT count(*) FROM projects p WHERE p.instance_id = i.id AND p.deleted_at IS NULL), i.created_at
LIMIT 1
`

// PickSharedInstance chooses the running shared instance hosting the fewest
// live projects.
func (q *Queries) PickSharedInstance(ctx context.Context) (Instance, error) {
	row := q.db.QueryRow(ctx, pickSharedInstance)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
	)
	return i, err
}

const setNodeAdminSecret = `-- name: SetNodeAdminSecret :exec
UPDATE nodes SET pg_admin_secret = $1 WHERE id = $2
`

type SetNodeAdminSecretParams struct {
	PgAdminSecret []byte
	ID            uuid.UUID
}

func (q *Queries) SetNodeAdminSecret(ctx context.Context, arg SetNodeAdminSecretParams) error {
	_, err := q.db.Exec(ctx, setNodeAdminSecret, arg.PgAdminSecret, arg.ID)
	return err
}

const upsertNode = `-- name: UpsertNode :one
INSERT INTO nodes (name, private_addr, role, pg_admin_secret, capacity)
VALUES ($1, $2, $3, $4, '{}')
ON CONFLICT (name) DO UPDATE
SET private_addr = EXCLUDED.private_addr, role = EXCLUDED.role, pg_admin_secret = EXCLUDED.pg_admin_secret
RETURNING id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at
`

type UpsertNodeParams struct {
	Name          string
	PrivateAddr   string
	Role          string
	PgAdminSecret []byte
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.Name,
		arg.PrivateAddr,
		arg.Role,
		arg.PgAdminSecret,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSharedInstance = `-- name: UpsertSharedInstance :one
INSERT INTO instances (node_id, kind, pg_version, port, admin_host, admin_port, status)
VALUES ($1, 'shared', $2, $3, $4, $5, 'running')
ON CONFLICT (node_id) WHERE kind = 'shared' DO UPDATE
SET pg_version = EXCLUDED.pg_version, port = EXCLUDED.port,
    admin_host = EXCLUDED.admin_host, admin_port = EXCLUDED.admin_port, status = 'running'
RETURNING id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port
`

type UpsertSharedInstanceParams struct {
	NodeID    uuid.UUID
	PgVersion int32
	Port      int32
	AdminHost *string
	AdminPort *int32
}

func (q *Queries) UpsertSharedInstance(ctx context.Context, arg UpsertSharedInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, upsertSharedInstance,
		arg.NodeID,
		arg.PgVersion,
		arg.Port,
		arg.AdminHost,
		arg.AdminPort,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
	)
	return i, err
}
