// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: infra.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInstance = `-- name: GetInstance :one
SELECT id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port, host, admin_secret, profile, walg_prefix, error, deleted_at, org_id, walg_target_id, walg_key_id, pg_release, pg_release_available, release_checked_at, ha_enabled, sync_replication, patroni, leader_member, patroni_secret FROM instances WHERE id = $1
`

func (q *Queries) GetInstance(ctx context.Context, id uuid.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
		&i.Host,
		&i.AdminSecret,
		&i.Profile,
		&i.WalgPrefix,
		&i.Error,
		&i.DeletedAt,
		&i.OrgID,
		&i.WalgTargetID,
		&i.WalgKeyID,
		&i.PgRelease,
		&i.PgReleaseAvailable,
		&i.ReleaseCheckedAt,
		&i.HaEnabled,
		&i.SyncReplication,
		&i.Patroni,
		&i.LeaderMember,
		&i.PatroniSecret,
	)
	return i, err
}

const getInstanceTarget = `-- name: GetInstanceTarget :one
SELECT i.id, i.kind, i.port, i.admin_host, i.admin_port, i.status,
       COALESCE(i.host, n.private_addr)::text AS host, i.admin_secret,
       n.id AS node_id, n.name AS node_name, n.private_addr, n.pg_admin_secret
FROM instances i JOIN nodes n ON n.id = i.node_id
WHERE i.id = $1
`

type GetInstanceTargetRow struct {
	ID            uuid.UUID
	Kind          string
	Port          int32
	AdminHost     *string
	AdminPort     *int32
	Status        string
	Host          string
	AdminSecret   []byte
	NodeID        uuid.UUID
	NodeName      string
	PrivateAddr   string
	PgAdminSecret []byte
}

// GetInstanceTarget is how to reach an instance: host (poolers, agents)
// defaults to the node's private address; the admin credential is the
// instance's own (dedicated) or the node's (registered shared cluster).
func (q *Queries) GetInstanceTarget(ctx context.Context, id uuid.UUID) (GetInstanceTargetRow, error) {
	row := q.db.QueryRow(ctx, getInstanceTarget, id)
	var i GetInstanceTargetRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Port,
		&i.AdminHost,
		&i.AdminPort,
		&i.Status,
		&i.Host,
		&i.AdminSecret,
		&i.NodeID,
		&i.NodeName,
		&i.PrivateAddr,
		&i.PgAdminSecret,
	)
	return i, err
}

const insertInstance = `-- name: InsertInstance :one
INSERT INTO instances (id, node_id, kind, pg_version, port, cpu_limit, mem_limit_mb, volume_gb, profile, walg_prefix, status)
VALUES ($1, $2, $3, $4, 5432, $5, $6, $7, $8, $9, 'provisioning')
RETURNING id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port, host, admin_secret, profile, walg_prefix, error, deleted_at, org_id, walg_target_id, walg_key_id, pg_release, pg_release_available, release_checked_at, ha_enabled, sync_replication, patroni, leader_member, patroni_secret
`

type InsertInstanceParams struct {
	ID         uuid.UUID
	NodeID     uuid.UUID
	Kind       string
	PgVersion  int32
	CpuLimit   pgtype.Numeric
	MemLimitMb *int32
	VolumeGb   *int32
	Profile    *string
	WalgPrefix *string
}

func (q *Queries) InsertInstance(ctx context.Context, arg InsertInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, insertInstance,
		arg.ID,
		arg.NodeID,
		arg.Kind,
		arg.PgVersion,
		arg.CpuLimit,
		arg.MemLimitMb,
		arg.VolumeGb,
		arg.Profile,
		arg.WalgPrefix,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
		&i.Host,
		&i.AdminSecret,
		&i.Profile,
		&i.WalgPrefix,
		&i.Error,
		&i.DeletedAt,
		&i.OrgID,
		&i.WalgTargetID,
		&i.WalgKeyID,
		&i.PgRelease,
		&i.PgReleaseAvailable,
		&i.ReleaseCheckedAt,
		&i.HaEnabled,
		&i.SyncReplication,
		&i.Patroni,
		&i.LeaderMember,
		&i.PatroniSecret,
	)
	return i, err
}

const listInstanceSummaries = `-- name: ListInstanceSummaries :many
SELECT i.id, i.kind, i.profile, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.status, i.error, i.pg_version,
       i.pg_release, i.pg_release_available, i.ha_enabled,
       n.id AS node_id, n.name AS node_name
FROM instances i JOIN nodes n ON n.id = i.node_id
WHERE i.deleted_at IS NULL
`

type ListInstanceSummariesRow struct {
	ID                 uuid.UUID
	Kind               string
	Profile            *string
	CpuLimit           pgtype.Numeric
	MemLimitMb         *int32
	VolumeGb           *int32
	Status             string
	Error              *string
	PgVersion          int32
	PgRelease          *string
	PgReleaseAvailable *string
	HaEnabled          bool
	NodeID             uuid.UUID
	NodeName           string
}

func (q *Queries) ListInstanceSummaries(ctx context.Context) ([]ListInstanceSummariesRow, error) {
	rows, err := q.db.Query(ctx, listInstanceSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstanceSummariesRow
	for rows.Next() {
		var i ListInstanceSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Profile,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.Status,
			&i.Error,
			&i.PgVersion,
			&i.PgRelease,
			&i.PgReleaseAvailable,
			&i.HaEnabled,
			&i.NodeID,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstances = `-- name: ListNodeInstances :many
SELECT i.id, i.node_id, i.kind, i.pg_version, i.port, i.container_id, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.status, i.created_at, i.admin_host, i.admin_port, i.host, i.admin_secret, i.profile, i.walg_prefix, i.error, i.deleted_at, i.org_id, i.walg_target_id, i.walg_key_id, i.pg_release, i.pg_release_available, i.release_checked_at, i.ha_enabled, i.sync_replication, i.patroni, i.leader_member, i.patroni_secret, (SELECT count(*) FROM projects p WHERE p.instance_id = i.id AND p.deleted_at IS NULL)::int AS projects
FROM instances i
WHERE i.node_id = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at
`

type ListNodeInstancesRow struct {
	ID                 uuid.UUID
	NodeID             uuid.UUID
	Kind               string
	PgVersion          int32
	Port               int32
	ContainerID        *string
	CpuLimit           pgtype.Numeric
	MemLimitMb         *int32
	VolumeGb           *int32
	Status             string
	CreatedAt          time.Time
	AdminHost          *string
	AdminPort          *int32
	Host               *string
	AdminSecret        []byte
	Profile            *string
	WalgPrefix         *string
	Error              *string
	DeletedAt          *time.Time
	OrgID              *uuid.UUID
	WalgTargetID       *uuid.UUID
	WalgKeyID          *uuid.UUID
	PgRelease          *string
	PgReleaseAvailable *string
	ReleaseCheckedAt   *time.Time
	HaEnabled          bool
	SyncReplication    bool
	Patroni            bool
	LeaderMember       *uuid.UUID
	PatroniSecret      []byte
	Projects           int32
}

// tenant: system - platform infrastructure (nodes, instances, placement).
func (q *Queries) ListNodeInstances(ctx context.Context, nodeID uuid.UUID) ([]ListNodeInstancesRow, error) {
	rows, err := q.db.Query(ctx, listNodeInstances, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeInstancesRow
	for rows.Next() {
		var i ListNodeInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.PgVersion,
			&i.Port,
			&i.ContainerID,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.Status,
			&i.CreatedAt,
			&i.AdminHost,
			&i.AdminPort,
			&i.Host,
			&i.AdminSecret,
			&i.Profile,
			&i.WalgPrefix,
			&i.Error,
			&i.DeletedAt,
			&i.OrgID,
			&i.WalgTargetID,
			&i.WalgKeyID,
			&i.PgRelease,
			&i.PgReleaseAvailable,
			&i.ReleaseCheckedAt,
			&i.HaEnabled,
			&i.SyncReplication,
			&i.Patroni,
			&i.LeaderMember,
			&i.PatroniSecret,
			&i.Projects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedInstances = `-- name: ListOrphanedInstances :many
SELECT i.id, i.node_id, i.kind, i.pg_version, i.port, i.container_id, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.status, i.created_at, i.admin_host, i.admin_port, i.host, i.admin_secret, i.profile, i.walg_prefix, i.error, i.deleted_at, i.org_id, i.walg_target_id, i.walg_key_id, i.pg_release, i.pg_release_available, i.release_checked_at, i.ha_enabled, i.sync_replication, i.patroni, i.leader_member, i.patroni_secret FROM instances i
WHERE i.deleted_at IS NULL
  AND i.created_at < now() - interval '5 minutes'
  AND NOT EXISTS (SELECT 1 FROM projects p WHERE p.instance_id = i.id AND p.deleted_at IS NULL)
  -- A demoted project's stopped instance, kept as a rollback option.
  AND NOT EXISTS (SELECT 1 FROM retired_databases r WHERE r.instance_id = i.id AND r.dropped_at IS NULL)
  AND (i.kind = 'dedicated' OR (i.kind = 'shared' AND i.status = 'error'))
ORDER BY i.created_at
`

// ListOrphanedInstances finds instances nothing uses and nothing will finish
// setting up: dedicated instances no live project points at, and shared
// clusters whose failed creation could not be rolled back (status 'error',
// see rollbackSharedCluster). Both are what a rollback leaves when it could
// not reach the node. The grace period keeps it clear of instances a create
// or restore is still setting up.
// tenant: system - platform infrastructure (nodes, instances, placement).
func (q *Queries) ListOrphanedInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listOrphanedInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.PgVersion,
			&i.Port,
			&i.ContainerID,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.Status,
			&i.CreatedAt,
			&i.AdminHost,
			&i.AdminPort,
			&i.Host,
			&i.AdminSecret,
			&i.Profile,
			&i.WalgPrefix,
			&i.Error,
			&i.DeletedAt,
			&i.OrgID,
			&i.WalgTargetID,
			&i.WalgKeyID,
			&i.PgRelease,
			&i.PgReleaseAvailable,
			&i.ReleaseCheckedAt,
			&i.HaEnabled,
			&i.SyncReplication,
			&i.Patroni,
			&i.LeaderMember,
			&i.PatroniSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstanceDeleted = `-- name: MarkInstanceDeleted :exec
UPDATE instances SET status = 'deleted', deleted_at = now() WHERE id = $1
`

func (q *Queries) MarkInstanceDeleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInstanceDeleted, id)
	return err
}

const orgSharedInstances = `-- name: OrgSharedInstances :many
SELECT i.id, i.node_id, i.kind, i.pg_version, i.port, i.container_id, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.status, i.created_at, i.admin_host, i.admin_port, i.host, i.admin_secret, i.profile, i.walg_prefix, i.error, i.deleted_at, i.org_id, i.walg_target_id, i.walg_key_id, i.pg_release, i.pg_release_available, i.release_checked_at, i.ha_enabled, i.sync_replication, i.patroni, i.leader_member, i.patroni_secret, n.name AS node_name FROM instances i JOIN nodes n ON n.id = i.node_id
WHERE i.kind = 'shared' AND i.deleted_at IS NULL AND i.org_id = $1
`

type OrgSharedInstancesRow struct {
	ID                 uuid.UUID
	NodeID             uuid.UUID
	Kind               string
	PgVersion          int32
	Port               int32
	ContainerID        *string
	CpuLimit           pgtype.Numeric
	MemLimitMb         *int32
	VolumeGb           *int32
	Status             string
	CreatedAt          time.Time
	AdminHost          *string
	AdminPort          *int32
	Host               *string
	AdminSecret        []byte
	Profile            *string
	WalgPrefix         *string
	Error              *string
	DeletedAt          *time.Time
	OrgID              *uuid.UUID
	WalgTargetID       *uuid.UUID
	WalgKeyID          *uuid.UUID
	PgRelease          *string
	PgReleaseAvailable *string
	ReleaseCheckedAt   *time.Time
	HaEnabled          bool
	SyncReplication    bool
	Patroni            bool
	LeaderMember       *uuid.UUID
	PatroniSecret      []byte
	NodeName           string
}

// tenant: system - the shared clusters tagged with one organisation.
func (q *Queries) OrgSharedInstances(ctx context.Context, orgID *uuid.UUID) ([]OrgSharedInstancesRow, error) {
	rows, err := q.db.Query(ctx, orgSharedInstances, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgSharedInstancesRow
	for rows.Next() {
		var i OrgSharedInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.PgVersion,
			&i.Port,
			&i.ContainerID,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.Status,
			&i.CreatedAt,
			&i.AdminHost,
			&i.AdminPort,
			&i.Host,
			&i.AdminSecret,
			&i.Profile,
			&i.WalgPrefix,
			&i.Error,
			&i.DeletedAt,
			&i.OrgID,
			&i.WalgTargetID,
			&i.WalgKeyID,
			&i.PgRelease,
			&i.PgReleaseAvailable,
			&i.ReleaseCheckedAt,
			&i.HaEnabled,
			&i.SyncReplication,
			&i.Patroni,
			&i.LeaderMember,
			&i.PatroniSecret,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickDedicatedNode = `-- name: PickDedicatedNode :one
SELECT n.id, n.name, n.private_addr, n.agent_port, n.role, n.agent_cert_fp, n.pg_admin_secret, n.capacity, n.status, n.last_heartbeat, n.created_at, n.agent_host, n.agent_version, n.registration_token, n.registration_expires_at, n.last_reachable_at, n.provider_server_id, n.pooler_generation, n.pooler_hash, n.pooler_vrrp_state, n.pooler_ready, n.pooler_checked_at, n.provider, n.region, n.server_type, n.monthly_cost_minor, n.cost_currency, n.lifecycle, n.empty_since, n.keep, n.failure_domain, n.placement_group FROM nodes n
WHERE n.role IN ('dedicated', 'both') AND n.status = 'healthy' AND n.lifecycle = 'active' AND n.agent_cert_fp IS NOT NULL
  AND n.region = $1
ORDER BY (SELECT count(*) FROM instances i WHERE i.node_id = n.id AND i.kind = 'dedicated' AND i.deleted_at IS NULL), n.created_at
LIMIT 1
`

// PickDedicatedNode chooses the healthy node with an agent that allows
// dedicated instances and runs the fewest.
func (q *Queries) PickDedicatedNode(ctx context.Context, region string) (Node, error) {
	row := q.db.QueryRow(ctx, pickDedicatedNode, region)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
		&i.LastReachableAt,
		&i.ProviderServerID,
		&i.PoolerGeneration,
		&i.PoolerHash,
		&i.PoolerVrrpState,
		&i.PoolerReady,
		&i.PoolerCheckedAt,
		&i.Provider,
		&i.Region,
		&i.ServerType,
		&i.MonthlyCostMinor,
		&i.CostCurrency,
		&i.Lifecycle,
		&i.EmptySince,
		&i.Keep,
		&i.FailureDomain,
		&i.PlacementGroup,
	)
	return i, err
}

const pickSharedInstance = `-- name: PickSharedInstance :one
SELECT i.id, i.node_id, i.kind, i.pg_version, i.port, i.container_id, i.cpu_limit, i.mem_limit_mb, i.volume_gb, i.status, i.created_at, i.admin_host, i.admin_port, i.host, i.admin_secret, i.profile, i.walg_prefix, i.error, i.deleted_at, i.org_id, i.walg_target_id, i.walg_key_id, i.pg_release, i.pg_release_available, i.release_checked_at, i.ha_enabled, i.sync_replication, i.patroni, i.leader_member, i.patroni_secret FROM instances i
JOIN nodes n ON n.id = i.node_id
WHERE i.kind = 'shared' AND i.status = 'running' AND n.status = 'healthy' AND n.lifecycle = 'active' AND n.role IN ('shared', 'both')
  AND i.deleted_at IS NULL AND i.pg_version = $1 AND n.region = $2
  AND CASE WHEN EXISTS (SELECT 1 FROM instances x WHERE x.kind = 'shared' AND x.deleted_at IS NULL AND x.org_id = $3)
           THEN i.org_id = $3 ELSE i.org_id IS NULL END
ORDER BY (SELECT count(*) FROM projects p WHERE p.instance_id = i.id AND p.deleted_at IS NULL), i.created_at
LIMIT 1
`

type PickSharedInstanceParams struct {
	PgVersion int32
	Region    string
	OrgID     *uuid.UUID
}

// PickSharedInstance chooses the running shared instance hosting the fewest
// live projects.
// tenant: system - platform infrastructure (nodes, instances, placement).
// An organisation with its own shared clusters uses only those; every
// other organisation uses only the untagged ones (V2 s10.5).
func (q *Queries) PickSharedInstance(ctx context.Context, arg PickSharedInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, pickSharedInstance, arg.PgVersion, arg.Region, arg.OrgID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
		&i.Host,
		&i.AdminSecret,
		&i.Profile,
		&i.WalgPrefix,
		&i.Error,
		&i.DeletedAt,
		&i.OrgID,
		&i.WalgTargetID,
		&i.WalgKeyID,
		&i.PgRelease,
		&i.PgReleaseAvailable,
		&i.ReleaseCheckedAt,
		&i.HaEnabled,
		&i.SyncReplication,
		&i.Patroni,
		&i.LeaderMember,
		&i.PatroniSecret,
	)
	return i, err
}

const setInstanceAdminSecret = `-- name: SetInstanceAdminSecret :exec
UPDATE instances SET admin_secret = $1 WHERE id = $2
`

type SetInstanceAdminSecretParams struct {
	AdminSecret []byte
	ID          uuid.UUID
}

func (q *Queries) SetInstanceAdminSecret(ctx context.Context, arg SetInstanceAdminSecretParams) error {
	_, err := q.db.Exec(ctx, setInstanceAdminSecret, arg.AdminSecret, arg.ID)
	return err
}

const setInstanceOrg = `-- name: SetInstanceOrg :execrows
UPDATE instances SET org_id = $1 WHERE id = $2 AND kind = 'shared' AND deleted_at IS NULL
`

type SetInstanceOrgParams struct {
	OrgID *uuid.UUID
	ID    uuid.UUID
}

// tenant: system - the platform admin assigns a shared cluster to one organisation.
func (q *Queries) SetInstanceOrg(ctx context.Context, arg SetInstanceOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstanceOrg, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstanceRunning = `-- name: SetInstanceRunning :exec
UPDATE instances
SET status = 'running', container_id = $1, host = $2, port = $3,
    admin_host = $4, admin_port = $5, error = NULL
WHERE id = $6
`

type SetInstanceRunningParams struct {
	ContainerID *string
	Host        *string
	Port        int32
	AdminHost   *string
	AdminPort   *int32
	ID          uuid.UUID
}

func (q *Queries) SetInstanceRunning(ctx context.Context, arg SetInstanceRunningParams) error {
	_, err := q.db.Exec(ctx, setInstanceRunning,
		arg.ContainerID,
		arg.Host,
		arg.Port,
		arg.AdminHost,
		arg.AdminPort,
		arg.ID,
	)
	return err
}

const setInstanceStatus = `-- name: SetInstanceStatus :exec
UPDATE instances SET status = $1, error = $2 WHERE id = $3
`

type SetInstanceStatusParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) SetInstanceStatus(ctx context.Context, arg SetInstanceStatusParams) error {
	_, err := q.db.Exec(ctx, setInstanceStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const setNodeAdminSecret = `-- name: SetNodeAdminSecret :exec
UPDATE nodes SET pg_admin_secret = $1 WHERE id = $2
`

type SetNodeAdminSecretParams struct {
	PgAdminSecret []byte
	ID            uuid.UUID
}

func (q *Queries) SetNodeAdminSecret(ctx context.Context, arg SetNodeAdminSecretParams) error {
	_, err := q.db.Exec(ctx, setNodeAdminSecret, arg.PgAdminSecret, arg.ID)
	return err
}

const sharedInstanceForeignProjects = `-- name: SharedInstanceForeignProjects :one
SELECT count(*)::int FROM projects p WHERE p.instance_id = $1 AND p.deleted_at IS NULL AND p.org_id <> $2
`

type SharedInstanceForeignProjectsParams struct {
	InstanceID uuid.UUID
	OrgID      uuid.UUID
}

// tenant: system - projects of other organisations already on a shared cluster.
func (q *Queries) SharedInstanceForeignProjects(ctx context.Context, arg SharedInstanceForeignProjectsParams) (int32, error) {
	row := q.db.QueryRow(ctx, sharedInstanceForeignProjects, arg.InstanceID, arg.OrgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const sharedInstanceOnNode = `-- name: SharedInstanceOnNode :one
SELECT id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port, host, admin_secret, profile, walg_prefix, error, deleted_at, org_id, walg_target_id, walg_key_id, pg_release, pg_release_available, release_checked_at, ha_enabled, sync_replication, patroni, leader_member, patroni_secret FROM instances WHERE node_id = $1 AND kind = 'shared' AND deleted_at IS NULL
`

func (q *Queries) SharedInstanceOnNode(ctx context.Context, nodeID uuid.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, sharedInstanceOnNode, nodeID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
		&i.Host,
		&i.AdminSecret,
		&i.Profile,
		&i.WalgPrefix,
		&i.Error,
		&i.DeletedAt,
		&i.OrgID,
		&i.WalgTargetID,
		&i.WalgKeyID,
		&i.PgRelease,
		&i.PgReleaseAvailable,
		&i.ReleaseCheckedAt,
		&i.HaEnabled,
		&i.SyncReplication,
		&i.Patroni,
		&i.LeaderMember,
		&i.PatroniSecret,
	)
	return i, err
}

const upsertNode = `-- name: UpsertNode :one
INSERT INTO nodes (name, private_addr, role, pg_admin_secret, capacity)
VALUES ($1, $2, $3, $4, '{}')
ON CONFLICT (name) DO UPDATE
SET private_addr = EXCLUDED.private_addr, pg_admin_secret = EXCLUDED.pg_admin_secret
RETURNING id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at, last_reachable_at, provider_server_id, pooler_generation, pooler_hash, pooler_vrrp_state, pooler_ready, pooler_checked_at, provider, region, server_type, monthly_cost_minor, cost_currency, lifecycle, empty_since, keep, failure_domain, placement_group
`

type UpsertNodeParams struct {
	Name          string
	PrivateAddr   string
	Role          string
	PgAdminSecret []byte
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.Name,
		arg.PrivateAddr,
		arg.Role,
		arg.PgAdminSecret,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
		&i.LastReachableAt,
		&i.ProviderServerID,
		&i.PoolerGeneration,
		&i.PoolerHash,
		&i.PoolerVrrpState,
		&i.PoolerReady,
		&i.PoolerCheckedAt,
		&i.Provider,
		&i.Region,
		&i.ServerType,
		&i.MonthlyCostMinor,
		&i.CostCurrency,
		&i.Lifecycle,
		&i.EmptySince,
		&i.Keep,
		&i.FailureDomain,
		&i.PlacementGroup,
	)
	return i, err
}

const upsertSharedInstance = `-- name: UpsertSharedInstance :one
INSERT INTO instances (node_id, kind, pg_version, port, admin_host, admin_port, status)
VALUES ($1, 'shared', $2, $3, $4, $5, 'running')
ON CONFLICT (node_id) WHERE kind = 'shared' AND deleted_at IS NULL DO UPDATE
SET pg_version = EXCLUDED.pg_version, port = EXCLUDED.port,
    admin_host = EXCLUDED.admin_host, admin_port = EXCLUDED.admin_port, status = 'running'
RETURNING id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port, host, admin_secret, profile, walg_prefix, error, deleted_at, org_id, walg_target_id, walg_key_id, pg_release, pg_release_available, release_checked_at, ha_enabled, sync_replication, patroni, leader_member, patroni_secret
`

type UpsertSharedInstanceParams struct {
	NodeID    uuid.UUID
	PgVersion int32
	Port      int32
	AdminHost *string
	AdminPort *int32
}

func (q *Queries) UpsertSharedInstance(ctx context.Context, arg UpsertSharedInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, upsertSharedInstance,
		arg.NodeID,
		arg.PgVersion,
		arg.Port,
		arg.AdminHost,
		arg.AdminPort,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.PgVersion,
		&i.Port,
		&i.ContainerID,
		&i.CpuLimit,
		&i.MemLimitMb,
		&i.VolumeGb,
		&i.Status,
		&i.CreatedAt,
		&i.AdminHost,
		&i.AdminPort,
		&i.Host,
		&i.AdminSecret,
		&i.Profile,
		&i.WalgPrefix,
		&i.Error,
		&i.DeletedAt,
		&i.OrgID,
		&i.WalgTargetID,
		&i.WalgKeyID,
		&i.PgRelease,
		&i.PgReleaseAvailable,
		&i.ReleaseCheckedAt,
		&i.HaEnabled,
		&i.SyncReplication,
		&i.Patroni,
		&i.LeaderMember,
		&i.PatroniSecret,
	)
	return i, err
}
