// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insights.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteQuerySnapshots = `-- name: DeleteQuerySnapshots :exec
DELETE FROM query_snapshots WHERE instance_id = $1
`

// tenant: system - the query insights collector.
func (q *Queries) DeleteQuerySnapshots(ctx context.Context, instanceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuerySnapshots, instanceID)
	return err
}

const getQueryText = `-- name: GetQueryText :one
SELECT project_id, queryid, query, example, example_at, first_seen, last_seen FROM query_texts WHERE project_id = $1 AND queryid = $2
`

type GetQueryTextParams struct {
	ProjectID uuid.UUID
	Queryid   int64
}

// tenant: system - a project the request already authorized.
func (q *Queries) GetQueryText(ctx context.Context, arg GetQueryTextParams) (QueryText, error) {
	row := q.db.QueryRow(ctx, getQueryText, arg.ProjectID, arg.Queryid)
	var i QueryText
	err := row.Scan(
		&i.ProjectID,
		&i.Queryid,
		&i.Query,
		&i.Example,
		&i.ExampleAt,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

type InsertQuerySnapshotsParams struct {
	InstanceID     uuid.UUID
	Dbid           int64
	Userid         int64
	Queryid        int64
	Toplevel       bool
	Calls          int64
	TotalMs        float64
	Rows           int64
	SharedBlksHit  int64
	SharedBlksRead int64
	MaxMs          float64
	TakenAt        time.Time
}

const insertSlowQuery = `-- name: InsertSlowQuery :exec
INSERT INTO slow_queries (project_id, queryid, query, duration_ms, source, role_name)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSlowQueryParams struct {
	ProjectID  uuid.UUID
	Queryid    *int64
	Query      string
	DurationMs float64
	Source     string
	RoleName   string
}

// tenant: system - the query insights collector logs a slow statement.
func (q *Queries) InsertSlowQuery(ctx context.Context, arg InsertSlowQueryParams) error {
	_, err := q.db.Exec(ctx, insertSlowQuery,
		arg.ProjectID,
		arg.Queryid,
		arg.Query,
		arg.DurationMs,
		arg.Source,
		arg.RoleName,
	)
	return err
}

const insightsProjects = `-- name: InsightsProjects :many

SELECT p.id, p.org_id, p.instance_id, p.db_name, p.tier, COALESCE(b.plan, 'free')::text AS plan
FROM projects p
LEFT JOIN billing_accounts b ON b.org_id = p.org_id
WHERE p.deleted_at IS NULL AND p.status = 'active' AND p.lifecycle = 'active'
ORDER BY p.instance_id, p.db_name
`

type InsightsProjectsRow struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	InstanceID uuid.UUID
	DbName     string
	Tier       string
	Plan       string
}

// Query insights (V3 §8).
// tenant: system - the query insights collector, across organisations.
// Live projects with their instance and their organisation's plan.
func (q *Queries) InsightsProjects(ctx context.Context) ([]InsightsProjectsRow, error) {
	rows, err := q.db.Query(ctx, insightsProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsightsProjectsRow
	for rows.Next() {
		var i InsightsProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.InstanceID,
			&i.DbName,
			&i.Tier,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuerySnapshots = `-- name: ListQuerySnapshots :many
SELECT instance_id, dbid, userid, queryid, toplevel, calls, total_ms, rows, shared_blks_hit, shared_blks_read, max_ms, taken_at FROM query_snapshots WHERE instance_id = $1
`

// tenant: system - the query insights collector.
func (q *Queries) ListQuerySnapshots(ctx context.Context, instanceID uuid.UUID) ([]QuerySnapshot, error) {
	rows, err := q.db.Query(ctx, listQuerySnapshots, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySnapshot
	for rows.Next() {
		var i QuerySnapshot
		if err := rows.Scan(
			&i.InstanceID,
			&i.Dbid,
			&i.Userid,
			&i.Queryid,
			&i.Toplevel,
			&i.Calls,
			&i.TotalMs,
			&i.Rows,
			&i.SharedBlksHit,
			&i.SharedBlksRead,
			&i.MaxMs,
			&i.TakenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlowQueries = `-- name: ListSlowQueries :many
SELECT queryid, query, duration_ms, source, role_name, seen_at FROM (
  SELECT q.queryid, q.query, q.duration_ms, q.source, q.role_name, q.seen_at FROM slow_queries q
  WHERE q.project_id = $1 AND q.seen_at >= $2
  UNION ALL
  SELECT NULL::bigint, COALESCE(r.query, ''), (r.duration_s * 1000)::float8, 'reaper', r.role_name, r.created_at FROM reaped_sessions r
  WHERE r.project_id = $1 AND r.kind = 'statement' AND r.created_at >= $2
) s ORDER BY seen_at DESC LIMIT $3
`

type ListSlowQueriesParams struct {
	ProjectID uuid.UUID
	Since     time.Time
	Lim       int32
}

type ListSlowQueriesRow struct {
	Queryid    *int64
	Query      string
	DurationMs float64
	Source     string
	RoleName   string
	SeenAt     time.Time
}

// tenant: system - a project the request already authorized. With the reaper's cancellations.
func (q *Queries) ListSlowQueries(ctx context.Context, arg ListSlowQueriesParams) ([]ListSlowQueriesRow, error) {
	rows, err := q.db.Query(ctx, listSlowQueries, arg.ProjectID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlowQueriesRow
	for rows.Next() {
		var i ListSlowQueriesRow
		if err := rows.Scan(
			&i.Queryid,
			&i.Query,
			&i.DurationMs,
			&i.Source,
			&i.RoleName,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectPlan = `-- name: ProjectPlan :one
SELECT COALESCE((SELECT b.plan FROM billing_accounts b WHERE b.org_id = $1), 'free')::text
`

// tenant: system - a project the request already authorized.
func (q *Queries) ProjectPlan(ctx context.Context, orgID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, projectPlan, orgID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneQueryInsights = `-- name: PruneQueryInsights :exec
WITH a AS (DELETE FROM query_stats WHERE bucket < $1),
     b AS (DELETE FROM slow_queries WHERE seen_at < $1)
DELETE FROM query_texts t WHERE t.last_seen < $1
`

// tenant: system - the query insights collector keeps 30 days.
func (q *Queries) PruneQueryInsights(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, pruneQueryInsights, before)
	return err
}

const querySeries = `-- name: QuerySeries :many
SELECT date_bin($1::interval, bucket, '2000-01-01'::timestamptz)::timestamptz AS ts,
  sum(calls)::bigint AS calls, sum(total_ms)::float8 AS total_ms, sum(rows)::bigint AS rows, max(max_ms)::float8 AS max_ms
FROM query_stats WHERE project_id = $2 AND queryid = $3 AND bucket >= $4
GROUP BY 1 ORDER BY 1
`

type QuerySeriesParams struct {
	Step      pgtype.Interval
	ProjectID uuid.UUID
	Queryid   int64
	Since     time.Time
}

type QuerySeriesRow struct {
	Ts      time.Time
	Calls   int64
	TotalMs float64
	Rows    int64
	MaxMs   float64
}

// tenant: system - a project the request already authorized.
func (q *Queries) QuerySeries(ctx context.Context, arg QuerySeriesParams) ([]QuerySeriesRow, error) {
	rows, err := q.db.Query(ctx, querySeries,
		arg.Step,
		arg.ProjectID,
		arg.Queryid,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySeriesRow
	for rows.Next() {
		var i QuerySeriesRow
		if err := rows.Scan(
			&i.Ts,
			&i.Calls,
			&i.TotalMs,
			&i.Rows,
			&i.MaxMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTotals = `-- name: QueryTotals :one
SELECT COALESCE(sum(calls), 0)::bigint AS calls, COALESCE(sum(total_ms), 0)::float8 AS total_ms
FROM query_stats WHERE project_id = $1 AND bucket >= $2
`

type QueryTotalsParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

type QueryTotalsRow struct {
	Calls   int64
	TotalMs float64
}

// tenant: system - a project the request already authorized.
func (q *Queries) QueryTotals(ctx context.Context, arg QueryTotalsParams) (QueryTotalsRow, error) {
	row := q.db.QueryRow(ctx, queryTotals, arg.ProjectID, arg.Since)
	var i QueryTotalsRow
	err := row.Scan(&i.Calls, &i.TotalMs)
	return i, err
}

const recentSlowQuery = `-- name: RecentSlowQuery :one
SELECT EXISTS (SELECT 1 FROM slow_queries WHERE project_id = $1 AND query = $2 AND source = 'running'
  AND seen_at > now() - interval '10 minutes')::bool
`

type RecentSlowQueryParams struct {
	ProjectID uuid.UUID
	Query     string
}

// tenant: system - the collector doesn't log one running statement twice.
func (q *Queries) RecentSlowQuery(ctx context.Context, arg RecentSlowQueryParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentSlowQuery, arg.ProjectID, arg.Query)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const rollUpQueryStats = `-- name: RollUpQueryStats :exec
WITH old AS (
  DELETE FROM query_stats d WHERE d.bucket < $1 AND d.bucket <> date_trunc('hour', d.bucket) RETURNING d.project_id, d.queryid, d.bucket, d.calls, d.total_ms, d.rows, d.shared_blks_hit, d.shared_blks_read, d.max_ms
)
INSERT INTO query_stats (project_id, queryid, bucket, calls, total_ms, rows, shared_blks_hit, shared_blks_read, max_ms)
SELECT project_id, queryid, date_trunc('hour', bucket), sum(calls), sum(total_ms), sum(rows), sum(shared_blks_hit), sum(shared_blks_read), max(max_ms)
FROM old GROUP BY 1, 2, 3
ON CONFLICT (project_id, queryid, bucket) DO UPDATE SET
  calls = query_stats.calls + EXCLUDED.calls, total_ms = query_stats.total_ms + EXCLUDED.total_ms,
  rows = query_stats.rows + EXCLUDED.rows, shared_blks_hit = query_stats.shared_blks_hit + EXCLUDED.shared_blks_hit,
  shared_blks_read = query_stats.shared_blks_read + EXCLUDED.shared_blks_read, max_ms = GREATEST(query_stats.max_ms, EXCLUDED.max_ms)
`

// tenant: system - the query insights collector folds 5-minute buckets older than a day into hours.
func (q *Queries) RollUpQueryStats(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, rollUpQueryStats, before)
	return err
}

const setQueryExample = `-- name: SetQueryExample :exec
UPDATE query_texts SET example = $1, example_at = now() WHERE project_id = $2 AND queryid = $3
`

type SetQueryExampleParams struct {
	Example   *string
	ProjectID uuid.UUID
	Queryid   int64
}

// tenant: system - the query insights collector keeps the latest example with literals.
func (q *Queries) SetQueryExample(ctx context.Context, arg SetQueryExampleParams) error {
	_, err := q.db.Exec(ctx, setQueryExample, arg.Example, arg.ProjectID, arg.Queryid)
	return err
}

const topQueries = `-- name: TopQueries :many
SELECT s.queryid, COALESCE(t.query, '')::text AS query, (t.example IS NOT NULL)::bool AS has_example,
  sum(s.calls)::bigint AS calls, sum(s.total_ms)::float8 AS total_ms, sum(s.rows)::bigint AS rows,
  COALESCE(sum(s.total_ms) / NULLIF(sum(s.calls), 0), 0)::float8 AS mean_ms, max(s.max_ms)::float8 AS max_ms,
  COALESCE(sum(s.shared_blks_hit)::float8 / NULLIF(sum(s.shared_blks_hit) + sum(s.shared_blks_read), 0), 1)::float8 AS hit_ratio
FROM query_stats s
LEFT JOIN query_texts t ON t.project_id = s.project_id AND t.queryid = s.queryid
WHERE s.project_id = $1 AND s.bucket >= $2
GROUP BY s.queryid, t.query, t.example
HAVING sum(s.calls) > 0
ORDER BY CASE $3::text
  WHEN 'mean' THEN sum(s.total_ms) / NULLIF(sum(s.calls), 0)
  WHEN 'calls' THEN sum(s.calls)::float8
  WHEN 'rows' THEN sum(s.rows)::float8
  ELSE sum(s.total_ms) END DESC NULLS LAST, s.queryid
LIMIT $4
`

type TopQueriesParams struct {
	ProjectID uuid.UUID
	Since     time.Time
	Sort      string
	Lim       int32
}

type TopQueriesRow struct {
	Queryid    int64
	Query      string
	HasExample bool
	Calls      int64
	TotalMs    float64
	Rows       int64
	MeanMs     float64
	MaxMs      float64
	HitRatio   float64
}

// tenant: system - a project the request already authorized.
func (q *Queries) TopQueries(ctx context.Context, arg TopQueriesParams) ([]TopQueriesRow, error) {
	rows, err := q.db.Query(ctx, topQueries,
		arg.ProjectID,
		arg.Since,
		arg.Sort,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopQueriesRow
	for rows.Next() {
		var i TopQueriesRow
		if err := rows.Scan(
			&i.Queryid,
			&i.Query,
			&i.HasExample,
			&i.Calls,
			&i.TotalMs,
			&i.Rows,
			&i.MeanMs,
			&i.MaxMs,
			&i.HitRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
