// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const acceptLegalDocument = `-- name: AcceptLegalDocument :exec
INSERT INTO legal_acceptances (document_id, org_id, user_id, ip) VALUES ($1, $2, $3, $4)
ON CONFLICT (document_id, org_id) DO NOTHING
`

type AcceptLegalDocumentParams struct {
	DocumentID uuid.UUID
	OrgID      uuid.UUID
	UserID     *uuid.UUID
	Ip         *netip.Addr
}

func (q *Queries) AcceptLegalDocument(ctx context.Context, arg AcceptLegalDocumentParams) error {
	_, err := q.db.Exec(ctx, acceptLegalDocument,
		arg.DocumentID,
		arg.OrgID,
		arg.UserID,
		arg.Ip,
	)
	return err
}

const currentLegalDocument = `-- name: CurrentLegalDocument :one

SELECT id, kind, org_id, version, title, body_md, published_by, published_at FROM legal_documents WHERE kind = $1 AND org_id IS NULL ORDER BY version DESC LIMIT 1
`

// Legal documents (V3 §7.3).
// tenant: system - the platform-wide SLA or DPA in effect, public.
func (q *Queries) CurrentLegalDocument(ctx context.Context, kind string) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, currentLegalDocument, kind)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OrgID,
		&i.Version,
		&i.Title,
		&i.BodyMd,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const currentOrderForm = `-- name: CurrentOrderForm :one
SELECT id, kind, org_id, version, title, body_md, published_by, published_at FROM legal_documents WHERE kind = 'order_form' AND org_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) CurrentOrderForm(ctx context.Context, orgID *uuid.UUID) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, currentOrderForm, orgID)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OrgID,
		&i.Version,
		&i.Title,
		&i.BodyMd,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const getLegalDocument = `-- name: GetLegalDocument :one
SELECT id, kind, org_id, version, title, body_md, published_by, published_at FROM legal_documents WHERE id = $1
`

// tenant: system - a document the caller checks belongs to its org or is platform-wide.
func (q *Queries) GetLegalDocument(ctx context.Context, id uuid.UUID) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, getLegalDocument, id)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OrgID,
		&i.Version,
		&i.Title,
		&i.BodyMd,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const insertLegalDocument = `-- name: InsertLegalDocument :one
INSERT INTO legal_documents (kind, org_id, version, title, body_md, published_by)
VALUES ($1, $2, (SELECT coalesce(max(version), 0) + 1 FROM legal_documents
  WHERE kind = $1 AND org_id IS NOT DISTINCT FROM $2), $3, $4, $5)
RETURNING id, kind, org_id, version, title, body_md, published_by, published_at
`

type InsertLegalDocumentParams struct {
	Kind        string
	OrgID       *uuid.UUID
	Title       string
	BodyMd      string
	PublishedBy *uuid.UUID
}

// tenant: system - the platform admin publishes a version (an order form names its org).
func (q *Queries) InsertLegalDocument(ctx context.Context, arg InsertLegalDocumentParams) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, insertLegalDocument,
		arg.Kind,
		arg.OrgID,
		arg.Title,
		arg.BodyMd,
		arg.PublishedBy,
	)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OrgID,
		&i.Version,
		&i.Title,
		&i.BodyMd,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const legalAcceptances = `-- name: LegalAcceptances :many
SELECT a.document_id, a.org_id, a.user_id, a.accepted_at, a.ip, o.name AS org_name, u.email AS accepted_by FROM legal_acceptances a
JOIN organizations o ON o.id = a.org_id LEFT JOIN users u ON u.id = a.user_id
WHERE a.document_id = $1 ORDER BY a.accepted_at DESC
`

type LegalAcceptancesRow struct {
	DocumentID uuid.UUID
	OrgID      uuid.UUID
	UserID     *uuid.UUID
	AcceptedAt time.Time
	Ip         *netip.Addr
	OrgName    string
	AcceptedBy *string
}

// tenant: system - the platform admin's record of who accepted a document.
func (q *Queries) LegalAcceptances(ctx context.Context, documentID uuid.UUID) ([]LegalAcceptancesRow, error) {
	rows, err := q.db.Query(ctx, legalAcceptances, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegalAcceptancesRow
	for rows.Next() {
		var i LegalAcceptancesRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.OrgID,
			&i.UserID,
			&i.AcceptedAt,
			&i.Ip,
			&i.OrgName,
			&i.AcceptedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalVersions = `-- name: ListLegalVersions :many
SELECT id, kind, version, title, published_at, (SELECT count(*) FROM legal_acceptances a WHERE a.document_id = d.id)::bigint AS acceptances
FROM legal_documents d WHERE org_id IS NULL ORDER BY kind, version DESC
`

type ListLegalVersionsRow struct {
	ID          uuid.UUID
	Kind        string
	Version     int32
	Title       string
	PublishedAt time.Time
	Acceptances int64
}

// tenant: system - the platform admin's history of platform-wide documents.
func (q *Queries) ListLegalVersions(ctx context.Context) ([]ListLegalVersionsRow, error) {
	rows, err := q.db.Query(ctx, listLegalVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegalVersionsRow
	for rows.Next() {
		var i ListLegalVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Title,
			&i.PublishedAt,
			&i.Acceptances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgLegalAcceptance = `-- name: OrgLegalAcceptance :one
SELECT a.document_id, a.org_id, a.user_id, a.accepted_at, a.ip, u.email AS accepted_by FROM legal_acceptances a LEFT JOIN users u ON u.id = a.user_id
WHERE a.document_id = $1 AND a.org_id = $2
`

type OrgLegalAcceptanceParams struct {
	DocumentID uuid.UUID
	OrgID      uuid.UUID
}

type OrgLegalAcceptanceRow struct {
	DocumentID uuid.UUID
	OrgID      uuid.UUID
	UserID     *uuid.UUID
	AcceptedAt time.Time
	Ip         *netip.Addr
	AcceptedBy *string
}

func (q *Queries) OrgLegalAcceptance(ctx context.Context, arg OrgLegalAcceptanceParams) (OrgLegalAcceptanceRow, error) {
	row := q.db.QueryRow(ctx, orgLegalAcceptance, arg.DocumentID, arg.OrgID)
	var i OrgLegalAcceptanceRow
	err := row.Scan(
		&i.DocumentID,
		&i.OrgID,
		&i.UserID,
		&i.AcceptedAt,
		&i.Ip,
		&i.AcceptedBy,
	)
	return i, err
}
