// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const finishMinorUpgrade = `-- name: FinishMinorUpgrade :exec
UPDATE minor_upgrades SET finished_at = now(), pause_ms = $1, error = $2 WHERE id = $3
`

type FinishMinorUpgradeParams struct {
	PauseMs *int32
	Error   *string
	ID      uuid.UUID
}

// tenant: system - the maintenance sweep records its own runs.
func (q *Queries) FinishMinorUpgrade(ctx context.Context, arg FinishMinorUpgradeParams) error {
	_, err := q.db.Exec(ctx, finishMinorUpgrade, arg.PauseMs, arg.Error, arg.ID)
	return err
}

const getMinorUpgrade = `-- name: GetMinorUpgrade :one
SELECT m.id, m.instance_id, m.from_release, m.to_release, m.started_at, m.finished_at, m.pause_ms, m.error, i.kind, n.name AS node_name
FROM minor_upgrades m JOIN instances i ON i.id = m.instance_id JOIN nodes n ON n.id = i.node_id
WHERE m.id = $1
`

type GetMinorUpgradeRow struct {
	ID          uuid.UUID
	InstanceID  uuid.UUID
	FromRelease string
	ToRelease   string
	StartedAt   time.Time
	FinishedAt  *time.Time
	PauseMs     *int32
	Error       *string
	Kind        string
	NodeName    string
}

// tenant: system - platform maintenance history for the admin console.
func (q *Queries) GetMinorUpgrade(ctx context.Context, id uuid.UUID) (GetMinorUpgradeRow, error) {
	row := q.db.QueryRow(ctx, getMinorUpgrade, id)
	var i GetMinorUpgradeRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.FromRelease,
		&i.ToRelease,
		&i.StartedAt,
		&i.FinishedAt,
		&i.PauseMs,
		&i.Error,
		&i.Kind,
		&i.NodeName,
	)
	return i, err
}

const instanceBusy = `-- name: InstanceBusy :one
SELECT EXISTS (
  SELECT 1 FROM projects p
  WHERE p.instance_id = $1 AND p.deleted_at IS NULL
    AND (p.status <> 'active' OR EXISTS (
      SELECT 1 FROM operations o WHERE o.project_id = p.id AND o.status IN ('queued', 'running')))
)::bool
`

// InstanceBusy reports whether a project on the instance is in the middle
// of something (a move, a restore, a queued operation) that a restart
// would get in the way of.
// tenant: system - the maintenance sweep checks every project on the instance.
func (q *Queries) InstanceBusy(ctx context.Context, instanceID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, instanceBusy, instanceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const instancesBehind = `-- name: InstancesBehind :many
SELECT id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port, host, admin_secret, profile, walg_prefix, error, deleted_at, org_id, walg_target_id, walg_key_id, pg_release, pg_release_available, release_checked_at, ha_enabled, sync_replication, patroni, leader_member, patroni_secret, etcd_region FROM instances
WHERE deleted_at IS NULL AND status = 'running'
  AND pg_release IS NOT NULL AND pg_release_available IS NOT NULL AND pg_release <> pg_release_available
ORDER BY kind = 'shared', created_at
`

// InstancesBehind lists running instances whose image has another release;
// the caller keeps the ones where it is newer. Dedicated instances go
// first: each restart there pauses one project, not a cluster's worth.
// tenant: system - the maintenance sweep reads every running instance.
func (q *Queries) InstancesBehind(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, instancesBehind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.PgVersion,
			&i.Port,
			&i.ContainerID,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.Status,
			&i.CreatedAt,
			&i.AdminHost,
			&i.AdminPort,
			&i.Host,
			&i.AdminSecret,
			&i.Profile,
			&i.WalgPrefix,
			&i.Error,
			&i.DeletedAt,
			&i.OrgID,
			&i.WalgTargetID,
			&i.WalgKeyID,
			&i.PgRelease,
			&i.PgReleaseAvailable,
			&i.ReleaseCheckedAt,
			&i.HaEnabled,
			&i.SyncReplication,
			&i.Patroni,
			&i.LeaderMember,
			&i.PatroniSecret,
			&i.EtcdRegion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instancesToCheckRelease = `-- name: InstancesToCheckRelease :many
SELECT id, node_id, kind, pg_version, port, container_id, cpu_limit, mem_limit_mb, volume_gb, status, created_at, admin_host, admin_port, host, admin_secret, profile, walg_prefix, error, deleted_at, org_id, walg_target_id, walg_key_id, pg_release, pg_release_available, release_checked_at, ha_enabled, sync_replication, patroni, leader_member, patroni_secret, etcd_region FROM instances
WHERE deleted_at IS NULL AND status = 'running'
  AND (release_checked_at IS NULL OR release_checked_at < $1::timestamptz)
ORDER BY release_checked_at NULLS FIRST, created_at
`

// tenant: system - the maintenance sweep reads every running instance.
func (q *Queries) InstancesToCheckRelease(ctx context.Context, before time.Time) ([]Instance, error) {
	rows, err := q.db.Query(ctx, instancesToCheckRelease, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.PgVersion,
			&i.Port,
			&i.ContainerID,
			&i.CpuLimit,
			&i.MemLimitMb,
			&i.VolumeGb,
			&i.Status,
			&i.CreatedAt,
			&i.AdminHost,
			&i.AdminPort,
			&i.Host,
			&i.AdminSecret,
			&i.Profile,
			&i.WalgPrefix,
			&i.Error,
			&i.DeletedAt,
			&i.OrgID,
			&i.WalgTargetID,
			&i.WalgKeyID,
			&i.PgRelease,
			&i.PgReleaseAvailable,
			&i.ReleaseCheckedAt,
			&i.HaEnabled,
			&i.SyncReplication,
			&i.Patroni,
			&i.LeaderMember,
			&i.PatroniSecret,
			&i.EtcdRegion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestMinorUpgrades = `-- name: LatestMinorUpgrades :many
SELECT m.id, m.instance_id, m.from_release, m.to_release, m.started_at, m.finished_at, m.pause_ms, m.error, i.kind, n.name AS node_name
FROM minor_upgrades m JOIN instances i ON i.id = m.instance_id JOIN nodes n ON n.id = i.node_id
ORDER BY m.started_at DESC LIMIT $1
`

type LatestMinorUpgradesRow struct {
	ID          uuid.UUID
	InstanceID  uuid.UUID
	FromRelease string
	ToRelease   string
	StartedAt   time.Time
	FinishedAt  *time.Time
	PauseMs     *int32
	Error       *string
	Kind        string
	NodeName    string
}

// tenant: system - platform maintenance history for the admin console.
func (q *Queries) LatestMinorUpgrades(ctx context.Context, lim int32) ([]LatestMinorUpgradesRow, error) {
	rows, err := q.db.Query(ctx, latestMinorUpgrades, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestMinorUpgradesRow
	for rows.Next() {
		var i LatestMinorUpgradesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.FromRelease,
			&i.ToRelease,
			&i.StartedAt,
			&i.FinishedAt,
			&i.PauseMs,
			&i.Error,
			&i.Kind,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenanceProjects = `-- name: MaintenanceProjects :many
SELECT id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier, lifecycle, last_active_at, pause_warned_at, paused_at, archived_at, archive_backup_id, archive_notice_days, region, data_residency, forward_region, forward_until FROM projects WHERE instance_id = $1 AND deleted_at IS NULL ORDER BY created_at
`

// tenant: system - the maintenance sweep pauses every project on the instance.
func (q *Queries) MaintenanceProjects(ctx context.Context, instanceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, maintenanceProjects, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
			&i.Lifecycle,
			&i.LastActiveAt,
			&i.PauseWarnedAt,
			&i.PausedAt,
			&i.ArchivedAt,
			&i.ArchiveBackupID,
			&i.ArchiveNoticeDays,
			&i.Region,
			&i.DataResidency,
			&i.ForwardRegion,
			&i.ForwardUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstanceRelease = `-- name: SetInstanceRelease :exec
UPDATE instances SET pg_release = $1, pg_release_available = $2,
  release_checked_at = now()
WHERE id = $3
`

type SetInstanceReleaseParams struct {
	PgRelease          *string
	PgReleaseAvailable *string
	ID                 uuid.UUID
}

// tenant: system - the maintenance sweep records what agents report.
func (q *Queries) SetInstanceRelease(ctx context.Context, arg SetInstanceReleaseParams) error {
	_, err := q.db.Exec(ctx, setInstanceRelease, arg.PgRelease, arg.PgReleaseAvailable, arg.ID)
	return err
}

const startMinorUpgrade = `-- name: StartMinorUpgrade :one
INSERT INTO minor_upgrades (instance_id, from_release, to_release) VALUES ($1, $2, $3)
RETURNING id, instance_id, from_release, to_release, started_at, finished_at, pause_ms, error
`

type StartMinorUpgradeParams struct {
	InstanceID  uuid.UUID
	FromRelease string
	ToRelease   string
}

// tenant: system - the maintenance sweep records its own runs.
func (q *Queries) StartMinorUpgrade(ctx context.Context, arg StartMinorUpgradeParams) (MinorUpgrade, error) {
	row := q.db.QueryRow(ctx, startMinorUpgrade, arg.InstanceID, arg.FromRelease, arg.ToRelease)
	var i MinorUpgrade
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.FromRelease,
		&i.ToRelease,
		&i.StartedAt,
		&i.FinishedAt,
		&i.PauseMs,
		&i.Error,
	)
	return i, err
}
