// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProjectExtension = `-- name: AddProjectExtension :exec
UPDATE projects SET extensions = (SELECT array_agg(DISTINCT e ORDER BY e) FROM unnest(extensions || $1::text) AS e)
WHERE id = $2
`

type AddProjectExtensionParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) AddProjectExtension(ctx context.Context, arg AddProjectExtensionParams) error {
	_, err := q.db.Exec(ctx, addProjectExtension, arg.Name, arg.ID)
	return err
}

const downsampleMetrics = `-- name: DownsampleMetrics :execrows
INSERT INTO metric_points (scope, scope_id, metric, ts, resolution, value)
SELECT scope, scope_id, metric, date_trunc('hour', ts), '1h', avg(value)
FROM metric_points
WHERE resolution = '1m' AND ts >= date_trunc('hour', $1::timestamptz) AND ts < date_trunc('hour', now())
GROUP BY scope, scope_id, metric, date_trunc('hour', ts)
ON CONFLICT (scope, scope_id, metric, resolution, ts) DO UPDATE SET value = EXCLUDED.value
`

// Hourly averages of the 1-minute points of completed hours since @since.
func (q *Queries) DownsampleMetrics(ctx context.Context, since time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, downsampleMetrics, since)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestMetrics = `-- name: LatestMetrics :many
SELECT DISTINCT ON (scope, scope_id, metric) scope, scope_id, metric, ts, value
FROM metric_points
WHERE resolution = '1m' AND ts >= $1
ORDER BY scope, scope_id, metric, ts DESC
`

type LatestMetricsRow struct {
	Scope   string
	ScopeID uuid.UUID
	Metric  string
	Ts      time.Time
	Value   float64
}

func (q *Queries) LatestMetrics(ctx context.Context, since time.Time) ([]LatestMetricsRow, error) {
	rows, err := q.db.Query(ctx, latestMetrics, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestMetricsRow
	for rows.Next() {
		var i LatestMetricsRow
		if err := rows.Scan(
			&i.Scope,
			&i.ScopeID,
			&i.Metric,
			&i.Ts,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricSeries = `-- name: MetricSeries :many
SELECT metric, ts, value FROM metric_points
WHERE scope = $1 AND scope_id = $2 AND resolution = $3
  AND ts >= $4 AND (cardinality($5::text[]) = 0 OR metric = ANY($5::text[]))
ORDER BY metric, ts
`

type MetricSeriesParams struct {
	Scope      string
	ScopeID    uuid.UUID
	Resolution string
	Since      time.Time
	Metrics    []string
}

type MetricSeriesRow struct {
	Metric string
	Ts     time.Time
	Value  float64
}

func (q *Queries) MetricSeries(ctx context.Context, arg MetricSeriesParams) ([]MetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, metricSeries,
		arg.Scope,
		arg.ScopeID,
		arg.Resolution,
		arg.Since,
		arg.Metrics,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricSeriesRow
	for rows.Next() {
		var i MetricSeriesRow
		if err := rows.Scan(&i.Metric, &i.Ts, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneMetrics = `-- name: PruneMetrics :execrows
DELETE FROM metric_points
WHERE (resolution = '1m' AND ts < now() - interval '24 hours')
   OR (resolution = '1h' AND ts < now() - interval '30 days')
`

func (q *Queries) PruneMetrics(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneMetrics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMetricPoints = `-- name: UpsertMetricPoints :exec
INSERT INTO metric_points (scope, scope_id, metric, ts, resolution, value)
SELECT $1::text, unnest($2::uuid[]), unnest($3::text[]), $4::timestamptz, '1m', unnest($5::float8[])
ON CONFLICT (scope, scope_id, metric, resolution, ts) DO UPDATE SET value = EXCLUDED.value
`

type UpsertMetricPointsParams struct {
	Scope    string
	ScopeIds []uuid.UUID
	Metrics  []string
	Ts       time.Time
	Vals     []float64
}

// One row per (scope_id, metric) pair in the arrays, at one timestamp.
func (q *Queries) UpsertMetricPoints(ctx context.Context, arg UpsertMetricPointsParams) error {
	_, err := q.db.Exec(ctx, upsertMetricPoints,
		arg.Scope,
		arg.ScopeIds,
		arg.Metrics,
		arg.Ts,
		arg.Vals,
	)
	return err
}
