// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64
	OperatorID *uuid.UUID
	Action     string
	TargetType *string
	TargetID   *string
	Detail     json.RawMessage
	Ip         *netip.Addr
	UserAgent  *string
	Outcome    string
	CreatedAt  time.Time
}

type Backup struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Kind       string
	ObjectKey  string
	SizeBytes  *int64
	Checksum   *string
	StartedAt  time.Time
	FinishedAt *time.Time
	Status     string
	ExpiresAt  *time.Time
}

type Instance struct {
	ID          uuid.UUID
	NodeID      uuid.UUID
	Kind        string
	PgVersion   int32
	Port        int32
	ContainerID *string
	CpuLimit    pgtype.Numeric
	MemLimitMb  *int32
	VolumeGb    *int32
	Status      string
	CreatedAt   time.Time
}

type MetricPoint struct {
	Scope      string
	ScopeID    uuid.UUID
	Metric     string
	Ts         time.Time
	Resolution string
	Value      float64
}

type Node struct {
	ID            uuid.UUID
	Name          string
	PrivateAddr   netip.Addr
	AgentPort     int32
	Role          string
	AgentCertFp   string
	PgAdminSecret []byte
	Capacity      json.RawMessage
	Status        string
	LastHeartbeat *time.Time
	CreatedAt     time.Time
}

type Operation struct {
	ID         uuid.UUID
	Kind       string
	ProjectID  *uuid.UUID
	Params     json.RawMessage
	Status     string
	Attempts   int32
	RunAfter   time.Time
	LockedBy   *string
	LockedAt   *time.Time
	Log        json.RawMessage
	Error      *string
	CreatedBy  *uuid.UUID
	CreatedAt  time.Time
	FinishedAt *time.Time
}

type Operator struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	TotpSecret   []byte
	Role         string
	CreatedAt    time.Time
	DisabledAt   *time.Time
}

type Project struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	DbName          string
	OwnerRole       string
	ScramVerifier   string
	Tier            string
	InstanceID      uuid.UUID
	Status          string
	Settings        json.RawMessage
	StorageTargetID uuid.UUID
	Extensions      []string
	Description     *string
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	DeletedAt       *time.Time
}

type Session struct {
	ID         string
	OperatorID uuid.UUID
	CreatedAt  time.Time
	LastSeenAt time.Time
	ReauthAt   *time.Time
	Ip         *netip.Addr
	UserAgent  *string
}

type Setting struct {
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

type StorageTarget struct {
	ID          uuid.UUID
	Name        string
	Endpoint    string
	Bucket      string
	Prefix      string
	Credentials []byte
	IsDefault   bool
	CreatedAt   time.Time
}
