// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const completeNodeRegistration = `-- name: CompleteNodeRegistration :one
UPDATE nodes
SET agent_cert_fp = $1, agent_host = $2, agent_port = $3,
    agent_version = $4, registration_token = NULL, registration_expires_at = NULL,
    last_heartbeat = now(), status = 'healthy'
WHERE id = $5
RETURNING id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at
`

type CompleteNodeRegistrationParams struct {
	AgentCertFp  *string
	AgentHost    *string
	AgentPort    int32
	AgentVersion *string
	ID           uuid.UUID
}

func (q *Queries) CompleteNodeRegistration(ctx context.Context, arg CompleteNodeRegistrationParams) (Node, error) {
	row := q.db.QueryRow(ctx, completeNodeRegistration,
		arg.AgentCertFp,
		arg.AgentHost,
		arg.AgentPort,
		arg.AgentVersion,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const firstAgentNode = `-- name: FirstAgentNode :one
SELECT id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at FROM nodes WHERE agent_cert_fp IS NOT NULL ORDER BY created_at LIMIT 1
`

func (q *Queries) FirstAgentNode(ctx context.Context) (Node, error) {
	row := q.db.QueryRow(ctx, firstAgentNode)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at FROM nodes WHERE name = $1
`

func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const getNodeByRegistrationToken = `-- name: GetNodeByRegistrationToken :one
SELECT id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at FROM nodes
WHERE registration_token = $1 AND registration_expires_at > now()
FOR UPDATE
`

func (q *Queries) GetNodeByRegistrationToken(ctx context.Context, registrationToken *string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByRegistrationToken, registrationToken)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :one
INSERT INTO nodes (name, private_addr, role, capacity, registration_token, registration_expires_at)
VALUES ($1, $2, $3, '{}', $4, $5)
RETURNING id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at
`

type InsertNodeParams struct {
	Name                  string
	PrivateAddr           string
	Role                  string
	RegistrationToken     *string
	RegistrationExpiresAt *time.Time
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, insertNode,
		arg.Name,
		arg.PrivateAddr,
		arg.Role,
		arg.RegistrationToken,
		arg.RegistrationExpiresAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at FROM nodes ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrivateAddr,
			&i.AgentPort,
			&i.Role,
			&i.AgentCertFp,
			&i.PgAdminSecret,
			&i.Capacity,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.AgentHost,
			&i.AgentVersion,
			&i.RegistrationToken,
			&i.RegistrationExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeForInstance = `-- name: NodeForInstance :one
SELECT n.id, n.name, n.private_addr, n.agent_port, n.role, n.agent_cert_fp, n.pg_admin_secret, n.capacity, n.status, n.last_heartbeat, n.created_at, n.agent_host, n.agent_version, n.registration_token, n.registration_expires_at FROM nodes n JOIN instances i ON i.node_id = n.id WHERE i.id = $1
`

func (q *Queries) NodeForInstance(ctx context.Context, instanceID uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, nodeForInstance, instanceID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateAddr,
		&i.AgentPort,
		&i.Role,
		&i.AgentCertFp,
		&i.PgAdminSecret,
		&i.Capacity,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.AgentHost,
		&i.AgentVersion,
		&i.RegistrationToken,
		&i.RegistrationExpiresAt,
	)
	return i, err
}

const nodeLiveInstances = `-- name: NodeLiveInstances :one
SELECT count(*)::int FROM instances WHERE node_id = $1 AND deleted_at IS NULL
`

func (q *Queries) NodeLiveInstances(ctx context.Context, nodeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nodeLiveInstances, nodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recordNodeHeartbeat = `-- name: RecordNodeHeartbeat :exec
UPDATE nodes SET last_heartbeat = now(), status = $1, capacity = $2, agent_version = $3
WHERE id = $4
`

type RecordNodeHeartbeatParams struct {
	Status       string
	Capacity     json.RawMessage
	AgentVersion *string
	ID           uuid.UUID
}

func (q *Queries) RecordNodeHeartbeat(ctx context.Context, arg RecordNodeHeartbeatParams) error {
	_, err := q.db.Exec(ctx, recordNodeHeartbeat,
		arg.Status,
		arg.Capacity,
		arg.AgentVersion,
		arg.ID,
	)
	return err
}

const removeNode = `-- name: RemoveNode :exec
UPDATE nodes SET status = 'removed', agent_cert_fp = NULL, registration_token = NULL WHERE id = $1
`

func (q *Queries) RemoveNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeNode, id)
	return err
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes SET status = $1 WHERE id = $2
`

type SetNodeStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.Exec(ctx, setNodeStatus, arg.Status, arg.ID)
	return err
}

const setRegistrationToken = `-- name: SetRegistrationToken :exec
UPDATE nodes SET registration_token = $1, registration_expires_at = $2
WHERE id = $3
`

type SetRegistrationTokenParams struct {
	RegistrationToken     *string
	RegistrationExpiresAt *time.Time
	ID                    uuid.UUID
}

func (q *Queries) SetRegistrationToken(ctx context.Context, arg SetRegistrationTokenParams) error {
	_, err := q.db.Exec(ctx, setRegistrationToken, arg.RegistrationToken, arg.RegistrationExpiresAt, arg.ID)
	return err
}
