// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendOperationLog = `-- name: AppendOperationLog :execrows
UPDATE operations SET log = log || jsonb_build_array($1::jsonb)
WHERE id = $2 AND locked_by = $3::text AND status = 'running'
`

type AppendOperationLogParams struct {
	Entry  json.RawMessage
	ID     uuid.UUID
	Worker string
}

func (q *Queries) AppendOperationLog(ctx context.Context, arg AppendOperationLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendOperationLog, arg.Entry, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimOperation = `-- name: ClaimOperation :one
UPDATE operations
SET status = 'running', attempts = attempts + 1, locked_by = $1::text, locked_at = now()
WHERE id = (
  SELECT o.id FROM operations o
  WHERE o.status = 'queued' AND o.run_after <= now() AND o.kind = ANY($2::text[])
  ORDER BY o.run_after, o.created_at
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, kind, project_id, params, status, attempts, run_after, locked_by, locked_at, log, error, created_by, created_at, finished_at
`

type ClaimOperationParams struct {
	Worker string
	Kinds  []string
}

// ClaimOperation takes the next runnable operation of one of the given
// kinds. SKIP LOCKED lets any number of workers claim concurrently without
// blocking each other or double-claiming.
func (q *Queries) ClaimOperation(ctx context.Context, arg ClaimOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, claimOperation, arg.Worker, arg.Kinds)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.Params,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.Log,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const enqueueOperation = `-- name: EnqueueOperation :one
INSERT INTO operations (kind, project_id, params, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, kind, project_id, params, status, attempts, run_after, locked_by, locked_at, log, error, created_by, created_at, finished_at
`

type EnqueueOperationParams struct {
	Kind      string
	ProjectID *uuid.UUID
	Params    json.RawMessage
	CreatedBy *uuid.UUID
}

func (q *Queries) EnqueueOperation(ctx context.Context, arg EnqueueOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, enqueueOperation,
		arg.Kind,
		arg.ProjectID,
		arg.Params,
		arg.CreatedBy,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.Params,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.Log,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failOperation = `-- name: FailOperation :execrows
UPDATE operations
SET status = 'failed', error = $1::text, params = params - 'secrets', finished_at = now(), locked_by = NULL, locked_at = NULL
WHERE id = $2 AND locked_by = $3::text AND status = 'running'
`

type FailOperationParams struct {
	Error  string
	ID     uuid.UUID
	Worker string
}

func (q *Queries) FailOperation(ctx context.Context, arg FailOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failOperation, arg.Error, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOperation = `-- name: GetOperation :one
SELECT id, kind, project_id, params, status, attempts, run_after, locked_by, locked_at, log, error, created_by, created_at, finished_at FROM operations WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.Params,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.Log,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const heartbeatOperation = `-- name: HeartbeatOperation :execrows
UPDATE operations SET locked_at = now()
WHERE id = $1 AND locked_by = $2::text AND status = 'running'
`

type HeartbeatOperationParams struct {
	ID     uuid.UUID
	Worker string
}

func (q *Queries) HeartbeatOperation(ctx context.Context, arg HeartbeatOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatOperation, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOperations = `-- name: ListOperations :many
SELECT id, kind, project_id, params, status, attempts, run_after, locked_by, locked_at, log, error, created_by, created_at, finished_at FROM operations
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR kind = $2)
  AND ($3::uuid IS NULL OR project_id = $3)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListOperationsParams struct {
	Status    *string
	Kind      *string
	ProjectID *uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListOperations(ctx context.Context, arg ListOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations,
		arg.Status,
		arg.Kind,
		arg.ProjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ProjectID,
			&i.Params,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LockedBy,
			&i.LockedAt,
			&i.Log,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectHasActiveOperation = `-- name: ProjectHasActiveOperation :one
SELECT EXISTS (
  SELECT 1 FROM operations
  WHERE project_id = $1 AND status IN ('queued', 'running')
)
`

func (q *Queries) ProjectHasActiveOperation(ctx context.Context, projectID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, projectHasActiveOperation, projectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reclaimStaleOperations = `-- name: ReclaimStaleOperations :many
UPDATE operations
SET status = 'queued', locked_by = NULL, locked_at = NULL,
    log = log || jsonb_build_array(jsonb_build_object(
      'ts', now(), 'step', 'queue', 'level', 'warn',
      'msg', 'worker ' || locked_by || ' stopped heartbeating; requeued'))
WHERE status = 'running' AND locked_at < $1::timestamptz
RETURNING id
`

// ReclaimStaleOperations requeues running operations whose worker stopped
// heartbeating (crashed or partitioned), so they resume elsewhere.
func (q *Queries) ReclaimStaleOperations(ctx context.Context, staleBefore time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, reclaimStaleOperations, staleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryOperation = `-- name: RetryOperation :execrows
UPDATE operations
SET status = 'queued', error = $1::text, run_after = $2, locked_by = NULL, locked_at = NULL
WHERE id = $3 AND locked_by = $4::text AND status = 'running'
`

type RetryOperationParams struct {
	Error    string
	RunAfter time.Time
	ID       uuid.UUID
	Worker   string
}

func (q *Queries) RetryOperation(ctx context.Context, arg RetryOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOperation,
		arg.Error,
		arg.RunAfter,
		arg.ID,
		arg.Worker,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedOperation = `-- name: SucceedOperation :execrows
UPDATE operations
SET status = 'succeeded', error = NULL, params = params - 'secrets', finished_at = now(), locked_by = NULL, locked_at = NULL
WHERE id = $1 AND locked_by = $2::text AND status = 'running'
`

type SucceedOperationParams struct {
	ID     uuid.UUID
	Worker string
}

// params.secrets carries encrypted, short-lived handoff data (for example
// a new password for the smoke test). It is scrubbed when an operation
// finishes either way.
func (q *Queries) SucceedOperation(ctx context.Context, arg SucceedOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, succeedOperation, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
