// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPaymentRefunded = `-- name: AddPaymentRefunded :exec
UPDATE payments SET refunded_minor = refunded_minor + $1 WHERE id = $2
`

type AddPaymentRefundedParams struct {
	AmountMinor int64
	ID          uuid.UUID
}

// tenant: system - a refund completed.
func (q *Queries) AddPaymentRefunded(ctx context.Context, arg AddPaymentRefundedParams) error {
	_, err := q.db.Exec(ctx, addPaymentRefunded, arg.AmountMinor, arg.ID)
	return err
}

const addPrepaidDeduction = `-- name: AddPrepaidDeduction :exec
INSERT INTO prepaid_deductions (org_id, month, account, amount_minor) VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, month, account) DO UPDATE SET amount_minor = prepaid_deductions.amount_minor + EXCLUDED.amount_minor, updated_at = now()
`

type AddPrepaidDeductionParams struct {
	OrgID       uuid.UUID
	Month       pgtype.Date
	Account     string
	AmountMinor int64
}

// tenant: system - a day's deduction.
func (q *Queries) AddPrepaidDeduction(ctx context.Context, arg AddPrepaidDeductionParams) error {
	_, err := q.db.Exec(ctx, addPrepaidDeduction,
		arg.OrgID,
		arg.Month,
		arg.Account,
		arg.AmountMinor,
	)
	return err
}

const defaultPaymentMethod = `-- name: DefaultPaymentMethod :one
SELECT id, org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default, status, reminded_days, created_at FROM payment_methods WHERE org_id = $1 AND status = 'active' ORDER BY is_default DESC, created_at LIMIT 1
`

// tenant: system - what PGDock charges for an org.
func (q *Queries) DefaultPaymentMethod(ctx context.Context, orgID uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, defaultPaymentMethod, orgID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.TokenSealed,
		&i.ProviderRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.LimitMinor,
		&i.IsDefault,
		&i.Status,
		&i.RemindedDays,
		&i.CreatedAt,
	)
	return i, err
}

const dunningAccounts = `-- name: DunningAccounts :many
SELECT b.org_id, b.plan, b.term, b.term_ends_at, b.mode, b.price_book_version, b.grandfathered, b.legal_name, b.address, b.tin, b.vat_registered, b.deducts_wht, b.provider_customers, b.payment_terms_days, b.budget_minor, b.spend_cap_minor, b.auto_topup, b.dunning_state, b.grace_until, b.forecast_minor, b.forecast_at, b.capped, b.budget_alerted, b.budget_month, b.created_at, b.updated_at, b.dunning_since, b.deletion_scheduled_at, b.balance_alerted, b.balance_month, b.zero_balance_at, b.card_failing_since, o.status AS org_status, o.name AS org_name FROM billing_accounts b JOIN organizations o ON o.id = b.org_id
WHERE o.status <> 'deleted' AND (b.dunning_state <> 'ok' OR b.card_failing_since IS NOT NULL
  OR EXISTS (SELECT 1 FROM invoices i WHERE i.org_id = b.org_id AND i.status IN ('issued', 'partially_paid') AND i.total_minor > 0 AND i.due_at < $1::timestamptz)
  OR b.zero_balance_at IS NOT NULL)
`

type DunningAccountsRow struct {
	OrgID               uuid.UUID
	Plan                string
	Term                string
	TermEndsAt          *time.Time
	Mode                string
	PriceBookVersion    int32
	Grandfathered       bool
	LegalName           *string
	Address             *string
	Tin                 *string
	VatRegistered       bool
	DeductsWht          bool
	ProviderCustomers   json.RawMessage
	PaymentTermsDays    int32
	BudgetMinor         *int64
	SpendCapMinor       *int64
	AutoTopup           []byte
	DunningState        string
	GraceUntil          *time.Time
	ForecastMinor       *int64
	ForecastAt          *time.Time
	Capped              bool
	BudgetAlerted       int32
	BudgetMonth         pgtype.Date
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DunningSince        *time.Time
	DeletionScheduledAt *time.Time
	BalanceAlerted      int32
	BalanceMonth        pgtype.Date
	ZeroBalanceAt       *time.Time
	CardFailingSince    *time.Time
	OrgStatus           string
	OrgName             string
}

// tenant: system - orgs owing money or in a dunning state.
func (q *Queries) DunningAccounts(ctx context.Context, at time.Time) ([]DunningAccountsRow, error) {
	rows, err := q.db.Query(ctx, dunningAccounts, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DunningAccountsRow
	for rows.Next() {
		var i DunningAccountsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Plan,
			&i.Term,
			&i.TermEndsAt,
			&i.Mode,
			&i.PriceBookVersion,
			&i.Grandfathered,
			&i.LegalName,
			&i.Address,
			&i.Tin,
			&i.VatRegistered,
			&i.DeductsWht,
			&i.ProviderCustomers,
			&i.PaymentTermsDays,
			&i.BudgetMinor,
			&i.SpendCapMinor,
			&i.AutoTopup,
			&i.DunningState,
			&i.GraceUntil,
			&i.ForecastMinor,
			&i.ForecastAt,
			&i.Capped,
			&i.BudgetAlerted,
			&i.BudgetMonth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DunningSince,
			&i.DeletionScheduledAt,
			&i.BalanceAlerted,
			&i.BalanceMonth,
			&i.ZeroBalanceAt,
			&i.CardFailingSince,
			&i.OrgStatus,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiringCards = `-- name: ExpiringCards :many
SELECT id, org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default, status, reminded_days, created_at FROM payment_methods WHERE kind = 'card' AND status = 'active' AND exp_year IS NOT NULL AND exp_month IS NOT NULL
`

// tenant: system - cards for expiry reminders.
func (q *Queries) ExpiringCards(ctx context.Context) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, expiringCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.Kind,
			&i.TokenSealed,
			&i.ProviderRef,
			&i.Brand,
			&i.Last4,
			&i.ExpMonth,
			&i.ExpYear,
			&i.LimitMinor,
			&i.IsDefault,
			&i.Status,
			&i.RemindedDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishPaymentEvent = `-- name: FinishPaymentEvent :exec
UPDATE payment_events SET processed_at = now(), outcome = $1, error = $2, org_id = coalesce($3, org_id)
WHERE id = $4
`

type FinishPaymentEventParams struct {
	Outcome *string
	Error   *string
	OrgID   *uuid.UUID
	ID      int64
}

// tenant: system - the outcome of processing an event.
func (q *Queries) FinishPaymentEvent(ctx context.Context, arg FinishPaymentEventParams) error {
	_, err := q.db.Exec(ctx, finishPaymentEvent,
		arg.Outcome,
		arg.Error,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const finishPaymentIntent = `-- name: FinishPaymentIntent :exec
UPDATE payment_intents SET status = $1, error = $2, completed_at = now()
WHERE reference = $3 AND status = 'pending'
`

type FinishPaymentIntentParams struct {
	Status    string
	Error     *string
	Reference string
}

// tenant: system - a checkout or charge ended.
func (q *Queries) FinishPaymentIntent(ctx context.Context, arg FinishPaymentIntentParams) error {
	_, err := q.db.Exec(ctx, finishPaymentIntent, arg.Status, arg.Error, arg.Reference)
	return err
}

const finishRefund = `-- name: FinishRefund :one
UPDATE refunds SET status = $1, provider_ref = coalesce($2, provider_ref), error = $3,
  completed_at = CASE WHEN $1 <> 'pending' THEN now() END
WHERE id = $4 RETURNING id, payment_id, amount_minor, reason, provider_ref, status, error, created_by, created_at, completed_at
`

type FinishRefundParams struct {
	Status      string
	ProviderRef *string
	Error       *string
	ID          uuid.UUID
}

// tenant: system - a refund's outcome.
func (q *Queries) FinishRefund(ctx context.Context, arg FinishRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, finishRefund,
		arg.Status,
		arg.ProviderRef,
		arg.Error,
		arg.ID,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.AmountMinor,
		&i.Reason,
		&i.ProviderRef,
		&i.Status,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOrgPaymentMethod = `-- name: GetOrgPaymentMethod :one
SELECT id, org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default, status, reminded_days, created_at FROM payment_methods WHERE id = $1 AND org_id = $2
`

type GetOrgPaymentMethodParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// tenant: org - one of the org's methods.
func (q *Queries) GetOrgPaymentMethod(ctx context.Context, arg GetOrgPaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getOrgPaymentMethod, arg.ID, arg.OrgID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.TokenSealed,
		&i.ProviderRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.LimitMinor,
		&i.IsDefault,
		&i.Status,
		&i.RemindedDays,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, org_id, provider, channel, provider_ref, reference, amount_minor, fee_minor, refunded_minor, fx_quote, note, proof_object_key, recorded_by, received_at, created_at FROM payments WHERE id = $1
`

// tenant: system - a payment by id.
func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Channel,
		&i.ProviderRef,
		&i.Reference,
		&i.AmountMinor,
		&i.FeeMinor,
		&i.RefundedMinor,
		&i.FxQuote,
		&i.Note,
		&i.ProofObjectKey,
		&i.RecordedBy,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, org_id, provider, channel, provider_ref, reference, amount_minor, fee_minor, refunded_minor, fx_quote, note, proof_object_key, recorded_by, received_at, created_at FROM payments WHERE provider = $1 AND provider_ref = $2
`

type GetPaymentByProviderRefParams struct {
	Provider    string
	ProviderRef string
}

// tenant: system - reconciliation.
func (q *Queries) GetPaymentByProviderRef(ctx context.Context, arg GetPaymentByProviderRefParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRef, arg.Provider, arg.ProviderRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Channel,
		&i.ProviderRef,
		&i.Reference,
		&i.AmountMinor,
		&i.FeeMinor,
		&i.RefundedMinor,
		&i.FxQuote,
		&i.Note,
		&i.ProofObjectKey,
		&i.RecordedBy,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentEvent = `-- name: GetPaymentEvent :one
SELECT id, provider, provider_event_id, kind, org_id, reference, provider_ref, amount_minor, currency, payload, received_at, processed_at, outcome, error FROM payment_events WHERE id = $1
`

// tenant: system - one event of the admin's log.
func (q *Queries) GetPaymentEvent(ctx context.Context, id int64) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentEvent, id)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.Kind,
		&i.OrgID,
		&i.Reference,
		&i.ProviderRef,
		&i.AmountMinor,
		&i.Currency,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Outcome,
		&i.Error,
	)
	return i, err
}

const getPaymentIntentByRef = `-- name: GetPaymentIntentByRef :one
SELECT id, org_id, reference, provider, channel, purpose, invoice_id, method_id, amount_minor, status, checkout_url, automatic, error, created_at, completed_at FROM payment_intents WHERE reference = $1
`

// tenant: system - matching a provider event to what we asked for.
func (q *Queries) GetPaymentIntentByRef(ctx context.Context, reference string) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByRef, reference)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Reference,
		&i.Provider,
		&i.Channel,
		&i.Purpose,
		&i.InvoiceID,
		&i.MethodID,
		&i.AmountMinor,
		&i.Status,
		&i.CheckoutUrl,
		&i.Automatic,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRefundByProviderRef = `-- name: GetRefundByProviderRef :one
SELECT id, payment_id, amount_minor, reason, provider_ref, status, error, created_by, created_at, completed_at FROM refunds WHERE provider_ref = $1
`

// tenant: system - matching a refund.completed event.
func (q *Queries) GetRefundByProviderRef(ctx context.Context, providerRef *string) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByProviderRef, providerRef)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.AmountMinor,
		&i.Reason,
		&i.ProviderRef,
		&i.Status,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :exec
INSERT INTO payment_allocations (payment_id, invoice_id, amount_minor, wht_minor) VALUES ($1, $2, $3, $4)
`

type InsertAllocationParams struct {
	PaymentID   uuid.UUID
	InvoiceID   uuid.UUID
	AmountMinor int64
	WhtMinor    int64
}

// tenant: system - a payment settling an invoice.
func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) error {
	_, err := q.db.Exec(ctx, insertAllocation,
		arg.PaymentID,
		arg.InvoiceID,
		arg.AmountMinor,
		arg.WhtMinor,
	)
	return err
}

const insertDunningStep = `-- name: InsertDunningStep :one

INSERT INTO dunning_steps (org_id, cycle, step, detail) VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, cycle, step) DO NOTHING RETURNING id, org_id, cycle, step, detail, taken_at
`

type InsertDunningStepParams struct {
	OrgID  uuid.UUID
	Cycle  time.Time
	Step   string
	Detail *string
}

// ---- Dunning -----------------------------------------------------------------
// tenant: system - a dunning step, once per cycle.
func (q *Queries) InsertDunningStep(ctx context.Context, arg InsertDunningStepParams) (DunningStep, error) {
	row := q.db.QueryRow(ctx, insertDunningStep,
		arg.OrgID,
		arg.Cycle,
		arg.Step,
		arg.Detail,
	)
	var i DunningStep
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Cycle,
		&i.Step,
		&i.Detail,
		&i.TakenAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (org_id, provider, channel, provider_ref, reference, amount_minor, fee_minor, fx_quote, note, proof_object_key, recorded_by, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (provider, provider_ref) DO NOTHING
RETURNING id, org_id, provider, channel, provider_ref, reference, amount_minor, fee_minor, refunded_minor, fx_quote, note, proof_object_key, recorded_by, received_at, created_at
`

type InsertPaymentParams struct {
	OrgID          uuid.UUID
	Provider       string
	Channel        string
	ProviderRef    string
	Reference      *string
	AmountMinor    int64
	FeeMinor       int64
	FxQuote        []byte
	Note           *string
	ProofObjectKey *string
	RecordedBy     *uuid.UUID
	ReceivedAt     time.Time
}

// tenant: system - money received for an org the caller resolved.
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.OrgID,
		arg.Provider,
		arg.Channel,
		arg.ProviderRef,
		arg.Reference,
		arg.AmountMinor,
		arg.FeeMinor,
		arg.FxQuote,
		arg.Note,
		arg.ProofObjectKey,
		arg.RecordedBy,
		arg.ReceivedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Channel,
		&i.ProviderRef,
		&i.Reference,
		&i.AmountMinor,
		&i.FeeMinor,
		&i.RefundedMinor,
		&i.FxQuote,
		&i.Note,
		&i.ProofObjectKey,
		&i.RecordedBy,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :one
INSERT INTO payment_events (provider, provider_event_id, kind, org_id, reference, provider_ref, amount_minor, currency, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (provider, provider_event_id) DO NOTHING
RETURNING id, provider, provider_event_id, kind, org_id, reference, provider_ref, amount_minor, currency, payload, received_at, processed_at, outcome, error
`

type InsertPaymentEventParams struct {
	Provider        string
	ProviderEventID string
	Kind            string
	OrgID           *uuid.UUID
	Reference       *string
	ProviderRef     *string
	AmountMinor     *int64
	Currency        *string
	Payload         json.RawMessage
}

// tenant: system - provider events (rows carry org_id once matched).
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, insertPaymentEvent,
		arg.Provider,
		arg.ProviderEventID,
		arg.Kind,
		arg.OrgID,
		arg.Reference,
		arg.ProviderRef,
		arg.AmountMinor,
		arg.Currency,
		arg.Payload,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.Kind,
		&i.OrgID,
		&i.Reference,
		&i.ProviderRef,
		&i.AmountMinor,
		&i.Currency,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Outcome,
		&i.Error,
	)
	return i, err
}

const insertPaymentIntent = `-- name: InsertPaymentIntent :one
INSERT INTO payment_intents (org_id, reference, provider, channel, purpose, invoice_id, method_id, amount_minor, checkout_url, automatic)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, reference, provider, channel, purpose, invoice_id, method_id, amount_minor, status, checkout_url, automatic, error, created_at, completed_at
`

type InsertPaymentIntentParams struct {
	OrgID       uuid.UUID
	Reference   string
	Provider    string
	Channel     string
	Purpose     string
	InvoiceID   *uuid.UUID
	MethodID    *uuid.UUID
	AmountMinor int64
	CheckoutUrl *string
	Automatic   bool
}

// tenant: system - a checkout or charge for an org the caller resolved.
func (q *Queries) InsertPaymentIntent(ctx context.Context, arg InsertPaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, insertPaymentIntent,
		arg.OrgID,
		arg.Reference,
		arg.Provider,
		arg.Channel,
		arg.Purpose,
		arg.InvoiceID,
		arg.MethodID,
		arg.AmountMinor,
		arg.CheckoutUrl,
		arg.Automatic,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Reference,
		&i.Provider,
		&i.Channel,
		&i.Purpose,
		&i.InvoiceID,
		&i.MethodID,
		&i.AmountMinor,
		&i.Status,
		&i.CheckoutUrl,
		&i.Automatic,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertRefund = `-- name: InsertRefund :one

INSERT INTO refunds (payment_id, amount_minor, reason, created_by) VALUES ($1, $2, $3, $4) RETURNING id, payment_id, amount_minor, reason, provider_ref, status, error, created_by, created_at, completed_at
`

type InsertRefundParams struct {
	PaymentID   uuid.UUID
	AmountMinor int64
	Reason      string
	CreatedBy   *uuid.UUID
}

// ---- Refunds -----------------------------------------------------------------
// tenant: system - a refund of a payment the caller resolved.
func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.PaymentID,
		arg.AmountMinor,
		arg.Reason,
		arg.CreatedBy,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.AmountMinor,
		&i.Reason,
		&i.ProviderRef,
		&i.Status,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertVirtualAccount = `-- name: InsertVirtualAccount :one

INSERT INTO virtual_accounts (org_id, provider, account_number, bank_name, account_name, provider_ref)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, provider) DO UPDATE SET account_number = virtual_accounts.account_number
RETURNING id, org_id, provider, account_number, bank_name, account_name, provider_ref, created_at
`

type InsertVirtualAccountParams struct {
	OrgID         uuid.UUID
	Provider      string
	AccountNumber string
	BankName      string
	AccountName   string
	ProviderRef   *string
}

// ---- Virtual accounts --------------------------------------------------------
// tenant: system - an org's transfer account.
func (q *Queries) InsertVirtualAccount(ctx context.Context, arg InsertVirtualAccountParams) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, insertVirtualAccount,
		arg.OrgID,
		arg.Provider,
		arg.AccountNumber,
		arg.BankName,
		arg.AccountName,
		arg.ProviderRef,
	)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.ProviderRef,
		&i.CreatedAt,
	)
	return i, err
}

const insertWHTCertificate = `-- name: InsertWHTCertificate :one

INSERT INTO wht_certificates (invoice_id, org_id, object_key, filename, size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, invoice_id, org_id, object_key, filename, size_bytes, uploaded_by, uploaded_at
`

type InsertWHTCertificateParams struct {
	InvoiceID  uuid.UUID
	OrgID      uuid.UUID
	ObjectKey  string
	Filename   string
	SizeBytes  int64
	UploadedBy *uuid.UUID
}

// ---- WHT ---------------------------------------------------------------------
// tenant: system - a WHT credit note for an invoice the caller resolved.
func (q *Queries) InsertWHTCertificate(ctx context.Context, arg InsertWHTCertificateParams) (WhtCertificate, error) {
	row := q.db.QueryRow(ctx, insertWHTCertificate,
		arg.InvoiceID,
		arg.OrgID,
		arg.ObjectKey,
		arg.Filename,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i WhtCertificate
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.OrgID,
		&i.ObjectKey,
		&i.Filename,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const invoiceCredited = `-- name: InvoiceCredited :one
SELECT coalesce(sum(amount_minor + vat_minor), 0)::bigint FROM credit_notes WHERE invoice_id = $1
`

// tenant: system - what credit notes took off an invoice.
func (q *Queries) InvoiceCredited(ctx context.Context, invoiceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, invoiceCredited, invoiceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const invoiceWHTCertificates = `-- name: InvoiceWHTCertificates :many
SELECT id, invoice_id, org_id, object_key, filename, size_bytes, uploaded_by, uploaded_at FROM wht_certificates WHERE invoice_id = $1 ORDER BY uploaded_at
`

// tenant: system - an invoice's WHT credit notes.
func (q *Queries) InvoiceWHTCertificates(ctx context.Context, invoiceID uuid.UUID) ([]WhtCertificate, error) {
	rows, err := q.db.Query(ctx, invoiceWHTCertificates, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhtCertificate
	for rows.Next() {
		var i WhtCertificate
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.OrgID,
			&i.ObjectKey,
			&i.Filename,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgPayments = `-- name: ListOrgPayments :many
SELECT id, org_id, provider, channel, provider_ref, reference, amount_minor, fee_minor, refunded_minor, fx_quote, note, proof_object_key, recorded_by, received_at, created_at FROM payments WHERE org_id = $1 ORDER BY received_at DESC LIMIT $2
`

type ListOrgPaymentsParams struct {
	OrgID uuid.UUID
	Lim   int32
}

// tenant: org - the org's payments (receipts).
func (q *Queries) ListOrgPayments(ctx context.Context, arg ListOrgPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listOrgPayments, arg.OrgID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.Channel,
			&i.ProviderRef,
			&i.Reference,
			&i.AmountMinor,
			&i.FeeMinor,
			&i.RefundedMinor,
			&i.FxQuote,
			&i.Note,
			&i.ProofObjectKey,
			&i.RecordedBy,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentEvents = `-- name: ListPaymentEvents :many
SELECT id, provider, provider_event_id, kind, org_id, reference, provider_ref, amount_minor, currency, payload, received_at, processed_at, outcome, error FROM payment_events WHERE ($1::text IS NULL OR outcome = $1)
ORDER BY id DESC LIMIT $2
`

type ListPaymentEventsParams struct {
	Outcome *string
	Lim     int32
}

// tenant: system - the admin's event log.
func (q *Queries) ListPaymentEvents(ctx context.Context, arg ListPaymentEventsParams) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, listPaymentEvents, arg.Outcome, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderEventID,
			&i.Kind,
			&i.OrgID,
			&i.Reference,
			&i.ProviderRef,
			&i.AmountMinor,
			&i.Currency,
			&i.Payload,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Outcome,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default, status, reminded_days, created_at FROM payment_methods WHERE org_id = $1 AND status = 'active' ORDER BY is_default DESC, created_at
`

// tenant: org - the org's saved cards and mandates.
func (q *Queries) ListPaymentMethods(ctx context.Context, orgID uuid.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.Kind,
			&i.TokenSealed,
			&i.ProviderRef,
			&i.Brand,
			&i.Last4,
			&i.ExpMonth,
			&i.ExpYear,
			&i.LimitMinor,
			&i.IsDefault,
			&i.Status,
			&i.RemindedDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT p.id, p.org_id, p.provider, p.channel, p.provider_ref, p.reference, p.amount_minor, p.fee_minor, p.refunded_minor, p.fx_quote, p.note, p.proof_object_key, p.recorded_by, p.received_at, p.created_at, o.name AS org_name FROM payments p JOIN organizations o ON o.id = p.org_id
WHERE ($1::text IS NULL OR p.provider = $1)
  AND p.received_at >= $2 AND p.received_at < $3
ORDER BY p.received_at DESC LIMIT $4
`

type ListPaymentsParams struct {
	Provider *string
	FromTs   time.Time
	ToTs     time.Time
	Lim      int32
}

type ListPaymentsRow struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	Provider       string
	Channel        string
	ProviderRef    string
	Reference      *string
	AmountMinor    int64
	FeeMinor       int64
	RefundedMinor  int64
	FxQuote        []byte
	Note           *string
	ProofObjectKey *string
	RecordedBy     *uuid.UUID
	ReceivedAt     time.Time
	CreatedAt      time.Time
	OrgName        string
}

// tenant: system - the admin's payments.
func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.Provider,
		arg.FromTs,
		arg.ToTs,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsRow
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.Channel,
			&i.ProviderRef,
			&i.Reference,
			&i.AmountMinor,
			&i.FeeMinor,
			&i.RefundedMinor,
			&i.FxQuote,
			&i.Note,
			&i.ProofObjectKey,
			&i.RecordedBy,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVirtualAccounts = `-- name: ListVirtualAccounts :many
SELECT id, org_id, provider, account_number, bank_name, account_name, provider_ref, created_at FROM virtual_accounts WHERE org_id = $1 ORDER BY created_at
`

// tenant: org - the org's transfer accounts.
func (q *Queries) ListVirtualAccounts(ctx context.Context, orgID uuid.UUID) ([]VirtualAccount, error) {
	rows, err := q.db.Query(ctx, listVirtualAccounts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VirtualAccount
	for rows.Next() {
		var i VirtualAccount
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.AccountNumber,
			&i.BankName,
			&i.AccountName,
			&i.ProviderRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPayment = `-- name: LockPayment :one
SELECT id, org_id, provider, channel, provider_ref, reference, amount_minor, fee_minor, refunded_minor, fx_quote, note, proof_object_key, recorded_by, received_at, created_at FROM payments WHERE id = $1 FOR UPDATE
`

// tenant: system - a payment for a refund.
func (q *Queries) LockPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Channel,
		&i.ProviderRef,
		&i.Reference,
		&i.AmountMinor,
		&i.FeeMinor,
		&i.RefundedMinor,
		&i.FxQuote,
		&i.Note,
		&i.ProofObjectKey,
		&i.RecordedBy,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const openInvoices = `-- name: OpenInvoices :many
SELECT id, org_id, number, period_start, period_end, status, held, hold_reason, subtotal_minor, vat_minor, total_minor, wht_expected_minor, vat_rate, bill_to, seller, due_at, issued_at, paid_at, pdf_object_key, price_book_version, created_at, paid_minor, wht_deducted_minor, wht_evidenced_at FROM invoices WHERE org_id = $1 AND status IN ('issued', 'partially_paid') AND total_minor > 0
ORDER BY issued_at, number FOR UPDATE
`

// tenant: system - an org's unpaid invoices, oldest first, locked for settling.
func (q *Queries) OpenInvoices(ctx context.Context, orgID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, openInvoices, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Number,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Held,
			&i.HoldReason,
			&i.SubtotalMinor,
			&i.VatMinor,
			&i.TotalMinor,
			&i.WhtExpectedMinor,
			&i.VatRate,
			&i.BillTo,
			&i.Seller,
			&i.DueAt,
			&i.IssuedAt,
			&i.PaidAt,
			&i.PdfObjectKey,
			&i.PriceBookVersion,
			&i.CreatedAt,
			&i.PaidMinor,
			&i.WhtDeductedMinor,
			&i.WhtEvidencedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgDunningSteps = `-- name: OrgDunningSteps :many
SELECT id, org_id, cycle, step, detail, taken_at FROM dunning_steps WHERE org_id = $1 AND cycle = $2 ORDER BY taken_at
`

type OrgDunningStepsParams struct {
	OrgID uuid.UUID
	Cycle time.Time
}

// tenant: system - an org's steps in a cycle.
func (q *Queries) OrgDunningSteps(ctx context.Context, arg OrgDunningStepsParams) ([]DunningStep, error) {
	rows, err := q.db.Query(ctx, orgDunningSteps, arg.OrgID, arg.Cycle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DunningStep
	for rows.Next() {
		var i DunningStep
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Cycle,
			&i.Step,
			&i.Detail,
			&i.TakenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgOverdueSince = `-- name: OrgOverdueSince :one
SELECT due_at FROM invoices WHERE org_id = $1 AND status IN ('issued', 'partially_paid') AND total_minor > 0 AND due_at < $2::timestamptz
ORDER BY due_at LIMIT 1
`

type OrgOverdueSinceParams struct {
	OrgID uuid.UUID
	At    time.Time
}

// tenant: system - when an org's oldest unpaid invoice fell due.
func (q *Queries) OrgOverdueSince(ctx context.Context, arg OrgOverdueSinceParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, orgOverdueSince, arg.OrgID, arg.At)
	var due_at *time.Time
	err := row.Scan(&due_at)
	return due_at, err
}

const outstandingWHT = `-- name: OutstandingWHT :many
SELECT i.id, i.org_id, i.number, i.period_start, i.period_end, i.status, i.held, i.hold_reason, i.subtotal_minor, i.vat_minor, i.total_minor, i.wht_expected_minor, i.vat_rate, i.bill_to, i.seller, i.due_at, i.issued_at, i.paid_at, i.pdf_object_key, i.price_book_version, i.created_at, i.paid_minor, i.wht_deducted_minor, i.wht_evidenced_at, o.name AS org_name, b.tin FROM invoices i JOIN organizations o ON o.id = i.org_id
LEFT JOIN billing_accounts b ON b.org_id = i.org_id
WHERE i.wht_deducted_minor > 0 AND i.wht_evidenced_at IS NULL ORDER BY i.paid_at
`

type OutstandingWHTRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Number           *string
	PeriodStart      pgtype.Date
	PeriodEnd        pgtype.Date
	Status           string
	Held             bool
	HoldReason       *string
	SubtotalMinor    int64
	VatMinor         int64
	TotalMinor       int64
	WhtExpectedMinor int64
	VatRate          pgtype.Numeric
	BillTo           json.RawMessage
	Seller           json.RawMessage
	DueAt            *time.Time
	IssuedAt         *time.Time
	PaidAt           *time.Time
	PdfObjectKey     *string
	PriceBookVersion int32
	CreatedAt        time.Time
	PaidMinor        int64
	WhtDeductedMinor int64
	WhtEvidencedAt   *time.Time
	OrgName          string
	Tin              *string
}

// tenant: system - deducted WHT awaiting its credit note, oldest first.
func (q *Queries) OutstandingWHT(ctx context.Context) ([]OutstandingWHTRow, error) {
	rows, err := q.db.Query(ctx, outstandingWHT)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutstandingWHTRow
	for rows.Next() {
		var i OutstandingWHTRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Number,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Held,
			&i.HoldReason,
			&i.SubtotalMinor,
			&i.VatMinor,
			&i.TotalMinor,
			&i.WhtExpectedMinor,
			&i.VatRate,
			&i.BillTo,
			&i.Seller,
			&i.DueAt,
			&i.IssuedAt,
			&i.PaidAt,
			&i.PdfObjectKey,
			&i.PriceBookVersion,
			&i.CreatedAt,
			&i.PaidMinor,
			&i.WhtDeductedMinor,
			&i.WhtEvidencedAt,
			&i.OrgName,
			&i.Tin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overdueInvoices = `-- name: OverdueInvoices :many
SELECT id, org_id, number, period_start, period_end, status, held, hold_reason, subtotal_minor, vat_minor, total_minor, wht_expected_minor, vat_rate, bill_to, seller, due_at, issued_at, paid_at, pdf_object_key, price_book_version, created_at, paid_minor, wht_deducted_minor, wht_evidenced_at FROM invoices WHERE status IN ('issued', 'partially_paid') AND total_minor > 0 AND due_at < $1::timestamptz ORDER BY due_at
`

// tenant: system - unpaid invoices past due, for dunning.
func (q *Queries) OverdueInvoices(ctx context.Context, at time.Time) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, overdueInvoices, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Number,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Held,
			&i.HoldReason,
			&i.SubtotalMinor,
			&i.VatMinor,
			&i.TotalMinor,
			&i.WhtExpectedMinor,
			&i.VatRate,
			&i.BillTo,
			&i.Seller,
			&i.DueAt,
			&i.IssuedAt,
			&i.PaidAt,
			&i.PdfObjectKey,
			&i.PriceBookVersion,
			&i.CreatedAt,
			&i.PaidMinor,
			&i.WhtDeductedMinor,
			&i.WhtEvidencedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentAllocations = `-- name: PaymentAllocations :many
SELECT a.payment_id, a.invoice_id, a.amount_minor, a.wht_minor, i.number FROM payment_allocations a JOIN invoices i ON i.id = a.invoice_id WHERE a.payment_id = $1
`

type PaymentAllocationsRow struct {
	PaymentID   uuid.UUID
	InvoiceID   uuid.UUID
	AmountMinor int64
	WhtMinor    int64
	Number      *string
}

// tenant: system - what a payment settled.
func (q *Queries) PaymentAllocations(ctx context.Context, paymentID uuid.UUID) ([]PaymentAllocationsRow, error) {
	rows, err := q.db.Query(ctx, paymentAllocations, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAllocationsRow
	for rows.Next() {
		var i PaymentAllocationsRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.InvoiceID,
			&i.AmountMinor,
			&i.WhtMinor,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentAllocationsForUpdate = `-- name: PaymentAllocationsForUpdate :many
SELECT a.payment_id, a.invoice_id, a.amount_minor, a.wht_minor FROM payment_allocations a JOIN invoices i ON i.id = a.invoice_id
WHERE a.payment_id = $1 AND a.amount_minor > 0 AND i.status <> 'void'
ORDER BY i.issued_at DESC, i.number DESC FOR UPDATE OF a, i
`

// tenant: system - what a payment settled, newest invoice first, locked for a refund.
func (q *Queries) PaymentAllocationsForUpdate(ctx context.Context, paymentID uuid.UUID) ([]PaymentAllocation, error) {
	rows, err := q.db.Query(ctx, paymentAllocationsForUpdate, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAllocation
	for rows.Next() {
		var i PaymentAllocation
		if err := rows.Scan(
			&i.PaymentID,
			&i.InvoiceID,
			&i.AmountMinor,
			&i.WhtMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentRefunds = `-- name: PaymentRefunds :many
SELECT id, payment_id, amount_minor, reason, provider_ref, status, error, created_by, created_at, completed_at FROM refunds WHERE payment_id = $1 ORDER BY created_at
`

// tenant: system - a payment's refunds.
func (q *Queries) PaymentRefunds(ctx context.Context, paymentID uuid.UUID) ([]Refund, error) {
	rows, err := q.db.Query(ctx, paymentRefunds, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Refund
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.AmountMinor,
			&i.Reason,
			&i.ProviderRef,
			&i.Status,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingIntents = `-- name: PendingIntents :many
SELECT id, org_id, reference, provider, channel, purpose, invoice_id, method_id, amount_minor, status, checkout_url, automatic, error, created_at, completed_at FROM payment_intents WHERE status = 'pending' AND created_at > $1 ORDER BY created_at
`

// tenant: system - checkouts and charges still open, for re-querying.
func (q *Queries) PendingIntents(ctx context.Context, since time.Time) ([]PaymentIntent, error) {
	rows, err := q.db.Query(ctx, pendingIntents, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentIntent
	for rows.Next() {
		var i PaymentIntent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Reference,
			&i.Provider,
			&i.Channel,
			&i.Purpose,
			&i.InvoiceID,
			&i.MethodID,
			&i.AmountMinor,
			&i.Status,
			&i.CheckoutUrl,
			&i.Automatic,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prepaidDeducted = `-- name: PrepaidDeducted :many

SELECT account, amount_minor FROM prepaid_deductions WHERE org_id = $1 AND month = $2
`

type PrepaidDeductedParams struct {
	OrgID uuid.UUID
	Month pgtype.Date
}

type PrepaidDeductedRow struct {
	Account     string
	AmountMinor int64
}

// ---- Prepaid -----------------------------------------------------------------
// tenant: system - a prepaid org's deductions for a month, per account.
func (q *Queries) PrepaidDeducted(ctx context.Context, arg PrepaidDeductedParams) ([]PrepaidDeductedRow, error) {
	rows, err := q.db.Query(ctx, prepaidDeducted, arg.OrgID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrepaidDeductedRow
	for rows.Next() {
		var i PrepaidDeductedRow
		if err := rows.Scan(&i.Account, &i.AmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAutoTopup = `-- name: RecentAutoTopup :one
SELECT EXISTS (SELECT 1 FROM payment_intents WHERE org_id = $1 AND automatic AND purpose = 'topup' AND created_at > $2)::bool
`

type RecentAutoTopupParams struct {
	OrgID uuid.UUID
	Since time.Time
}

// tenant: system - whether an org was auto-topped-up recently.
func (q *Queries) RecentAutoTopup(ctx context.Context, arg RecentAutoTopupParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentAutoTopup, arg.OrgID, arg.Since)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const reopenInvoice = `-- name: ReopenInvoice :one
UPDATE invoices SET paid_minor = paid_minor - $1,
  status = CASE WHEN paid_minor - $1 = 0 AND wht_deducted_minor = 0 THEN 'issued' ELSE 'partially_paid' END,
  paid_at = NULL
WHERE id = $2 RETURNING id, org_id, number, period_start, period_end, status, held, hold_reason, subtotal_minor, vat_minor, total_minor, wht_expected_minor, vat_rate, bill_to, seller, due_at, issued_at, paid_at, pdf_object_key, price_book_version, created_at, paid_minor, wht_deducted_minor, wht_evidenced_at
`

type ReopenInvoiceParams struct {
	AmountMinor int64
	ID          uuid.UUID
}

// tenant: system - an invoice owed again after a refund of what paid it.
func (q *Queries) ReopenInvoice(ctx context.Context, arg ReopenInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, reopenInvoice, arg.AmountMinor, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Number,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Held,
		&i.HoldReason,
		&i.SubtotalMinor,
		&i.VatMinor,
		&i.TotalMinor,
		&i.WhtExpectedMinor,
		&i.VatRate,
		&i.BillTo,
		&i.Seller,
		&i.DueAt,
		&i.IssuedAt,
		&i.PaidAt,
		&i.PdfObjectKey,
		&i.PriceBookVersion,
		&i.CreatedAt,
		&i.PaidMinor,
		&i.WhtDeductedMinor,
		&i.WhtEvidencedAt,
	)
	return i, err
}

const revokeMandateByRef = `-- name: RevokeMandateByRef :one
UPDATE payment_methods SET status = 'revoked', is_default = false WHERE provider = $1 AND provider_ref = $2 AND kind = 'mandate'
RETURNING id, org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default, status, reminded_days, created_at
`

type RevokeMandateByRefParams struct {
	Provider    string
	ProviderRef *string
}

// tenant: system - a mandate.revoked event.
func (q *Queries) RevokeMandateByRef(ctx context.Context, arg RevokeMandateByRefParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, revokeMandateByRef, arg.Provider, arg.ProviderRef)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.TokenSealed,
		&i.ProviderRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.LimitMinor,
		&i.IsDefault,
		&i.Status,
		&i.RemindedDays,
		&i.CreatedAt,
	)
	return i, err
}

const setAutoTopup = `-- name: SetAutoTopup :exec
UPDATE billing_accounts SET auto_topup = $1, updated_at = now() WHERE org_id = $2
`

type SetAutoTopupParams struct {
	AutoTopup []byte
	OrgID     uuid.UUID
}

// tenant: system - an org's auto top-up (top up amount when below threshold).
func (q *Queries) SetAutoTopup(ctx context.Context, arg SetAutoTopupParams) error {
	_, err := q.db.Exec(ctx, setAutoTopup, arg.AutoTopup, arg.OrgID)
	return err
}

const setBalanceAlert = `-- name: SetBalanceAlert :exec
UPDATE billing_accounts SET balance_alerted = $1, balance_month = $2, zero_balance_at = $3
WHERE org_id = $4
`

type SetBalanceAlertParams struct {
	BalanceAlerted int32
	BalanceMonth   pgtype.Date
	ZeroBalanceAt  *time.Time
	OrgID          uuid.UUID
}

// tenant: system - prepaid alert state.
func (q *Queries) SetBalanceAlert(ctx context.Context, arg SetBalanceAlertParams) error {
	_, err := q.db.Exec(ctx, setBalanceAlert,
		arg.BalanceAlerted,
		arg.BalanceMonth,
		arg.ZeroBalanceAt,
		arg.OrgID,
	)
	return err
}

const setCardFailing = `-- name: SetCardFailing :exec
UPDATE billing_accounts SET card_failing_since = $1 WHERE org_id = $2
`

type SetCardFailingParams struct {
	CardFailingSince *time.Time
	OrgID            uuid.UUID
}

// tenant: system - when automatic card charges started failing.
func (q *Queries) SetCardFailing(ctx context.Context, arg SetCardFailingParams) error {
	_, err := q.db.Exec(ctx, setCardFailing, arg.CardFailingSince, arg.OrgID)
	return err
}

const setCardReminded = `-- name: SetCardReminded :exec
UPDATE payment_methods SET reminded_days = $1 WHERE id = $2
`

type SetCardRemindedParams struct {
	Days int32
	ID   uuid.UUID
}

// tenant: system - an expiry reminder was sent.
func (q *Queries) SetCardReminded(ctx context.Context, arg SetCardRemindedParams) error {
	_, err := q.db.Exec(ctx, setCardReminded, arg.Days, arg.ID)
	return err
}

const setDefaultPaymentMethod = `-- name: SetDefaultPaymentMethod :exec
UPDATE payment_methods SET is_default = (id = $1) WHERE org_id = $2 AND status = 'active'
`

type SetDefaultPaymentMethodParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// tenant: org - choose the default method.
func (q *Queries) SetDefaultPaymentMethod(ctx context.Context, arg SetDefaultPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, setDefaultPaymentMethod, arg.ID, arg.OrgID)
	return err
}

const setDunning = `-- name: SetDunning :exec
UPDATE billing_accounts SET dunning_state = $1, dunning_since = $2,
  deletion_scheduled_at = $3, updated_at = now()
WHERE org_id = $4
`

type SetDunningParams struct {
	DunningState        string
	DunningSince        *time.Time
	DeletionScheduledAt *time.Time
	OrgID               uuid.UUID
}

// tenant: system - an org's dunning state.
func (q *Queries) SetDunning(ctx context.Context, arg SetDunningParams) error {
	_, err := q.db.Exec(ctx, setDunning,
		arg.DunningState,
		arg.DunningSince,
		arg.DeletionScheduledAt,
		arg.OrgID,
	)
	return err
}

const setGrace = `-- name: SetGrace :exec
UPDATE billing_accounts SET grace_until = $1, updated_at = now() WHERE org_id = $2
`

type SetGraceParams struct {
	GraceUntil *time.Time
	OrgID      uuid.UUID
}

// tenant: system - the admin extends an org's grace.
func (q *Queries) SetGrace(ctx context.Context, arg SetGraceParams) error {
	_, err := q.db.Exec(ctx, setGrace, arg.GraceUntil, arg.OrgID)
	return err
}

const setIntentCheckout = `-- name: SetIntentCheckout :exec
UPDATE payment_intents SET checkout_url = $1 WHERE id = $2
`

type SetIntentCheckoutParams struct {
	CheckoutUrl *string
	ID          uuid.UUID
}

// tenant: system - the provider's hosted page for an intent.
func (q *Queries) SetIntentCheckout(ctx context.Context, arg SetIntentCheckoutParams) error {
	_, err := q.db.Exec(ctx, setIntentCheckout, arg.CheckoutUrl, arg.ID)
	return err
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :exec
UPDATE invoices SET status = $1, paid_at = CASE WHEN $1 = 'paid' THEN coalesce(paid_at, now()) ELSE paid_at END
WHERE id = $2
`

type SetInvoiceStatusParams struct {
	Status string
	ID     uuid.UUID
}

// tenant: system - an invoice's status after a credit note or evidence.
func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, setInvoiceStatus, arg.Status, arg.ID)
	return err
}

const setPaymentMethodStatus = `-- name: SetPaymentMethodStatus :exec
UPDATE payment_methods SET status = $1, is_default = false WHERE id = $2
`

type SetPaymentMethodStatusParams struct {
	Status string
	ID     uuid.UUID
}

// tenant: system - a method removed, revoked or expired.
func (q *Queries) SetPaymentMethodStatus(ctx context.Context, arg SetPaymentMethodStatusParams) error {
	_, err := q.db.Exec(ctx, setPaymentMethodStatus, arg.Status, arg.ID)
	return err
}

const setProviderCustomer = `-- name: SetProviderCustomer :exec
UPDATE billing_accounts SET provider_customers = provider_customers || jsonb_build_object($1::text, $2::text), updated_at = now()
WHERE org_id = $3
`

type SetProviderCustomerParams struct {
	Provider   string
	CustomerID string
	OrgID      uuid.UUID
}

// tenant: system - an org's customer id at a provider.
func (q *Queries) SetProviderCustomer(ctx context.Context, arg SetProviderCustomerParams) error {
	_, err := q.db.Exec(ctx, setProviderCustomer, arg.Provider, arg.CustomerID, arg.OrgID)
	return err
}

const setWHTEvidenced = `-- name: SetWHTEvidenced :one
UPDATE invoices SET wht_evidenced_at = now(), status = CASE WHEN status = 'paid_wht_pending' THEN 'paid' ELSE status END
WHERE id = $1 AND wht_deducted_minor > 0 RETURNING id, org_id, number, period_start, period_end, status, held, hold_reason, subtotal_minor, vat_minor, total_minor, wht_expected_minor, vat_rate, bill_to, seller, due_at, issued_at, paid_at, pdf_object_key, price_book_version, created_at, paid_minor, wht_deducted_minor, wht_evidenced_at
`

// tenant: system - the WHT on an invoice is evidenced.
func (q *Queries) SetWHTEvidenced(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, setWHTEvidenced, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Number,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Held,
		&i.HoldReason,
		&i.SubtotalMinor,
		&i.VatMinor,
		&i.TotalMinor,
		&i.WhtExpectedMinor,
		&i.VatRate,
		&i.BillTo,
		&i.Seller,
		&i.DueAt,
		&i.IssuedAt,
		&i.PaidAt,
		&i.PdfObjectKey,
		&i.PriceBookVersion,
		&i.CreatedAt,
		&i.PaidMinor,
		&i.WhtDeductedMinor,
		&i.WhtEvidencedAt,
	)
	return i, err
}

const settleInvoice = `-- name: SettleInvoice :one
UPDATE invoices SET paid_minor = paid_minor + $1, wht_deducted_minor = wht_deducted_minor + $2,
  status = $3, paid_at = CASE WHEN $3 IN ('paid', 'paid_wht_pending') THEN coalesce(paid_at, now()) ELSE paid_at END
WHERE id = $4 RETURNING id, org_id, number, period_start, period_end, status, held, hold_reason, subtotal_minor, vat_minor, total_minor, wht_expected_minor, vat_rate, bill_to, seller, due_at, issued_at, paid_at, pdf_object_key, price_book_version, created_at, paid_minor, wht_deducted_minor, wht_evidenced_at
`

type SettleInvoiceParams struct {
	PaidMinor int64
	WhtMinor  int64
	Status    string
	ID        uuid.UUID
}

// tenant: system - a payment (or credit) applied to an invoice.
func (q *Queries) SettleInvoice(ctx context.Context, arg SettleInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, settleInvoice,
		arg.PaidMinor,
		arg.WhtMinor,
		arg.Status,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Number,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Held,
		&i.HoldReason,
		&i.SubtotalMinor,
		&i.VatMinor,
		&i.TotalMinor,
		&i.WhtExpectedMinor,
		&i.VatRate,
		&i.BillTo,
		&i.Seller,
		&i.DueAt,
		&i.IssuedAt,
		&i.PaidAt,
		&i.PdfObjectKey,
		&i.PriceBookVersion,
		&i.CreatedAt,
		&i.PaidMinor,
		&i.WhtDeductedMinor,
		&i.WhtEvidencedAt,
	)
	return i, err
}

const unapplyAllocation = `-- name: UnapplyAllocation :exec
UPDATE payment_allocations SET amount_minor = amount_minor - $1
WHERE payment_id = $2 AND invoice_id = $3
`

type UnapplyAllocationParams struct {
	AmountMinor int64
	PaymentID   uuid.UUID
	InvoiceID   uuid.UUID
}

// tenant: system - part of a payment taken back off an invoice for a refund.
func (q *Queries) UnapplyAllocation(ctx context.Context, arg UnapplyAllocationParams) error {
	_, err := q.db.Exec(ctx, unapplyAllocation, arg.AmountMinor, arg.PaymentID, arg.InvoiceID)
	return err
}

const uninvoicedPrepaidMonths = `-- name: UninvoicedPrepaidMonths :many
SELECT d.month FROM prepaid_deductions d
WHERE d.org_id = $1 AND NOT EXISTS (
  SELECT 1 FROM invoices i WHERE i.org_id = d.org_id AND i.period_start = d.month AND i.status <> 'draft')
GROUP BY d.month HAVING bool_or(d.amount_minor <> 0) ORDER BY d.month
`

// tenant: system - months of a prepaid org's deductions its invoice hasn't trued up yet.
func (q *Queries) UninvoicedPrepaidMonths(ctx context.Context, orgID uuid.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, uninvoicedPrepaidMonths, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var month pgtype.Date
		if err := rows.Scan(&month); err != nil {
			return nil, err
		}
		items = append(items, month)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unmatchedPaymentEvents = `-- name: UnmatchedPaymentEvents :many
SELECT id, provider, provider_event_id, kind, org_id, reference, provider_ref, amount_minor, currency, payload, received_at, processed_at, outcome, error FROM payment_events WHERE outcome = 'unmatched' ORDER BY id DESC LIMIT 200
`

// tenant: system - verified money that couldn't be attributed to an org.
func (q *Queries) UnmatchedPaymentEvents(ctx context.Context) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, unmatchedPaymentEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderEventID,
			&i.Kind,
			&i.OrgID,
			&i.Reference,
			&i.ProviderRef,
			&i.AmountMinor,
			&i.Currency,
			&i.Payload,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Outcome,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPaymentMethod = `-- name: UpsertPaymentMethod :one

INSERT INTO payment_methods (org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        NOT EXISTS (SELECT 1 FROM payment_methods WHERE org_id = $1 AND is_default AND status = 'active'))
ON CONFLICT (provider, provider_ref) DO UPDATE SET status = 'active', token_sealed = coalesce(EXCLUDED.token_sealed, payment_methods.token_sealed),
  exp_month = EXCLUDED.exp_month, exp_year = EXCLUDED.exp_year, limit_minor = EXCLUDED.limit_minor
RETURNING id, org_id, provider, kind, token_sealed, provider_ref, brand, last4, exp_month, exp_year, limit_minor, is_default, status, reminded_days, created_at
`

type UpsertPaymentMethodParams struct {
	OrgID       uuid.UUID
	Provider    string
	Kind        string
	TokenSealed []byte
	ProviderRef *string
	Brand       *string
	Last4       *string
	ExpMonth    *int32
	ExpYear     *int32
	LimitMinor  *int64
}

// ---- Payment methods ---------------------------------------------------------
// tenant: system - a saved card or mandate of an org the caller resolved.
func (q *Queries) UpsertPaymentMethod(ctx context.Context, arg UpsertPaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, upsertPaymentMethod,
		arg.OrgID,
		arg.Provider,
		arg.Kind,
		arg.TokenSealed,
		arg.ProviderRef,
		arg.Brand,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.LimitMinor,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.TokenSealed,
		&i.ProviderRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.LimitMinor,
		&i.IsDefault,
		&i.Status,
		&i.RemindedDays,
		&i.CreatedAt,
	)
	return i, err
}

const virtualAccountByNumber = `-- name: VirtualAccountByNumber :one
SELECT id, org_id, provider, account_number, bank_name, account_name, provider_ref, created_at FROM virtual_accounts WHERE provider = $1 AND (account_number = $2 OR provider_ref = $2)
LIMIT 1
`

type VirtualAccountByNumberParams struct {
	Provider      string
	AccountNumber string
}

// tenant: system - attributing a transfer, by the account's number or the
// provider's reference for it.
func (q *Queries) VirtualAccountByNumber(ctx context.Context, arg VirtualAccountByNumberParams) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, virtualAccountByNumber, arg.Provider, arg.AccountNumber)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.ProviderRef,
		&i.CreatedAt,
	)
	return i, err
}

const wHTDeducted = `-- name: WHTDeducted :many
SELECT i.id, i.org_id, i.number, i.period_start, i.period_end, i.status, i.held, i.hold_reason, i.subtotal_minor, i.vat_minor, i.total_minor, i.wht_expected_minor, i.vat_rate, i.bill_to, i.seller, i.due_at, i.issued_at, i.paid_at, i.pdf_object_key, i.price_book_version, i.created_at, i.paid_minor, i.wht_deducted_minor, i.wht_evidenced_at, o.name AS org_name, b.legal_name, b.tin FROM invoices i JOIN organizations o ON o.id = i.org_id
LEFT JOIN billing_accounts b ON b.org_id = i.org_id
WHERE i.wht_deducted_minor > 0 ORDER BY i.paid_at
`

type WHTDeductedRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Number           *string
	PeriodStart      pgtype.Date
	PeriodEnd        pgtype.Date
	Status           string
	Held             bool
	HoldReason       *string
	SubtotalMinor    int64
	VatMinor         int64
	TotalMinor       int64
	WhtExpectedMinor int64
	VatRate          pgtype.Numeric
	BillTo           json.RawMessage
	Seller           json.RawMessage
	DueAt            *time.Time
	IssuedAt         *time.Time
	PaidAt           *time.Time
	PdfObjectKey     *string
	PriceBookVersion int32
	CreatedAt        time.Time
	PaidMinor        int64
	WhtDeductedMinor int64
	WhtEvidencedAt   *time.Time
	OrgName          string
	LegalName        *string
	Tin              *string
}

// tenant: system - every invoice with WHT deducted, for the tax export.
func (q *Queries) WHTDeducted(ctx context.Context) ([]WHTDeductedRow, error) {
	rows, err := q.db.Query(ctx, wHTDeducted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WHTDeductedRow
	for rows.Next() {
		var i WHTDeductedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Number,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Held,
			&i.HoldReason,
			&i.SubtotalMinor,
			&i.VatMinor,
			&i.TotalMinor,
			&i.WhtExpectedMinor,
			&i.VatRate,
			&i.BillTo,
			&i.Seller,
			&i.DueAt,
			&i.IssuedAt,
			&i.PaidAt,
			&i.PdfObjectKey,
			&i.PriceBookVersion,
			&i.CreatedAt,
			&i.PaidMinor,
			&i.WhtDeductedMinor,
			&i.WhtEvidencedAt,
			&i.OrgName,
			&i.LegalName,
			&i.Tin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
