// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pooler.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const advancePoolerGeneration = `-- name: AdvancePoolerGeneration :one
INSERT INTO pooler_generations (region, generation, hash) VALUES ($1, 1, $2)
ON CONFLICT (region) DO UPDATE
  SET generation = pooler_generations.generation + CASE WHEN pooler_generations.hash = EXCLUDED.hash THEN 0 ELSE 1 END,
      hash = EXCLUDED.hash,
      updated_at = CASE WHEN pooler_generations.hash = EXCLUDED.hash THEN pooler_generations.updated_at ELSE now() END
RETURNING region, generation, hash, updated_at
`

type AdvancePoolerGenerationParams struct {
	Region string
	Hash   string
}

// Records a region's rendered configuration's hash, moving to the next
// generation only when the content changed.
func (q *Queries) AdvancePoolerGeneration(ctx context.Context, arg AdvancePoolerGenerationParams) (PoolerGeneration, error) {
	row := q.db.QueryRow(ctx, advancePoolerGeneration, arg.Region, arg.Hash)
	var i PoolerGeneration
	err := row.Scan(
		&i.Region,
		&i.Generation,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolerGeneration = `-- name: GetPoolerGeneration :one
SELECT region, generation, hash, updated_at FROM pooler_generations WHERE region = $1
`

func (q *Queries) GetPoolerGeneration(ctx context.Context, region string) (PoolerGeneration, error) {
	row := q.db.QueryRow(ctx, getPoolerGeneration, region)
	var i PoolerGeneration
	err := row.Scan(
		&i.Region,
		&i.Generation,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPoolerEvent = `-- name: InsertPoolerEvent :exec
INSERT INTO pooler_events (node_id, kind, detail) VALUES ($1, $2, $3)
`

type InsertPoolerEventParams struct {
	NodeID *uuid.UUID
	Kind   string
	Detail json.RawMessage
}

func (q *Queries) InsertPoolerEvent(ctx context.Context, arg InsertPoolerEventParams) error {
	_, err := q.db.Exec(ctx, insertPoolerEvent, arg.NodeID, arg.Kind, arg.Detail)
	return err
}

const listPoolerEvents = `-- name: ListPoolerEvents :many
SELECT e.id, e.node_id, e.kind, e.detail, e.occurred_at, n.name AS node_name FROM pooler_events e
LEFT JOIN nodes n ON n.id = e.node_id
ORDER BY e.occurred_at DESC LIMIT $1
`

type ListPoolerEventsRow struct {
	ID         int64
	NodeID     *uuid.UUID
	Kind       string
	Detail     json.RawMessage
	OccurredAt time.Time
	NodeName   *string
}

func (q *Queries) ListPoolerEvents(ctx context.Context, lim int32) ([]ListPoolerEventsRow, error) {
	rows, err := q.db.Query(ctx, listPoolerEvents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolerEventsRow
	for rows.Next() {
		var i ListPoolerEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.Detail,
			&i.OccurredAt,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const poolerHosts = `-- name: PoolerHosts :many
SELECT id, name, private_addr, agent_port, role, agent_cert_fp, pg_admin_secret, capacity, status, last_heartbeat, created_at, agent_host, agent_version, registration_token, registration_expires_at, last_reachable_at, provider_server_id, pooler_generation, pooler_hash, pooler_vrrp_state, pooler_ready, pooler_checked_at, provider, region, server_type, monthly_cost_minor, cost_currency, lifecycle, empty_since, keep, failure_domain, placement_group FROM nodes
WHERE role = 'pooler' AND status <> 'removed' AND agent_cert_fp IS NOT NULL
ORDER BY name
`

// Registered pooler hosts (V3 §2.1), in a stable order.
func (q *Queries) PoolerHosts(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, poolerHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrivateAddr,
			&i.AgentPort,
			&i.Role,
			&i.AgentCertFp,
			&i.PgAdminSecret,
			&i.Capacity,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.AgentHost,
			&i.AgentVersion,
			&i.RegistrationToken,
			&i.RegistrationExpiresAt,
			&i.LastReachableAt,
			&i.ProviderServerID,
			&i.PoolerGeneration,
			&i.PoolerHash,
			&i.PoolerVrrpState,
			&i.PoolerReady,
			&i.PoolerCheckedAt,
			&i.Provider,
			&i.Region,
			&i.ServerType,
			&i.MonthlyCostMinor,
			&i.CostCurrency,
			&i.Lifecycle,
			&i.EmptySince,
			&i.Keep,
			&i.FailureDomain,
			&i.PlacementGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPoolerHostState = `-- name: RecordPoolerHostState :exec
UPDATE nodes SET pooler_generation = $1, pooler_hash = $2,
  pooler_vrrp_state = $3, pooler_ready = $4, pooler_checked_at = now()
WHERE id = $5
`

type RecordPoolerHostStateParams struct {
	PoolerGeneration *int64
	PoolerHash       *string
	PoolerVrrpState  *string
	PoolerReady      *bool
	ID               uuid.UUID
}

func (q *Queries) RecordPoolerHostState(ctx context.Context, arg RecordPoolerHostStateParams) error {
	_, err := q.db.Exec(ctx, recordPoolerHostState,
		arg.PoolerGeneration,
		arg.PoolerHash,
		arg.PoolerVrrpState,
		arg.PoolerReady,
		arg.ID,
	)
	return err
}

const setProviderServerID = `-- name: SetProviderServerID :exec
UPDATE nodes SET provider_server_id = $1 WHERE id = $2
`

type SetProviderServerIDParams struct {
	ProviderServerID *string
	ID               uuid.UUID
}

func (q *Queries) SetProviderServerID(ctx context.Context, arg SetProviderServerIDParams) error {
	_, err := q.db.Exec(ctx, setProviderServerID, arg.ProviderServerID, arg.ID)
	return err
}
