// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_auth.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimAuthEmails = `-- name: ClaimAuthEmails :many
UPDATE auth_message_outbox SET next_attempt_at = now() + make_interval(secs => $1::int)
WHERE id IN (SELECT o.id FROM auth_message_outbox o
  WHERE o.sent_at IS NULL AND o.message_enc IS NOT NULL AND o.next_attempt_at <= now()
  ORDER BY o.next_attempt_at LIMIT $2 FOR UPDATE SKIP LOCKED)
RETURNING id, project_id, kind, via, message_enc, attempts, next_attempt_at, last_error, created_at, sent_at, channel, recipient_hash, country
`

type ClaimAuthEmailsParams struct {
	LeaseSecs int32
	Lim       int32
}

// tenant: system - the auth email sender across all projects: due messages,
// leased for lease_secs so no other sender takes them while they're sent.
func (q *Queries) ClaimAuthEmails(ctx context.Context, arg ClaimAuthEmailsParams) ([]AuthMessageOutbox, error) {
	rows, err := q.db.Query(ctx, claimAuthEmails, arg.LeaseSecs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthMessageOutbox
	for rows.Next() {
		var i AuthMessageOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Via,
			&i.MessageEnc,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
			&i.Channel,
			&i.RecipientHash,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimAuthHooks = `-- name: ClaimAuthHooks :many
UPDATE auth_hook_outbox SET next_attempt_at = now() + make_interval(secs => $1::int)
WHERE id IN (SELECT o.id FROM auth_hook_outbox o
  WHERE o.delivered_at IS NULL AND o.failed_at IS NULL AND o.next_attempt_at <= now()
  ORDER BY o.next_attempt_at LIMIT $2 FOR UPDATE SKIP LOCKED)
RETURNING id, project_id, event, payload, attempts, next_attempt_at, last_error, last_status, created_at, delivered_at, failed_at
`

type ClaimAuthHooksParams struct {
	LeaseSecs int32
	Lim       int32
}

// tenant: system - the auth hook sender across all projects: due events,
// leased for lease_secs so no other sender takes them while they're sent.
func (q *Queries) ClaimAuthHooks(ctx context.Context, arg ClaimAuthHooksParams) ([]AuthHookOutbox, error) {
	rows, err := q.db.Query(ctx, claimAuthHooks, arg.LeaseSecs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthHookOutbox
	for rows.Next() {
		var i AuthHookOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Event,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.LastStatus,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPhoneMessages = `-- name: CountPhoneMessages :one
SELECT count(*) FROM auth_message_outbox WHERE project_id = $1 AND channel <> 'email' AND created_at > $2
`

type CountPhoneMessagesParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

// tenant: system - a project the caller resolved: SMS and WhatsApp codes since a time.
func (q *Queries) CountPhoneMessages(ctx context.Context, arg CountPhoneMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhoneMessages, arg.ProjectID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlatformAuthEmails = `-- name: CountPlatformAuthEmails :one
SELECT count(*) FROM auth_message_outbox WHERE project_id = $1 AND channel = 'email' AND via = 'platform' AND created_at > $2
`

type CountPlatformAuthEmailsParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

// tenant: system - a project the caller resolved.
func (q *Queries) CountPlatformAuthEmails(ctx context.Context, arg CountPlatformAuthEmailsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAuthEmails, arg.ProjectID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipientMessages = `-- name: CountRecipientMessages :one
SELECT count(*) FROM auth_message_outbox WHERE project_id = $1 AND recipient_hash = $2 AND created_at > $3
`

type CountRecipientMessagesParams struct {
	ProjectID     uuid.UUID
	RecipientHash *string
	Since         time.Time
}

// tenant: system - a project the caller resolved: codes to one number since a time.
func (q *Queries) CountRecipientMessages(ctx context.Context, arg CountRecipientMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipientMessages, arg.ProjectID, arg.RecipientHash, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const demoteActiveJWTKey = `-- name: DemoteActiveJWTKey :exec
UPDATE project_jwt_keys SET status = 'verifying', verify_until = $1
WHERE project_id = $2 AND status = 'active'
`

type DemoteActiveJWTKeyParams struct {
	VerifyUntil *time.Time
	ProjectID   uuid.UUID
}

// tenant: system - a project the request already authorized.
func (q *Queries) DemoteActiveJWTKey(ctx context.Context, arg DemoteActiveJWTKeyParams) error {
	_, err := q.db.Exec(ctx, demoteActiveJWTKey, arg.VerifyUntil, arg.ProjectID)
	return err
}

const edgeAuthConfigs = `-- name: EdgeAuthConfigs :many
SELECT project_id, config, providers_enc FROM project_auth_config WHERE project_id = ANY($1::uuid[])
`

type EdgeAuthConfigsRow struct {
	ProjectID    uuid.UUID
	Config       json.RawMessage
	ProvidersEnc []byte
}

// tenant: system - pgdock-edge's configuration feed: auth settings.
func (q *Queries) EdgeAuthConfigs(ctx context.Context, projectIds []uuid.UUID) ([]EdgeAuthConfigsRow, error) {
	rows, err := q.db.Query(ctx, edgeAuthConfigs, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgeAuthConfigsRow
	for rows.Next() {
		var i EdgeAuthConfigsRow
		if err := rows.Scan(&i.ProjectID, &i.Config, &i.ProvidersEnc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgeSigningKeys = `-- name: EdgeSigningKeys :many
SELECT project_id, id, kid, private_enc FROM project_jwt_keys
WHERE project_id = ANY($1::uuid[]) AND status = 'active'
`

type EdgeSigningKeysRow struct {
	ProjectID  uuid.UUID
	ID         uuid.UUID
	Kid        string
	PrivateEnc []byte
}

// tenant: system - pgdock-edge's configuration feed: the active signing keys.
func (q *Queries) EdgeSigningKeys(ctx context.Context, projectIds []uuid.UUID) ([]EdgeSigningKeysRow, error) {
	rows, err := q.db.Query(ctx, edgeSigningKeys, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgeSigningKeysRow
	for rows.Next() {
		var i EdgeSigningKeysRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Kid,
			&i.PrivateEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthConfig = `-- name: GetAuthConfig :one

SELECT project_id, config, providers_enc, templates, updated_at FROM project_auth_config WHERE project_id = $1
`

// Auth core (V4 §4, M31): settings, queued emails, sends, active users.
// tenant: system - a project the request already authorized.
func (q *Queries) GetAuthConfig(ctx context.Context, projectID uuid.UUID) (ProjectAuthConfig, error) {
	row := q.db.QueryRow(ctx, getAuthConfig, projectID)
	var i ProjectAuthConfig
	err := row.Scan(
		&i.ProjectID,
		&i.Config,
		&i.ProvidersEnc,
		&i.Templates,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActiveUser = `-- name: InsertActiveUser :execrows
INSERT INTO auth_mau (project_id, month, user_id) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertActiveUserParams struct {
	ProjectID uuid.UUID
	Month     pgtype.Date
	UserID    uuid.UUID
}

// tenant: system - pgdock-edge's report, for projects it serves.
func (q *Queries) InsertActiveUser(ctx context.Context, arg InsertActiveUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertActiveUser, arg.ProjectID, arg.Month, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuthAlert = `-- name: InsertAuthAlert :execrows
INSERT INTO auth_alerts (project_id, kind, day, details) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
`

type InsertAuthAlertParams struct {
	ProjectID uuid.UUID
	Kind      string
	Day       pgtype.Date
	Details   json.RawMessage
}

// tenant: system - a project the caller resolved: an alert, once a day per kind.
func (q *Queries) InsertAuthAlert(ctx context.Context, arg InsertAuthAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuthAlert,
		arg.ProjectID,
		arg.Kind,
		arg.Day,
		arg.Details,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuthHook = `-- name: InsertAuthHook :exec
INSERT INTO auth_hook_outbox (id, project_id, event, payload) VALUES ($1, $2, $3, $4)
`

type InsertAuthHookParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Event     string
	Payload   json.RawMessage
}

// tenant: system - a hook event pgdock-edge sent, for the project it named.
func (q *Queries) InsertAuthHook(ctx context.Context, arg InsertAuthHookParams) error {
	_, err := q.db.Exec(ctx, insertAuthHook,
		arg.ID,
		arg.ProjectID,
		arg.Event,
		arg.Payload,
	)
	return err
}

const insertAuthMessage = `-- name: InsertAuthMessage :exec
INSERT INTO auth_message_outbox (id, project_id, channel, kind, via, message_enc, recipient_hash, country)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuthMessageParams struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Channel       string
	Kind          string
	Via           string
	MessageEnc    []byte
	RecipientHash *string
	Country       *string
}

// tenant: system - a message pgdock-edge asked for, for the project it named.
func (q *Queries) InsertAuthMessage(ctx context.Context, arg InsertAuthMessageParams) error {
	_, err := q.db.Exec(ctx, insertAuthMessage,
		arg.ID,
		arg.ProjectID,
		arg.Channel,
		arg.Kind,
		arg.Via,
		arg.MessageEnc,
		arg.RecipientHash,
		arg.Country,
	)
	return err
}

const insertMessageSend = `-- name: InsertMessageSend :exec
INSERT INTO message_sends (project_id, channel, provider, kind, status, country, cost_minor, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMessageSendParams struct {
	ProjectID uuid.UUID
	Channel   string
	Provider  string
	Kind      string
	Status    string
	Country   *string
	CostMinor *int64
	Currency  *string
}

// tenant: system - a message sent for the project the caller resolved.
func (q *Queries) InsertMessageSend(ctx context.Context, arg InsertMessageSendParams) error {
	_, err := q.db.Exec(ctx, insertMessageSend,
		arg.ProjectID,
		arg.Channel,
		arg.Provider,
		arg.Kind,
		arg.Status,
		arg.Country,
		arg.CostMinor,
		arg.Currency,
	)
	return err
}

const markAuthEmailFailed = `-- name: MarkAuthEmailFailed :exec
UPDATE auth_message_outbox SET attempts = attempts + 1, last_error = $1, next_attempt_at = $2,
  message_enc = CASE WHEN $3::boolean THEN NULL ELSE message_enc END
WHERE id = $4
`

type MarkAuthEmailFailedParams struct {
	LastError     *string
	NextAttemptAt time.Time
	GiveUp        bool
	ID            uuid.UUID
}

// tenant: system - the auth email sender; give_up drops the message.
func (q *Queries) MarkAuthEmailFailed(ctx context.Context, arg MarkAuthEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markAuthEmailFailed,
		arg.LastError,
		arg.NextAttemptAt,
		arg.GiveUp,
		arg.ID,
	)
	return err
}

const markAuthEmailSent = `-- name: MarkAuthEmailSent :exec
UPDATE auth_message_outbox SET sent_at = now(), message_enc = NULL, attempts = attempts + 1, last_error = NULL WHERE id = $1
`

// tenant: system - the auth email sender.
func (q *Queries) MarkAuthEmailSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuthEmailSent, id)
	return err
}

const markAuthHook = `-- name: MarkAuthHook :exec
UPDATE auth_hook_outbox SET attempts = attempts + 1, last_status = $1, last_error = $2,
  delivered_at = CASE WHEN $3::boolean THEN now() END,
  failed_at = CASE WHEN $4::boolean THEN now() END,
  next_attempt_at = $5
WHERE id = $6
`

type MarkAuthHookParams struct {
	LastStatus    *int32
	LastError     *string
	Delivered     bool
	Failed        bool
	NextAttemptAt time.Time
	ID            uuid.UUID
}

// tenant: system - the auth hook sender.
func (q *Queries) MarkAuthHook(ctx context.Context, arg MarkAuthHookParams) error {
	_, err := q.db.Exec(ctx, markAuthHook,
		arg.LastStatus,
		arg.LastError,
		arg.Delivered,
		arg.Failed,
		arg.NextAttemptAt,
		arg.ID,
	)
	return err
}

const projectAuthHooks = `-- name: ProjectAuthHooks :many
SELECT id, event, attempts, last_status, last_error, created_at, delivered_at, failed_at FROM auth_hook_outbox
WHERE project_id = $1 ORDER BY created_at DESC LIMIT 50
`

type ProjectAuthHooksRow struct {
	ID          uuid.UUID
	Event       string
	Attempts    int32
	LastStatus  *int32
	LastError   *string
	CreatedAt   time.Time
	DeliveredAt *time.Time
	FailedAt    *time.Time
}

// tenant: system - a project the request already authorized: recent hook deliveries.
func (q *Queries) ProjectAuthHooks(ctx context.Context, projectID uuid.UUID) ([]ProjectAuthHooksRow, error) {
	rows, err := q.db.Query(ctx, projectAuthHooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectAuthHooksRow
	for rows.Next() {
		var i ProjectAuthHooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Event,
			&i.Attempts,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMAU = `-- name: ProjectMAU :one
SELECT count(*) FROM auth_mau WHERE project_id = $1 AND month = $2
`

type ProjectMAUParams struct {
	ProjectID uuid.UUID
	Month     pgtype.Date
}

// tenant: system - a project the request already authorized.
func (q *Queries) ProjectMAU(ctx context.Context, arg ProjectMAUParams) (int64, error) {
	row := q.db.QueryRow(ctx, projectMAU, arg.ProjectID, arg.Month)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const projectMessageSends = `-- name: ProjectMessageSends :many
SELECT channel, provider, status, count(*)::bigint AS n FROM message_sends
WHERE project_id = $1 AND created_at > $2
GROUP BY channel, provider, status ORDER BY channel, provider, status
`

type ProjectMessageSendsParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

type ProjectMessageSendsRow struct {
	Channel  string
	Provider string
	Status   string
	N        int64
}

// tenant: system - a project the request already authorized.
func (q *Queries) ProjectMessageSends(ctx context.Context, arg ProjectMessageSendsParams) ([]ProjectMessageSendsRow, error) {
	rows, err := q.db.Query(ctx, projectMessageSends, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMessageSendsRow
	for rows.Next() {
		var i ProjectMessageSendsRow
		if err := rows.Scan(
			&i.Channel,
			&i.Provider,
			&i.Status,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMessageSpend = `-- name: ProjectMessageSpend :many
SELECT channel, count(*)::bigint AS n, coalesce(sum(cost_minor), 0)::bigint AS cost_minor FROM message_sends
WHERE project_id = $1 AND created_at >= $2 AND status = 'sent' AND channel <> 'email'
GROUP BY channel ORDER BY channel
`

type ProjectMessageSpendParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

type ProjectMessageSpendRow struct {
	Channel   string
	N         int64
	CostMinor int64
}

// tenant: system - a project the request already authorized: this month's platform sends and their cost.
func (q *Queries) ProjectMessageSpend(ctx context.Context, arg ProjectMessageSpendParams) ([]ProjectMessageSpendRow, error) {
	rows, err := q.db.Query(ctx, projectMessageSpend, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMessageSpendRow
	for rows.Next() {
		var i ProjectMessageSpendRow
		if err := rows.Scan(&i.Channel, &i.N, &i.CostMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuthEmails = `-- name: PruneAuthEmails :execrows
DELETE FROM auth_message_outbox WHERE created_at < $1
`

// tenant: system - the auth email sender across all projects.
func (q *Queries) PruneAuthEmails(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthEmails, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneAuthHooks = `-- name: PruneAuthHooks :execrows
DELETE FROM auth_hook_outbox WHERE created_at < $1
`

// tenant: system - the auth hook sender across all projects.
func (q *Queries) PruneAuthHooks(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthHooks, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireJWTKeys = `-- name: RetireJWTKeys :execrows
UPDATE project_jwt_keys SET status = 'retired', retired_at = now()
WHERE status = 'verifying' AND verify_until IS NOT NULL AND verify_until < now()
`

// tenant: system - the signing-key sweep across all projects.
func (q *Queries) RetireJWTKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, retireJWTKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAuthConfig = `-- name: UpsertAuthConfig :one
INSERT INTO project_auth_config (project_id, config, providers_enc, templates)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id) DO UPDATE SET config = EXCLUDED.config, providers_enc = EXCLUDED.providers_enc,
  templates = EXCLUDED.templates, updated_at = now()
RETURNING project_id, config, providers_enc, templates, updated_at
`

type UpsertAuthConfigParams struct {
	ProjectID    uuid.UUID
	Config       json.RawMessage
	ProvidersEnc []byte
	Templates    json.RawMessage
}

// tenant: system - a project the request already authorized.
func (q *Queries) UpsertAuthConfig(ctx context.Context, arg UpsertAuthConfigParams) (ProjectAuthConfig, error) {
	row := q.db.QueryRow(ctx, upsertAuthConfig,
		arg.ProjectID,
		arg.Config,
		arg.ProvidersEnc,
		arg.Templates,
	)
	var i ProjectAuthConfig
	err := row.Scan(
		&i.ProjectID,
		&i.Config,
		&i.ProvidersEnc,
		&i.Templates,
		&i.UpdatedAt,
	)
	return i, err
}
