// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: regions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ensureRegion = `-- name: EnsureRegion :exec
INSERT INTO regions (id, name) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type EnsureRegionParams struct {
	ID   string
	Name string
}

func (q *Queries) EnsureRegion(ctx context.Context, arg EnsureRegionParams) error {
	_, err := q.db.Exec(ctx, ensureRegion, arg.ID, arg.Name)
	return err
}

const getRegion = `-- name: GetRegion :one
SELECT id, name, country, pooler_host, provider, location, storage_target_id, copy_target_id, floating_ip_id, residency, status, created_at FROM regions WHERE id = $1
`

func (q *Queries) GetRegion(ctx context.Context, id string) (Region, error) {
	row := q.db.QueryRow(ctx, getRegion, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.PoolerHost,
		&i.Provider,
		&i.Location,
		&i.StorageTargetID,
		&i.CopyTargetID,
		&i.FloatingIpID,
		&i.Residency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listRegions = `-- name: ListRegions :many

SELECT id, name, country, pooler_host, provider, location, storage_target_id, copy_target_id, floating_ip_id, residency, status, created_at FROM regions ORDER BY created_at, id
`

// Regions (V3 §6).
func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.PoolerHost,
			&i.Provider,
			&i.Location,
			&i.StorageTargetID,
			&i.CopyTargetID,
			&i.FloatingIpID,
			&i.Residency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionUsage = `-- name: RegionUsage :many
SELECT r.id,
  (SELECT count(*) FROM nodes n WHERE n.region = r.id AND n.status <> 'removed' AND n.role <> 'pooler')::int AS nodes,
  (SELECT count(*) FROM nodes n WHERE n.region = r.id AND n.status <> 'removed' AND n.role = 'pooler')::int AS pooler_hosts,
  (SELECT count(*) FROM projects p WHERE p.region = r.id AND p.deleted_at IS NULL)::int AS projects,
  (SELECT count(*) FROM projects p WHERE p.region = r.id AND p.deleted_at IS NULL AND p.data_residency)::int AS residency_projects,
  EXISTS (SELECT 1 FROM instances i JOIN nodes n ON n.id = i.node_id WHERE n.region = r.id AND i.kind = 'shared'
    AND i.status = 'running' AND i.deleted_at IS NULL AND i.org_id IS NULL) AS has_shared,
  EXISTS (SELECT 1 FROM nodes n WHERE n.region = r.id AND n.status = 'healthy' AND n.role IN ('dedicated', 'both')) AS has_dedicated
FROM regions r ORDER BY r.created_at, r.id
`

type RegionUsageRow struct {
	ID                string
	Nodes             int32
	PoolerHosts       int32
	Projects          int32
	ResidencyProjects int32
	HasShared         bool
	HasDedicated      bool
}

// tenant: system - each region's nodes and live projects, for the regions list.
func (q *Queries) RegionUsage(ctx context.Context) ([]RegionUsageRow, error) {
	rows, err := q.db.Query(ctx, regionUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegionUsageRow
	for rows.Next() {
		var i RegionUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.Nodes,
			&i.PoolerHosts,
			&i.Projects,
			&i.ResidencyProjects,
			&i.HasShared,
			&i.HasDedicated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectRegion = `-- name: SetProjectRegion :exec
UPDATE projects SET forward_region = CASE WHEN region <> $1 THEN region ELSE forward_region END,
  forward_until = CASE WHEN region <> $1 THEN $2 ELSE forward_until END,
  region = $1
WHERE id = $3
`

type SetProjectRegionParams struct {
	Region       string
	ForwardUntil *time.Time
	ID           uuid.UUID
}

// tenant: system - a region move's cutover: the old hostname keeps routing for 30 days.
func (q *Queries) SetProjectRegion(ctx context.Context, arg SetProjectRegionParams) error {
	_, err := q.db.Exec(ctx, setProjectRegion, arg.Region, arg.ForwardUntil, arg.ID)
	return err
}

const setProjectResidency = `-- name: SetProjectResidency :one
UPDATE projects SET data_residency = $1 WHERE id = $2 AND deleted_at IS NULL RETURNING id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier, lifecycle, last_active_at, pause_warned_at, paused_at, archived_at, archive_backup_id, archive_notice_days, region, data_residency, forward_region, forward_until
`

type SetProjectResidencyParams struct {
	DataResidency bool
	ID            uuid.UUID
}

// tenant: system - a project the request already authorized (owners only).
func (q *Queries) SetProjectResidency(ctx context.Context, arg SetProjectResidencyParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectResidency, arg.DataResidency, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbName,
		&i.OwnerRole,
		&i.ScramVerifier,
		&i.Tier,
		&i.InstanceID,
		&i.Status,
		&i.Settings,
		&i.StorageTargetID,
		&i.Extensions,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.AliasDbName,
		&i.LegacyOwnerRole,
		&i.LegacyScramVerifier,
		&i.LegacyUntil,
		&i.StorageState,
		&i.StorageStateAt,
		&i.BackupKeyID,
		&i.ParentProjectID,
		&i.BranchSource,
		&i.BranchSchemaOnly,
		&i.ExpiresAt,
		&i.ExpiryNotifiedAt,
		&i.BranchBackups,
		&i.SensitiveData,
		&i.ProbeVerifier,
		&i.Lifecycle,
		&i.LastActiveAt,
		&i.PauseWarnedAt,
		&i.PausedAt,
		&i.ArchivedAt,
		&i.ArchiveBackupID,
		&i.ArchiveNoticeDays,
		&i.Region,
		&i.DataResidency,
		&i.ForwardRegion,
		&i.ForwardUntil,
	)
	return i, err
}

const setStorageTargetRegion = `-- name: SetStorageTargetRegion :exec
UPDATE storage_targets SET pgdock_region = $1 WHERE id = $2
`

type SetStorageTargetRegionParams struct {
	PgdockRegion *string
	ID           uuid.UUID
}

// tenant: system - the platform admin marks a platform target as in a region.
func (q *Queries) SetStorageTargetRegion(ctx context.Context, arg SetStorageTargetRegionParams) error {
	_, err := q.db.Exec(ctx, setStorageTargetRegion, arg.PgdockRegion, arg.ID)
	return err
}

const upsertRegion = `-- name: UpsertRegion :one
INSERT INTO regions (id, name, country, pooler_host, provider, location, storage_target_id, copy_target_id, floating_ip_id, residency, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, country = EXCLUDED.country, pooler_host = EXCLUDED.pooler_host,
  provider = EXCLUDED.provider, location = EXCLUDED.location, storage_target_id = EXCLUDED.storage_target_id,
  copy_target_id = EXCLUDED.copy_target_id, floating_ip_id = EXCLUDED.floating_ip_id, residency = EXCLUDED.residency, status = EXCLUDED.status
RETURNING id, name, country, pooler_host, provider, location, storage_target_id, copy_target_id, floating_ip_id, residency, status, created_at
`

type UpsertRegionParams struct {
	ID              string
	Name            string
	Country         string
	PoolerHost      string
	Provider        string
	Location        string
	StorageTargetID *uuid.UUID
	CopyTargetID    *uuid.UUID
	FloatingIpID    *string
	Residency       bool
	Status          string
}

func (q *Queries) UpsertRegion(ctx context.Context, arg UpsertRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, upsertRegion,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.PoolerHost,
		arg.Provider,
		arg.Location,
		arg.StorageTargetID,
		arg.CopyTargetID,
		arg.FloatingIpID,
		arg.Residency,
		arg.Status,
	)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.PoolerHost,
		&i.Provider,
		&i.Location,
		&i.StorageTargetID,
		&i.CopyTargetID,
		&i.FloatingIpID,
		&i.Residency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
