// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replicas.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProjectReplicas = `-- name: CountProjectReplicas :one
SELECT count(*)::int FROM read_replicas WHERE project_id = $1 AND deleted_at IS NULL
`

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) CountProjectReplicas(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProjectReplicas, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteReadReplica = `-- name: DeleteReadReplica :exec
UPDATE read_replicas SET status = 'deleted', in_rotation = false, deleted_at = now(), updated_at = now() WHERE id = $1
`

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) DeleteReadReplica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReadReplica, id)
	return err
}

const getInstanceMember = `-- name: GetInstanceMember :one
SELECT id, instance_id, node_id, role, state, host, port, rest_host, rest_port, admin_host, admin_port, lag_bytes, timeline, error, updated_at, created_at, deleted_at, replica FROM instance_members WHERE id = $1
`

// tenant: system - HA members of an instance the caller already resolved.
func (q *Queries) GetInstanceMember(ctx context.Context, id uuid.UUID) (InstanceMember, error) {
	row := q.db.QueryRow(ctx, getInstanceMember, id)
	var i InstanceMember
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.NodeID,
		&i.Role,
		&i.State,
		&i.Host,
		&i.Port,
		&i.RestHost,
		&i.RestPort,
		&i.AdminHost,
		&i.AdminPort,
		&i.LagBytes,
		&i.Timeline,
		&i.Error,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Replica,
	)
	return i, err
}

const getReadReplica = `-- name: GetReadReplica :one
SELECT id, project_id, instance_member_id, node_id, region_id, size, status, in_rotation, lag_bytes, lag_ms, error, detached_project_id, rotation_changed_at, updated_at, created_at, deleted_at FROM read_replicas WHERE id = $1
`

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) GetReadReplica(ctx context.Context, id uuid.UUID) (ReadReplica, error) {
	row := q.db.QueryRow(ctx, getReadReplica, id)
	var i ReadReplica
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstanceMemberID,
		&i.NodeID,
		&i.RegionID,
		&i.Size,
		&i.Status,
		&i.InRotation,
		&i.LagBytes,
		&i.LagMs,
		&i.Error,
		&i.DetachedProjectID,
		&i.RotationChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hourlyReplicas = `-- name: HourlyReplicas :many
SELECT r.project_id, p.org_id, o.plan_id, g.h::timestamptz AS period_start,
       COALESCE(i.cpu_limit, 0)::float8 AS cpus, COALESCE(i.mem_limit_mb, 0)::int AS mem_mb, COALESCE(i.volume_gb, 0)::int AS disk_gb,
       (extract(epoch FROM LEAST(g.h + '1 hour'::interval, COALESCE(r.deleted_at, 'infinity'::timestamptz)) - GREATEST(g.h, r.created_at)) / 3600)::float8 AS fraction
FROM read_replicas r
JOIN projects p ON p.id = r.project_id
JOIN instances i ON i.id = p.instance_id
JOIN organizations o ON o.id = p.org_id
CROSS JOIN generate_series($1::timestamptz, $2::timestamptz, '1 hour'::interval) AS g(h)
WHERE r.created_at < g.h + '1 hour'::interval AND (r.deleted_at IS NULL OR r.deleted_at > g.h)
`

type HourlyReplicasParams struct {
	FromTs   time.Time
	LastHour time.Time
}

type HourlyReplicasRow struct {
	ProjectID   uuid.UUID
	OrgID       uuid.UUID
	PlanID      uuid.UUID
	PeriodStart time.Time
	Cpus        float64
	MemMb       int32
	DiskGb      int32
	Fraction    float64
}

// tenant: system - usage recording; rows carry org_id.
// Each read replica's size (its instance's), for each hour from @from_ts to
// @last_hour it existed, with the fraction of the hour it did.
func (q *Queries) HourlyReplicas(ctx context.Context, arg HourlyReplicasParams) ([]HourlyReplicasRow, error) {
	rows, err := q.db.Query(ctx, hourlyReplicas, arg.FromTs, arg.LastHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyReplicasRow
	for rows.Next() {
		var i HourlyReplicasRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.OrgID,
			&i.PlanID,
			&i.PeriodStart,
			&i.Cpus,
			&i.MemMb,
			&i.DiskGb,
			&i.Fraction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReadReplica = `-- name: InsertReadReplica :one
INSERT INTO read_replicas (id, project_id, instance_member_id, node_id, region_id, size)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, instance_member_id, node_id, region_id, size, status, in_rotation, lag_bytes, lag_ms, error, detached_project_id, rotation_changed_at, updated_at, created_at, deleted_at
`

type InsertReadReplicaParams struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	InstanceMemberID *uuid.UUID
	NodeID           uuid.UUID
	RegionID         *string
	Size             string
}

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) InsertReadReplica(ctx context.Context, arg InsertReadReplicaParams) (ReadReplica, error) {
	row := q.db.QueryRow(ctx, insertReadReplica,
		arg.ID,
		arg.ProjectID,
		arg.InstanceMemberID,
		arg.NodeID,
		arg.RegionID,
		arg.Size,
	)
	var i ReadReplica
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstanceMemberID,
		&i.NodeID,
		&i.RegionID,
		&i.Size,
		&i.Status,
		&i.InRotation,
		&i.LagBytes,
		&i.LagMs,
		&i.Error,
		&i.DetachedProjectID,
		&i.RotationChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const instanceReplicas = `-- name: InstanceReplicas :many
SELECT r.id, r.project_id, r.instance_member_id, r.node_id, r.region_id, r.size, r.status, r.in_rotation, r.lag_bytes, r.lag_ms, r.error, r.detached_project_id, r.rotation_changed_at, r.updated_at, r.created_at, r.deleted_at FROM read_replicas r JOIN projects p ON p.id = r.project_id
WHERE p.instance_id = $1 AND r.deleted_at IS NULL
ORDER BY r.created_at, r.id
`

// tenant: system - the replica watcher: an instance's live replicas.
func (q *Queries) InstanceReplicas(ctx context.Context, instanceID uuid.UUID) ([]ReadReplica, error) {
	rows, err := q.db.Query(ctx, instanceReplicas, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadReplica
	for rows.Next() {
		var i ReadReplica
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InstanceMemberID,
			&i.NodeID,
			&i.RegionID,
			&i.Size,
			&i.Status,
			&i.InRotation,
			&i.LagBytes,
			&i.LagMs,
			&i.Error,
			&i.DetachedProjectID,
			&i.RotationChangedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectReplicas = `-- name: ListProjectReplicas :many
SELECT r.id, r.project_id, r.instance_member_id, r.node_id, r.region_id, r.size, r.status, r.in_rotation, r.lag_bytes, r.lag_ms, r.error, r.detached_project_id, r.rotation_changed_at, r.updated_at, r.created_at, r.deleted_at, n.name AS node_name, n.region AS node_region, m.host, m.port, m.state AS member_state
FROM read_replicas r
JOIN nodes n ON n.id = r.node_id
LEFT JOIN instance_members m ON m.id = r.instance_member_id AND m.deleted_at IS NULL
WHERE r.project_id = $1 AND r.deleted_at IS NULL
ORDER BY r.created_at, r.id
`

type ListProjectReplicasRow struct {
	ID                uuid.UUID
	ProjectID         uuid.UUID
	InstanceMemberID  *uuid.UUID
	NodeID            uuid.UUID
	RegionID          *string
	Size              string
	Status            string
	InRotation        bool
	LagBytes          *int64
	LagMs             *int64
	Error             *string
	DetachedProjectID *uuid.UUID
	RotationChangedAt *time.Time
	UpdatedAt         time.Time
	CreatedAt         time.Time
	DeletedAt         *time.Time
	NodeName          string
	NodeRegion        string
	Host              *string
	Port              *int32
	MemberState       *string
}

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) ListProjectReplicas(ctx context.Context, projectID uuid.UUID) ([]ListProjectReplicasRow, error) {
	rows, err := q.db.Query(ctx, listProjectReplicas, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectReplicasRow
	for rows.Next() {
		var i ListProjectReplicasRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InstanceMemberID,
			&i.NodeID,
			&i.RegionID,
			&i.Size,
			&i.Status,
			&i.InRotation,
			&i.LagBytes,
			&i.LagMs,
			&i.Error,
			&i.DetachedProjectID,
			&i.RotationChangedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.NodeName,
			&i.NodeRegion,
			&i.Host,
			&i.Port,
			&i.MemberState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReplicaDetaching = `-- name: MarkReplicaDetaching :execrows
UPDATE read_replicas SET status = 'detaching', in_rotation = false, updated_at = now()
WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL AND status IN ('streaming', 'lagging', 'down')
`

type MarkReplicaDetachingParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) MarkReplicaDetaching(ctx context.Context, arg MarkReplicaDetachingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReplicaDetaching, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const poolerReplicaRoutes = `-- name: PoolerReplicaRoutes :many
SELECT p.db_name, r.id, r.in_rotation, n.region, COALESCE(m.host, n.private_addr)::text AS host, COALESCE(m.port, 0)::int AS port
FROM read_replicas r
JOIN projects p ON p.id = r.project_id
JOIN nodes n ON n.id = r.node_id
LEFT JOIN instance_members m ON m.id = r.instance_member_id AND m.deleted_at IS NULL
WHERE r.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY p.db_name, r.created_at, r.id
`

type PoolerReplicaRoutesRow struct {
	DbName     string
	ID         uuid.UUID
	InRotation bool
	Region     string
	Host       string
	Port       int32
}

// tenant: system - the poolers: every live read replica, whether it is in
// rotation, and the address the pooler reaches it at.
func (q *Queries) PoolerReplicaRoutes(ctx context.Context) ([]PoolerReplicaRoutesRow, error) {
	rows, err := q.db.Query(ctx, poolerReplicaRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolerReplicaRoutesRow
	for rows.Next() {
		var i PoolerReplicaRoutesRow
		if err := rows.Scan(
			&i.DbName,
			&i.ID,
			&i.InRotation,
			&i.Region,
			&i.Host,
			&i.Port,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberReplica = `-- name: SetMemberReplica :exec
UPDATE instance_members SET replica = true WHERE id = $1
`

// tenant: system - HA members of an instance the caller already resolved.
func (q *Queries) SetMemberReplica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setMemberReplica, id)
	return err
}

const setReplicaDetached = `-- name: SetReplicaDetached :exec
UPDATE read_replicas SET status = 'detached', in_rotation = false, detached_project_id = $1,
  deleted_at = now(), updated_at = now()
WHERE id = $2
`

type SetReplicaDetachedParams struct {
	DetachedProjectID *uuid.UUID
	ID                uuid.UUID
}

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) SetReplicaDetached(ctx context.Context, arg SetReplicaDetachedParams) error {
	_, err := q.db.Exec(ctx, setReplicaDetached, arg.DetachedProjectID, arg.ID)
	return err
}

const setReplicaLag = `-- name: SetReplicaLag :exec
UPDATE read_replicas SET status = $1, in_rotation = $2, lag_bytes = $3, lag_ms = $4,
  rotation_changed_at = CASE WHEN in_rotation <> $2 THEN now() ELSE rotation_changed_at END, updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
`

type SetReplicaLagParams struct {
	Status     string
	InRotation bool
	LagBytes   *int64
	LagMs      *int64
	ID         uuid.UUID
}

// tenant: system - the replica watcher, for a replica it already resolved.
func (q *Queries) SetReplicaLag(ctx context.Context, arg SetReplicaLagParams) error {
	_, err := q.db.Exec(ctx, setReplicaLag,
		arg.Status,
		arg.InRotation,
		arg.LagBytes,
		arg.LagMs,
		arg.ID,
	)
	return err
}

const setReplicaStatus = `-- name: SetReplicaStatus :exec
UPDATE read_replicas SET status = $1, error = $2, updated_at = now() WHERE id = $3
`

type SetReplicaStatusParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) SetReplicaStatus(ctx context.Context, arg SetReplicaStatusParams) error {
	_, err := q.db.Exec(ctx, setReplicaStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const unmarkReplicaDetaching = `-- name: UnmarkReplicaDetaching :exec
UPDATE read_replicas SET status = 'down', updated_at = now() WHERE id = $1 AND status = 'detaching' AND deleted_at IS NULL
`

// tenant: system - read replicas of a project the caller already resolved.
func (q *Queries) UnmarkReplicaDetaching(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unmarkReplicaDetaching, id)
	return err
}
