// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeJWTKey = `-- name: ActiveJWTKey :one
SELECT id, project_id, kid, algorithm, public_jwk, private_enc, status, created_at, retired_at, verify_until FROM project_jwt_keys WHERE project_id = $1 AND status = 'active'
`

// tenant: system - a project the caller resolved.
func (q *Queries) ActiveJWTKey(ctx context.Context, projectID uuid.UUID) (ProjectJwtKey, error) {
	row := q.db.QueryRow(ctx, activeJWTKey, projectID)
	var i ProjectJwtKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kid,
		&i.Algorithm,
		&i.PublicJwk,
		&i.PrivateEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.VerifyUntil,
	)
	return i, err
}

const createProjectServices = `-- name: CreateProjectServices :one
INSERT INTO project_services (project_id, ref) VALUES ($1, $2)
ON CONFLICT (project_id) DO NOTHING
RETURNING project_id, ref, enabled, exposed_schemas, public_tables, cors_origins, settings, edge_verifier, schema_version, roles_instance, config_version, changed_seq, enabled_at, created_at
`

type CreateProjectServicesParams struct {
	ProjectID uuid.UUID
	Ref       string
}

// tenant: system - a project the request already authorized.
func (q *Queries) CreateProjectServices(ctx context.Context, arg CreateProjectServicesParams) (ProjectService, error) {
	row := q.db.QueryRow(ctx, createProjectServices, arg.ProjectID, arg.Ref)
	var i ProjectService
	err := row.Scan(
		&i.ProjectID,
		&i.Ref,
		&i.Enabled,
		&i.ExposedSchemas,
		&i.PublicTables,
		&i.CorsOrigins,
		&i.Settings,
		&i.EdgeVerifier,
		&i.SchemaVersion,
		&i.RolesInstance,
		&i.ConfigVersion,
		&i.ChangedSeq,
		&i.EnabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const edgeAPIKeys = `-- name: EdgeAPIKeys :many
SELECT project_id, id, kind, key_hash FROM project_api_keys
WHERE project_id = ANY($1::uuid[]) AND revoked_at IS NULL
`

type EdgeAPIKeysRow struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
	Kind      string
	KeyHash   string
}

// tenant: system - pgdock-edge's configuration feed: the live keys' hashes.
func (q *Queries) EdgeAPIKeys(ctx context.Context, projectIds []uuid.UUID) ([]EdgeAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, edgeAPIKeys, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgeAPIKeysRow
	for rows.Next() {
		var i EdgeAPIKeysRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Kind,
			&i.KeyHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgeConfigChanges = `-- name: EdgeConfigChanges :many
SELECT s.project_id, s.ref, s.enabled, s.cors_origins, s.settings, s.exposed_schemas, s.public_tables,
  s.config_version, s.changed_seq, (s.edge_verifier IS NOT NULL)::boolean AS edge_ready,
  p.db_name, p.region, p.org_id, p.lifecycle, p.status, p.deleted_at, o.status AS org_status, o.plan_id
FROM project_services s JOIN projects p ON p.id = s.project_id JOIN organizations o ON o.id = p.org_id
WHERE s.changed_seq > $1
ORDER BY s.changed_seq
LIMIT $2
`

type EdgeConfigChangesParams struct {
	Since int64
	Lim   int32
}

type EdgeConfigChangesRow struct {
	ProjectID      uuid.UUID
	Ref            string
	Enabled        bool
	CorsOrigins    []string
	Settings       json.RawMessage
	ExposedSchemas []string
	PublicTables   []string
	ConfigVersion  int64
	ChangedSeq     int64
	EdgeReady      bool
	DbName         string
	Region         string
	OrgID          uuid.UUID
	Lifecycle      string
	Status         string
	DeletedAt      *time.Time
	OrgStatus      string
	PlanID         uuid.UUID
}

// tenant: system - pgdock-edge's configuration feed: every project with backend services changed since a point.
func (q *Queries) EdgeConfigChanges(ctx context.Context, arg EdgeConfigChangesParams) ([]EdgeConfigChangesRow, error) {
	rows, err := q.db.Query(ctx, edgeConfigChanges, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgeConfigChangesRow
	for rows.Next() {
		var i EdgeConfigChangesRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Ref,
			&i.Enabled,
			&i.CorsOrigins,
			&i.Settings,
			&i.ExposedSchemas,
			&i.PublicTables,
			&i.ConfigVersion,
			&i.ChangedSeq,
			&i.EdgeReady,
			&i.DbName,
			&i.Region,
			&i.OrgID,
			&i.Lifecycle,
			&i.Status,
			&i.DeletedAt,
			&i.OrgStatus,
			&i.PlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgeConfigSeq = `-- name: EdgeConfigSeq :one
SELECT coalesce(max(changed_seq), 0)::bigint FROM project_services
`

// tenant: system - pgdock-edge's configuration feed position.
func (q *Queries) EdgeConfigSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, edgeConfigSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const edgeJWTKeys = `-- name: EdgeJWTKeys :many
SELECT project_id, kid, public_jwk FROM project_jwt_keys
WHERE project_id = ANY($1::uuid[]) AND status <> 'retired'
`

type EdgeJWTKeysRow struct {
	ProjectID uuid.UUID
	Kid       string
	PublicJwk json.RawMessage
}

// tenant: system - pgdock-edge's configuration feed: public signing keys.
func (q *Queries) EdgeJWTKeys(ctx context.Context, projectIds []uuid.UUID) ([]EdgeJWTKeysRow, error) {
	rows, err := q.db.Query(ctx, edgeJWTKeys, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgeJWTKeysRow
	for rows.Next() {
		var i EdgeJWTKeysRow
		if err := rows.Scan(&i.ProjectID, &i.Kid, &i.PublicJwk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectServices = `-- name: GetProjectServices :one

SELECT project_id, ref, enabled, exposed_schemas, public_tables, cors_origins, settings, edge_verifier, schema_version, roles_instance, config_version, changed_seq, enabled_at, created_at FROM project_services WHERE project_id = $1
`

// Backend services (V4 §2): project refs, API keys, signing keys, and what
// pgdock-edge reads.
// tenant: system - a project the request already authorized.
func (q *Queries) GetProjectServices(ctx context.Context, projectID uuid.UUID) (ProjectService, error) {
	row := q.db.QueryRow(ctx, getProjectServices, projectID)
	var i ProjectService
	err := row.Scan(
		&i.ProjectID,
		&i.Ref,
		&i.Enabled,
		&i.ExposedSchemas,
		&i.PublicTables,
		&i.CorsOrigins,
		&i.Settings,
		&i.EdgeVerifier,
		&i.SchemaVersion,
		&i.RolesInstance,
		&i.ConfigVersion,
		&i.ChangedSeq,
		&i.EnabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO project_api_keys (project_id, kind, name, key_hash, prefix, display, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, kind, name, key_hash, prefix, display, last_used_at, revoked_at, created_by, created_at
`

type InsertAPIKeyParams struct {
	ProjectID uuid.UUID
	Kind      string
	Name      string
	KeyHash   string
	Prefix    string
	Display   *string
	CreatedBy *uuid.UUID
}

// tenant: system - a project the request already authorized.
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ProjectID,
		arg.Kind,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.Display,
		arg.CreatedBy,
	)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Display,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertEdgeReport = `-- name: InsertEdgeReport :execrows
INSERT INTO edge_reports (batch_id, edge) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertEdgeReportParams struct {
	BatchID string
	Edge    string
}

// tenant: system - pgdock-edge's usage and log reports, once per batch.
func (q *Queries) InsertEdgeReport(ctx context.Context, arg InsertEdgeReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEdgeReport, arg.BatchID, arg.Edge)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJWTKey = `-- name: InsertJWTKey :one
INSERT INTO project_jwt_keys (id, project_id, kid, public_jwk, private_enc, status)
VALUES ($1, $2, $3, $4, $5, 'active')
RETURNING id, project_id, kid, algorithm, public_jwk, private_enc, status, created_at, retired_at, verify_until
`

type InsertJWTKeyParams struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Kid        string
	PublicJwk  json.RawMessage
	PrivateEnc []byte
}

// tenant: system - a project the caller resolved.
func (q *Queries) InsertJWTKey(ctx context.Context, arg InsertJWTKeyParams) (ProjectJwtKey, error) {
	row := q.db.QueryRow(ctx, insertJWTKey,
		arg.ID,
		arg.ProjectID,
		arg.Kid,
		arg.PublicJwk,
		arg.PrivateEnc,
	)
	var i ProjectJwtKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kid,
		&i.Algorithm,
		&i.PublicJwk,
		&i.PrivateEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.VerifyUntil,
	)
	return i, err
}

type InsertRequestLogsParams struct {
	ProjectID uuid.UUID
	At        time.Time
	RequestID string
	Method    string
	Path      string
	Status    int32
	LatencyMs int32
	Role      *string
	UserID    *uuid.UUID
	KeyID     *uuid.UUID
	Ip        *string
	BytesOut  int64
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, kind, name, key_hash, prefix, display, last_used_at, revoked_at, created_by, created_at FROM project_api_keys WHERE project_id = $1 ORDER BY revoked_at IS NOT NULL, created_at
`

// tenant: system - a project the request already authorized.
func (q *Queries) ListAPIKeys(ctx context.Context, projectID uuid.UUID) ([]ProjectApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectApiKey
	for rows.Next() {
		var i ProjectApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.Display,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const poolerEdgeUsers = `-- name: PoolerEdgeUsers :many
SELECT p.db_name, s.edge_verifier::text AS edge_verifier, p.region, p.forward_region, p.forward_until
FROM project_services s JOIN projects p ON p.id = s.project_id
WHERE s.enabled AND s.edge_verifier IS NOT NULL AND p.deleted_at IS NULL
ORDER BY p.db_name
`

type PoolerEdgeUsersRow struct {
	DbName        string
	EdgeVerifier  string
	Region        string
	ForwardRegion *string
	ForwardUntil  *time.Time
}

// tenant: system - the edge logins the poolers must accept.
func (q *Queries) PoolerEdgeUsers(ctx context.Context) ([]PoolerEdgeUsersRow, error) {
	rows, err := q.db.Query(ctx, poolerEdgeUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolerEdgeUsersRow
	for rows.Next() {
		var i PoolerEdgeUsersRow
		if err := rows.Scan(
			&i.DbName,
			&i.EdgeVerifier,
			&i.Region,
			&i.ForwardRegion,
			&i.ForwardUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectJWTKeys = `-- name: ProjectJWTKeys :many
SELECT id, project_id, kid, algorithm, public_jwk, private_enc, status, created_at, retired_at, verify_until FROM project_jwt_keys WHERE project_id = $1 AND status <> 'retired' ORDER BY created_at
`

// tenant: system - a project the request already authorized.
func (q *Queries) ProjectJWTKeys(ctx context.Context, projectID uuid.UUID) ([]ProjectJwtKey, error) {
	rows, err := q.db.Query(ctx, projectJWTKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectJwtKey
	for rows.Next() {
		var i ProjectJwtKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kid,
			&i.Algorithm,
			&i.PublicJwk,
			&i.PrivateEnc,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
			&i.VerifyUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectRequestLogs = `-- name: ProjectRequestLogs :many
SELECT id, project_id, at, request_id, method, path, status, latency_ms, role, user_id, key_id, ip, bytes_out FROM api_request_logs
WHERE project_id = $1 AND ($2::bigint IS NULL OR id < $2)
ORDER BY id DESC LIMIT $3
`

type ProjectRequestLogsParams struct {
	ProjectID uuid.UUID
	Before    *int64
	Lim       int32
}

// tenant: system - a project the request already authorized.
func (q *Queries) ProjectRequestLogs(ctx context.Context, arg ProjectRequestLogsParams) ([]ApiRequestLog, error) {
	rows, err := q.db.Query(ctx, projectRequestLogs, arg.ProjectID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiRequestLog
	for rows.Next() {
		var i ApiRequestLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.At,
			&i.RequestID,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Role,
			&i.UserID,
			&i.KeyID,
			&i.Ip,
			&i.BytesOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectServicesByRef = `-- name: ProjectServicesByRef :one
SELECT s.project_id, s.ref, s.enabled, s.exposed_schemas, s.public_tables, s.cors_origins, s.settings, s.edge_verifier, s.schema_version, s.roles_instance, s.config_version, s.changed_seq, s.enabled_at, s.created_at, p.db_name FROM project_services s JOIN projects p ON p.id = s.project_id WHERE s.ref = $1
`

type ProjectServicesByRefRow struct {
	ProjectID      uuid.UUID
	Ref            string
	Enabled        bool
	ExposedSchemas []string
	PublicTables   []string
	CorsOrigins    []string
	Settings       json.RawMessage
	EdgeVerifier   *string
	SchemaVersion  int32
	RolesInstance  *uuid.UUID
	ConfigVersion  int64
	ChangedSeq     int64
	EnabledAt      *time.Time
	CreatedAt      time.Time
	DbName         string
}

// tenant: system - pgdock-edge names a project by its reference.
func (q *Queries) ProjectServicesByRef(ctx context.Context, ref string) (ProjectServicesByRefRow, error) {
	row := q.db.QueryRow(ctx, projectServicesByRef, ref)
	var i ProjectServicesByRefRow
	err := row.Scan(
		&i.ProjectID,
		&i.Ref,
		&i.Enabled,
		&i.ExposedSchemas,
		&i.PublicTables,
		&i.CorsOrigins,
		&i.Settings,
		&i.EdgeVerifier,
		&i.SchemaVersion,
		&i.RolesInstance,
		&i.ConfigVersion,
		&i.ChangedSeq,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.DbName,
	)
	return i, err
}

const projectUsageOwner = `-- name: ProjectUsageOwner :many
SELECT p.id, p.org_id, o.plan_id FROM projects p JOIN organizations o ON o.id = p.org_id
WHERE p.id = ANY($1::uuid[])
`

type ProjectUsageOwnerRow struct {
	ID     uuid.UUID
	OrgID  uuid.UUID
	PlanID uuid.UUID
}

// tenant: system - pgdock-edge's usage: each project's organisation and plan.
func (q *Queries) ProjectUsageOwner(ctx context.Context, projectIds []uuid.UUID) ([]ProjectUsageOwnerRow, error) {
	rows, err := q.db.Query(ctx, projectUsageOwner, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectUsageOwnerRow
	for rows.Next() {
		var i ProjectUsageOwnerRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.PlanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEdgeReports = `-- name: PruneEdgeReports :execrows
DELETE FROM edge_reports WHERE received_at < $1
`

// tenant: system - housekeeping.
func (q *Queries) PruneEdgeReports(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEdgeReports, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneRequestLogs = `-- name: PruneRequestLogs :execrows
DELETE FROM api_request_logs WHERE at < $1
`

// tenant: system - housekeeping: request logs are kept 7 days.
func (q *Queries) PruneRequestLogs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRequestLogs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE project_api_keys SET revoked_at = now()
WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
RETURNING id, project_id, kind, name, key_hash, prefix, display, last_used_at, revoked_at, created_by, created_at
`

type RevokeAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

// tenant: system - a project the request already authorized.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Display,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeProjectAPIKeys = `-- name: RevokeProjectAPIKeys :exec
UPDATE project_api_keys SET revoked_at = now() WHERE project_id = $1 AND revoked_at IS NULL
`

// tenant: system - a project the caller resolved (disabling services).
func (q *Queries) RevokeProjectAPIKeys(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeProjectAPIKeys, projectID)
	return err
}

const servicesToReconcile = `-- name: ServicesToReconcile :many
SELECT p.id, p.name, p.slug, p.db_name, p.owner_role, p.scram_verifier, p.tier, p.instance_id, p.status, p.settings, p.storage_target_id, p.extensions, p.description, p.created_by, p.created_at, p.deleted_at, p.org_id, p.alias_db_name, p.legacy_owner_role, p.legacy_scram_verifier, p.legacy_until, p.storage_state, p.storage_state_at, p.backup_key_id, p.parent_project_id, p.branch_source, p.branch_schema_only, p.expires_at, p.expiry_notified_at, p.branch_backups, p.sensitive_data, p.probe_verifier, p.lifecycle, p.last_active_at, p.pause_warned_at, p.paused_at, p.archived_at, p.archive_backup_id, p.archive_notice_days, p.region, p.data_residency, p.forward_region, p.forward_until FROM project_services s JOIN projects p ON p.id = s.project_id
WHERE s.enabled AND p.deleted_at IS NULL AND p.status = 'active' AND p.lifecycle = 'active'
  AND (s.schema_version < $1 OR s.roles_instance IS DISTINCT FROM p.instance_id)
ORDER BY p.id
LIMIT 50
`

// tenant: system - the services reconciler: enabled projects whose roles or pgd_* schemas are behind or on another instance.
func (q *Queries) ServicesToReconcile(ctx context.Context, schemaVersion int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, servicesToReconcile, schemaVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
			&i.Lifecycle,
			&i.LastActiveAt,
			&i.PauseWarnedAt,
			&i.PausedAt,
			&i.ArchivedAt,
			&i.ArchiveBackupID,
			&i.ArchiveNoticeDays,
			&i.Region,
			&i.DataResidency,
			&i.ForwardRegion,
			&i.ForwardUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServicesEnabled = `-- name: SetServicesEnabled :one
UPDATE project_services SET enabled = $1,
  enabled_at = CASE WHEN $1::boolean THEN now() ELSE enabled_at END
WHERE project_id = $2
RETURNING project_id, ref, enabled, exposed_schemas, public_tables, cors_origins, settings, edge_verifier, schema_version, roles_instance, config_version, changed_seq, enabled_at, created_at
`

type SetServicesEnabledParams struct {
	Enabled   bool
	ProjectID uuid.UUID
}

// tenant: system - a project the caller resolved.
func (q *Queries) SetServicesEnabled(ctx context.Context, arg SetServicesEnabledParams) (ProjectService, error) {
	row := q.db.QueryRow(ctx, setServicesEnabled, arg.Enabled, arg.ProjectID)
	var i ProjectService
	err := row.Scan(
		&i.ProjectID,
		&i.Ref,
		&i.Enabled,
		&i.ExposedSchemas,
		&i.PublicTables,
		&i.CorsOrigins,
		&i.Settings,
		&i.EdgeVerifier,
		&i.SchemaVersion,
		&i.RolesInstance,
		&i.ConfigVersion,
		&i.ChangedSeq,
		&i.EnabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const setServicesRoles = `-- name: SetServicesRoles :exec
UPDATE project_services SET edge_verifier = $1, schema_version = $2, roles_instance = $3
WHERE project_id = $4
`

type SetServicesRolesParams struct {
	EdgeVerifier  *string
	SchemaVersion int32
	RolesInstance *uuid.UUID
	ProjectID     uuid.UUID
}

// tenant: system - a project the caller resolved.
func (q *Queries) SetServicesRoles(ctx context.Context, arg SetServicesRolesParams) error {
	_, err := q.db.Exec(ctx, setServicesRoles,
		arg.EdgeVerifier,
		arg.SchemaVersion,
		arg.RolesInstance,
		arg.ProjectID,
	)
	return err
}

const touchAPIKeys = `-- name: TouchAPIKeys :exec
UPDATE project_api_keys SET last_used_at = greatest(coalesce(last_used_at, '-infinity'), $1::timestamptz)
WHERE id = ANY($2::uuid[])
`

type TouchAPIKeysParams struct {
	At  time.Time
	Ids []uuid.UUID
}

// tenant: system - the edge's report of keys in use.
func (q *Queries) TouchAPIKeys(ctx context.Context, arg TouchAPIKeysParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeys, arg.At, arg.Ids)
	return err
}

const updateServicesSettings = `-- name: UpdateServicesSettings :one
UPDATE project_services SET cors_origins = $1, settings = $2,
  exposed_schemas = $3, public_tables = $4
WHERE project_id = $5
RETURNING project_id, ref, enabled, exposed_schemas, public_tables, cors_origins, settings, edge_verifier, schema_version, roles_instance, config_version, changed_seq, enabled_at, created_at
`

type UpdateServicesSettingsParams struct {
	CorsOrigins    []string
	Settings       json.RawMessage
	ExposedSchemas []string
	PublicTables   []string
	ProjectID      uuid.UUID
}

// tenant: system - a project the request already authorized.
func (q *Queries) UpdateServicesSettings(ctx context.Context, arg UpdateServicesSettingsParams) (ProjectService, error) {
	row := q.db.QueryRow(ctx, updateServicesSettings,
		arg.CorsOrigins,
		arg.Settings,
		arg.ExposedSchemas,
		arg.PublicTables,
		arg.ProjectID,
	)
	var i ProjectService
	err := row.Scan(
		&i.ProjectID,
		&i.Ref,
		&i.Enabled,
		&i.ExposedSchemas,
		&i.PublicTables,
		&i.CorsOrigins,
		&i.Settings,
		&i.EdgeVerifier,
		&i.SchemaVersion,
		&i.RolesInstance,
		&i.ConfigVersion,
		&i.ChangedSeq,
		&i.EnabledAt,
		&i.CreatedAt,
	)
	return i, err
}
