// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage_targets.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultStorageTarget = `-- name: ClearDefaultStorageTarget :exec
UPDATE storage_targets SET is_default = false WHERE is_default AND org_id IS NULL
`

func (q *Queries) ClearDefaultStorageTarget(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultStorageTarget)
	return err
}

const dedicatedArchiveDrift = `-- name: DedicatedArchiveDrift :many
SELECT p.id, p.name, p.slug, p.db_name, p.owner_role, p.scram_verifier, p.tier, p.instance_id, p.status, p.settings, p.storage_target_id, p.extensions, p.description, p.created_by, p.created_at, p.deleted_at, p.org_id, p.alias_db_name, p.legacy_owner_role, p.legacy_scram_verifier, p.legacy_until, p.storage_state, p.storage_state_at, p.backup_key_id, p.parent_project_id, p.branch_source, p.branch_schema_only, p.expires_at, p.expiry_notified_at, p.branch_backups, p.sensitive_data, p.probe_verifier FROM projects p JOIN instances i ON i.id = p.instance_id
WHERE p.deleted_at IS NULL AND p.status = 'active' AND p.tier = 'dedicated'
  AND i.status = 'running' AND i.walg_prefix IS NOT NULL AND i.walg_target_id IS NOT NULL
  AND (COALESCE(p.storage_target_id, (SELECT t.id FROM storage_targets t WHERE t.is_default AND t.org_id IS NULL AND t.deleted_at IS NULL)) IS DISTINCT FROM i.walg_target_id
       OR p.backup_key_id IS DISTINCT FROM i.walg_key_id)
  AND NOT EXISTS (SELECT 1 FROM operations o WHERE o.project_id = p.id AND o.status IN ('queued', 'running'))
`

// tenant: system - the backup scheduler across organisations.
// Running dedicated projects whose WAL-G archive is not on the target and
// key their backups now use, with nothing in flight.
func (q *Queries) DedicatedArchiveDrift(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, dedicatedArchiveDrift)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbName,
			&i.OwnerRole,
			&i.ScramVerifier,
			&i.Tier,
			&i.InstanceID,
			&i.Status,
			&i.Settings,
			&i.StorageTargetID,
			&i.Extensions,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.AliasDbName,
			&i.LegacyOwnerRole,
			&i.LegacyScramVerifier,
			&i.LegacyUntil,
			&i.StorageState,
			&i.StorageStateAt,
			&i.BackupKeyID,
			&i.ParentProjectID,
			&i.BranchSource,
			&i.BranchSchemaOnly,
			&i.ExpiresAt,
			&i.ExpiryNotifiedAt,
			&i.BranchBackups,
			&i.SensitiveData,
			&i.ProbeVerifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forgetTargetBackups = `-- name: ForgetTargetBackups :execrows
UPDATE backups SET status = 'deleted', deleted_at = now(), error = 'its storage target was deleted'
WHERE storage_target_id = $1::uuid AND status IN ('succeeded', 'copied', 'failed') AND deleted_at IS NULL
`

// tenant: system - deleting a target whose backups the deleter accepted losing.
func (q *Queries) ForgetTargetBackups(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, forgetTargetBackups, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackupKey = `-- name: GetBackupKey :one
SELECT id, project_id, key_enc, fingerprint, created_by, created_at, retired_at FROM backup_keys WHERE id = $1
`

// tenant: system - backup workers open the key a backup row or project names.
func (q *Queries) GetBackupKey(ctx context.Context, id uuid.UUID) (BackupKey, error) {
	row := q.db.QueryRow(ctx, getBackupKey, id)
	var i BackupKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyEnc,
		&i.Fingerprint,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getDefaultStorageTarget = `-- name: GetDefaultStorageTarget :one

SELECT id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at FROM storage_targets WHERE is_default AND org_id IS NULL AND deleted_at IS NULL
`

// Storage targets (V2 s6): platform targets have no org_id; org targets
// belong to one organisation and are invisible to every other one and to
// the platform admin.
func (q *Queries) GetDefaultStorageTarget(ctx context.Context) (StorageTarget, error) {
	row := q.db.QueryRow(ctx, getDefaultStorageTarget)
	var i StorageTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Bucket,
		&i.Prefix,
		&i.Credentials,
		&i.IsDefault,
		&i.CreatedAt,
		&i.OrgID,
		&i.Region,
		&i.PathStyle,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgStorageTarget = `-- name: GetOrgStorageTarget :one
SELECT id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at FROM storage_targets WHERE id = $1 AND org_id = $2::uuid AND deleted_at IS NULL
`

type GetOrgStorageTargetParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetOrgStorageTarget(ctx context.Context, arg GetOrgStorageTargetParams) (StorageTarget, error) {
	row := q.db.QueryRow(ctx, getOrgStorageTarget, arg.ID, arg.OrgID)
	var i StorageTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Bucket,
		&i.Prefix,
		&i.Credentials,
		&i.IsDefault,
		&i.CreatedAt,
		&i.OrgID,
		&i.Region,
		&i.PathStyle,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlatformStorageTarget = `-- name: GetPlatformStorageTarget :one
SELECT id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at FROM storage_targets WHERE id = $1 AND org_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) GetPlatformStorageTarget(ctx context.Context, id uuid.UUID) (StorageTarget, error) {
	row := q.db.QueryRow(ctx, getPlatformStorageTarget, id)
	var i StorageTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Bucket,
		&i.Prefix,
		&i.Credentials,
		&i.IsDefault,
		&i.CreatedAt,
		&i.OrgID,
		&i.Region,
		&i.PathStyle,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectForUpdate = `-- name: GetProjectForUpdate :one
SELECT id, name, slug, db_name, owner_role, scram_verifier, tier, instance_id, status, settings, storage_target_id, extensions, description, created_by, created_at, deleted_at, org_id, alias_db_name, legacy_owner_role, legacy_scram_verifier, legacy_until, storage_state, storage_state_at, backup_key_id, parent_project_id, branch_source, branch_schema_only, expires_at, expiry_notified_at, branch_backups, sensitive_data, probe_verifier FROM projects WHERE id = $1 FOR UPDATE
`

// tenant: system - a project the request already authorized, locked while its backup settings change.
func (q *Queries) GetProjectForUpdate(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUpdate, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbName,
		&i.OwnerRole,
		&i.ScramVerifier,
		&i.Tier,
		&i.InstanceID,
		&i.Status,
		&i.Settings,
		&i.StorageTargetID,
		&i.Extensions,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.AliasDbName,
		&i.LegacyOwnerRole,
		&i.LegacyScramVerifier,
		&i.LegacyUntil,
		&i.StorageState,
		&i.StorageStateAt,
		&i.BackupKeyID,
		&i.ParentProjectID,
		&i.BranchSource,
		&i.BranchSchemaOnly,
		&i.ExpiresAt,
		&i.ExpiryNotifiedAt,
		&i.BranchBackups,
		&i.SensitiveData,
		&i.ProbeVerifier,
	)
	return i, err
}

const getStorageTarget = `-- name: GetStorageTarget :one
SELECT id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at FROM storage_targets WHERE id = $1
`

// tenant: system - backup workers resolve a project's or a backup's target by id (an org_id-free lookup the caller already scoped).
func (q *Queries) GetStorageTarget(ctx context.Context, id uuid.UUID) (StorageTarget, error) {
	row := q.db.QueryRow(ctx, getStorageTarget, id)
	var i StorageTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Bucket,
		&i.Prefix,
		&i.Credentials,
		&i.IsDefault,
		&i.CreatedAt,
		&i.OrgID,
		&i.Region,
		&i.PathStyle,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertBackupKey = `-- name: InsertBackupKey :one

INSERT INTO backup_keys (id, project_id, key_enc, fingerprint, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, key_enc, fingerprint, created_by, created_at, retired_at
`

type InsertBackupKeyParams struct {
	ID          uuid.UUID
	ProjectID   *uuid.UUID
	KeyEnc      []byte
	Fingerprint string
	CreatedBy   *uuid.UUID
}

// Per-project backup keys.
// tenant: system - a project the request already authorized.
func (q *Queries) InsertBackupKey(ctx context.Context, arg InsertBackupKeyParams) (BackupKey, error) {
	row := q.db.QueryRow(ctx, insertBackupKey,
		arg.ID,
		arg.ProjectID,
		arg.KeyEnc,
		arg.Fingerprint,
		arg.CreatedBy,
	)
	var i BackupKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyEnc,
		&i.Fingerprint,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const insertStorageTarget = `-- name: InsertStorageTarget :one
INSERT INTO storage_targets (id, org_id, name, endpoint, bucket, prefix, region, path_style, credentials, is_default, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at
`

type InsertStorageTargetParams struct {
	ID          uuid.UUID
	OrgID       *uuid.UUID
	Name        string
	Endpoint    string
	Bucket      string
	Prefix      string
	Region      string
	PathStyle   bool
	Credentials []byte
	IsDefault   bool
	CreatedBy   *uuid.UUID
}

func (q *Queries) InsertStorageTarget(ctx context.Context, arg InsertStorageTargetParams) (StorageTarget, error) {
	row := q.db.QueryRow(ctx, insertStorageTarget,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Endpoint,
		arg.Bucket,
		arg.Prefix,
		arg.Region,
		arg.PathStyle,
		arg.Credentials,
		arg.IsDefault,
		arg.CreatedBy,
	)
	var i StorageTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Bucket,
		&i.Prefix,
		&i.Credentials,
		&i.IsDefault,
		&i.CreatedAt,
		&i.OrgID,
		&i.Region,
		&i.PathStyle,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const instanceArchivingTo = `-- name: InstanceArchivingTo :one
SELECT EXISTS (SELECT 1 FROM instances WHERE walg_prefix = $1 AND walg_target_id = $2 AND status <> 'deleted')::bool
`

type InstanceArchivingToParams struct {
	WalgPrefix   *string
	WalgTargetID *uuid.UUID
}

func (q *Queries) InstanceArchivingTo(ctx context.Context, arg InstanceArchivingToParams) (bool, error) {
	row := q.db.QueryRow(ctx, instanceArchivingTo, arg.WalgPrefix, arg.WalgTargetID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listOrgStorageTargets = `-- name: ListOrgStorageTargets :many
SELECT id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at FROM storage_targets WHERE org_id = $1::uuid AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListOrgStorageTargets(ctx context.Context, orgID uuid.UUID) ([]StorageTarget, error) {
	rows, err := q.db.Query(ctx, listOrgStorageTargets, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageTarget
	for rows.Next() {
		var i StorageTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Bucket,
			&i.Prefix,
			&i.Credentials,
			&i.IsDefault,
			&i.CreatedAt,
			&i.OrgID,
			&i.Region,
			&i.PathStyle,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformStorageTargets = `-- name: ListPlatformStorageTargets :many
SELECT id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at FROM storage_targets WHERE org_id IS NULL AND deleted_at IS NULL ORDER BY is_default DESC, name
`

func (q *Queries) ListPlatformStorageTargets(ctx context.Context) ([]StorageTarget, error) {
	rows, err := q.db.Query(ctx, listPlatformStorageTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageTarget
	for rows.Next() {
		var i StorageTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Bucket,
			&i.Prefix,
			&i.Credentials,
			&i.IsDefault,
			&i.CreatedAt,
			&i.OrgID,
			&i.Region,
			&i.PathStyle,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgPlatformBackupBytes = `-- name: OrgPlatformBackupBytes :one
SELECT COALESCE(sum(b.size_bytes), 0)::float8
FROM backups b JOIN projects p ON p.id = b.project_id JOIN storage_targets t ON t.id = b.storage_target_id
WHERE p.org_id = $1 AND t.org_id IS NULL AND b.status IN ('succeeded', 'copied') AND b.deleted_at IS NULL
`

// Backup storage the org's projects hold on platform targets (V2 s10.3);
// org targets do not count.
func (q *Queries) OrgPlatformBackupBytes(ctx context.Context, orgID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, orgPlatformBackupBytes, orgID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const projectsUsingOrgTargets = `-- name: ProjectsUsingOrgTargets :one
SELECT (p.storage_target_id IS NOT NULL AND EXISTS (SELECT 1 FROM storage_targets t WHERE t.id = p.storage_target_id AND t.org_id IS NOT NULL)
        OR EXISTS (SELECT 1 FROM backups b JOIN storage_targets t ON t.id = b.storage_target_id
                   WHERE b.project_id = p.id AND t.org_id IS NOT NULL AND b.status IN ('succeeded', 'copied', 'running') AND b.deleted_at IS NULL))::bool
FROM projects p WHERE p.id = $1 AND p.org_id = $2
`

type ProjectsUsingOrgTargetsParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// A project that uses one of the org's targets, or holds backups on one,
// cannot leave the org with them.
func (q *Queries) ProjectsUsingOrgTargets(ctx context.Context, arg ProjectsUsingOrgTargetsParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectsUsingOrgTargets, arg.ID, arg.OrgID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const retireBackupKey = `-- name: RetireBackupKey :exec
UPDATE backup_keys SET retired_at = now() WHERE id = $1 AND retired_at IS NULL
`

// tenant: system - a project the request already authorized.
func (q *Queries) RetireBackupKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, retireBackupKey, id)
	return err
}

const setDefaultStorageTarget = `-- name: SetDefaultStorageTarget :execrows
UPDATE storage_targets SET is_default = true WHERE id = $1 AND org_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) SetDefaultStorageTarget(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setDefaultStorageTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstanceWALG = `-- name: SetInstanceWALG :exec
UPDATE instances SET walg_prefix = $1, walg_target_id = $2, walg_key_id = $3
WHERE id = $4
`

type SetInstanceWALGParams struct {
	WalgPrefix   *string
	WalgTargetID *uuid.UUID
	WalgKeyID    *uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) SetInstanceWALG(ctx context.Context, arg SetInstanceWALGParams) error {
	_, err := q.db.Exec(ctx, setInstanceWALG,
		arg.WalgPrefix,
		arg.WalgTargetID,
		arg.WalgKeyID,
		arg.ID,
	)
	return err
}

const setProjectBackupKey = `-- name: SetProjectBackupKey :exec
UPDATE projects SET backup_key_id = $1 WHERE id = $2
`

type SetProjectBackupKeyParams struct {
	BackupKeyID *uuid.UUID
	ID          uuid.UUID
}

// tenant: system - a project the request already authorized.
func (q *Queries) SetProjectBackupKey(ctx context.Context, arg SetProjectBackupKeyParams) error {
	_, err := q.db.Exec(ctx, setProjectBackupKey, arg.BackupKeyID, arg.ID)
	return err
}

const setProjectStorageTarget = `-- name: SetProjectStorageTarget :exec
UPDATE projects SET storage_target_id = $1 WHERE id = $2
`

type SetProjectStorageTargetParams struct {
	StorageTargetID *uuid.UUID
	ID              uuid.UUID
}

// tenant: system - a project the request already authorized.
func (q *Queries) SetProjectStorageTarget(ctx context.Context, arg SetProjectStorageTargetParams) error {
	_, err := q.db.Exec(ctx, setProjectStorageTarget, arg.StorageTargetID, arg.ID)
	return err
}

const softDeleteStorageTarget = `-- name: SoftDeleteStorageTarget :exec
UPDATE storage_targets SET deleted_at = now(), is_default = false, credentials = '\x'::bytea WHERE id = $1
`

// tenant: system - the caller loaded the target through its org_id (or as a platform target) first.
func (q *Queries) SoftDeleteStorageTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStorageTarget, id)
	return err
}

const storageTargetUse = `-- name: StorageTargetUse :one
SELECT
  (SELECT count(*) FROM projects p WHERE p.deleted_at IS NULL
     AND (p.storage_target_id = $1::uuid OR ($2::bool AND p.storage_target_id IS NULL)))::int AS projects,
  (SELECT count(*) FROM instances i WHERE i.status <> 'deleted' AND i.walg_target_id = $1::uuid)::int AS instances,
  (SELECT count(*) FROM backups b WHERE b.storage_target_id = $1::uuid AND b.status IN ('succeeded', 'copied', 'running')
     AND b.deleted_at IS NULL AND (b.expires_at IS NULL OR b.expires_at > now()))::int AS backups,
  (SELECT COALESCE(sum(b.size_bytes), 0) FROM backups b WHERE b.storage_target_id = $1::uuid
     AND b.status IN ('succeeded', 'copied') AND b.deleted_at IS NULL)::bigint AS bytes
`

type StorageTargetUseParams struct {
	ID        uuid.UUID
	IsDefault bool
}

type StorageTargetUseRow struct {
	Projects  int32
	Instances int32
	Backups   int32
	Bytes     int64
}

// tenant: system - deletion checks for a target the caller already scoped; counts only.
// Live projects choosing the target (or, for the default, choosing none),
// live dedicated instances archiving to it, and unexpired backups on it.
func (q *Queries) StorageTargetUse(ctx context.Context, arg StorageTargetUseParams) (StorageTargetUseRow, error) {
	row := q.db.QueryRow(ctx, storageTargetUse, arg.ID, arg.IsDefault)
	var i StorageTargetUseRow
	err := row.Scan(
		&i.Projects,
		&i.Instances,
		&i.Backups,
		&i.Bytes,
	)
	return i, err
}

const updateStorageTarget = `-- name: UpdateStorageTarget :one
UPDATE storage_targets
SET name = $1, endpoint = $2, bucket = $3, prefix = $4, region = $5,
    path_style = $6, credentials = $7, updated_at = now()
WHERE id = $8 AND deleted_at IS NULL
RETURNING id, name, endpoint, bucket, prefix, credentials, is_default, created_at, org_id, region, path_style, created_by, updated_at, deleted_at
`

type UpdateStorageTargetParams struct {
	Name        string
	Endpoint    string
	Bucket      string
	Prefix      string
	Region      string
	PathStyle   bool
	Credentials []byte
	ID          uuid.UUID
}

// tenant: system - the caller loaded the target through its org_id (or as a platform target) first.
func (q *Queries) UpdateStorageTarget(ctx context.Context, arg UpdateStorageTargetParams) (StorageTarget, error) {
	row := q.db.QueryRow(ctx, updateStorageTarget,
		arg.Name,
		arg.Endpoint,
		arg.Bucket,
		arg.Prefix,
		arg.Region,
		arg.PathStyle,
		arg.Credentials,
		arg.ID,
	)
	var i StorageTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Bucket,
		&i.Prefix,
		&i.Credentials,
		&i.IsDefault,
		&i.CreatedAt,
		&i.OrgID,
		&i.Region,
		&i.PathStyle,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
