// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const approveDeviceRequest = `-- name: ApproveDeviceRequest :execrows
UPDATE device_auth_requests SET approved_by = $1, org_id = $2, token_id = $3, sealed_token = $4
WHERE device_code_hash = $5 AND approved_by IS NULL AND denied_at IS NULL AND expires_at > now()
`

type ApproveDeviceRequestParams struct {
	ApprovedBy     *uuid.UUID
	OrgID          *uuid.UUID
	TokenID        *uuid.UUID
	SealedToken    []byte
	DeviceCodeHash string
}

func (q *Queries) ApproveDeviceRequest(ctx context.Context, arg ApproveDeviceRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveDeviceRequest,
		arg.ApprovedBy,
		arg.OrgID,
		arg.TokenID,
		arg.SealedToken,
		arg.DeviceCodeHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceRequest = `-- name: DeleteDeviceRequest :exec
DELETE FROM device_auth_requests WHERE device_code_hash = $1
`

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) DeleteDeviceRequest(ctx context.Context, deviceCodeHash string) error {
	_, err := q.db.Exec(ctx, deleteDeviceRequest, deviceCodeHash)
	return err
}

const deleteExpiredDeviceRequests = `-- name: DeleteExpiredDeviceRequests :execrows
DELETE FROM device_auth_requests WHERE expires_at < now() - '1 hour'::interval
`

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) DeleteExpiredDeviceRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDeviceRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyDeviceRequest = `-- name: DenyDeviceRequest :execrows
UPDATE device_auth_requests SET denied_at = now()
WHERE device_code_hash = $1 AND approved_by IS NULL AND denied_at IS NULL
`

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) DenyDeviceRequest(ctx context.Context, deviceCodeHash string) (int64, error) {
	result, err := q.db.Exec(ctx, denyDeviceRequest, deviceCodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dropProjectFromTokens = `-- name: DropProjectFromTokens :exec
UPDATE api_tokens SET project_ids = array_remove(project_ids, $1::uuid)
WHERE org_id = $2 AND $1::uuid = ANY(project_ids)
`

type DropProjectFromTokensParams struct {
	ProjectID uuid.UUID
	OrgID     uuid.UUID
}

// A project moved to another organisation leaves its old org's tokens.
func (q *Queries) DropProjectFromTokens(ctx context.Context, arg DropProjectFromTokensParams) error {
	_, err := q.db.Exec(ctx, dropProjectFromTokens, arg.ProjectID, arg.OrgID)
	return err
}

const getDeviceRequest = `-- name: GetDeviceRequest :one
SELECT device_code_hash, user_code, client_name, requested_scopes, org_id, approved_by, token_id, sealed_token, denied_at, last_polled_at, expires_at, created_at FROM device_auth_requests WHERE device_code_hash = $1
`

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) GetDeviceRequest(ctx context.Context, deviceCodeHash string) (DeviceAuthRequest, error) {
	row := q.db.QueryRow(ctx, getDeviceRequest, deviceCodeHash)
	var i DeviceAuthRequest
	err := row.Scan(
		&i.DeviceCodeHash,
		&i.UserCode,
		&i.ClientName,
		&i.RequestedScopes,
		&i.OrgID,
		&i.ApprovedBy,
		&i.TokenID,
		&i.SealedToken,
		&i.DeniedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceRequestByCode = `-- name: GetDeviceRequestByCode :one
SELECT device_code_hash, user_code, client_name, requested_scopes, org_id, approved_by, token_id, sealed_token, denied_at, last_polled_at, expires_at, created_at FROM device_auth_requests WHERE user_code = $1
`

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) GetDeviceRequestByCode(ctx context.Context, userCode string) (DeviceAuthRequest, error) {
	row := q.db.QueryRow(ctx, getDeviceRequestByCode, userCode)
	var i DeviceAuthRequest
	err := row.Scan(
		&i.DeviceCodeHash,
		&i.UserCode,
		&i.ClientName,
		&i.RequestedScopes,
		&i.OrgID,
		&i.ApprovedBy,
		&i.TokenID,
		&i.SealedToken,
		&i.DeniedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgToken = `-- name: GetOrgToken :one
SELECT id, user_id, org_id, name, token_hash, prefix, scopes, project_ids, expires_at, last_used_at, last_used_ip, revoked_at, revoked_by, created_via, expiry_notified_at, created_at FROM api_tokens WHERE id = $1 AND org_id = $2
`

type GetOrgTokenParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetOrgToken(ctx context.Context, arg GetOrgTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getOrgToken, arg.ID, arg.OrgID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.ProjectIds,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedVia,
		&i.ExpiryNotifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenForAuth = `-- name: GetTokenForAuth :one
SELECT t.id, t.user_id, t.org_id, t.name, t.scopes, t.project_ids, t.expires_at, t.revoked_at, t.last_used_at,
       u.email, u.name AS user_name, u.platform_role, u.disabled_at, u.approved_at, u.email_verified_at,
       o.status AS org_status
FROM api_tokens t
JOIN users u ON u.id = t.user_id
JOIN organizations o ON o.id = t.org_id
WHERE t.token_hash = $1
`

type GetTokenForAuthRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	OrgID           uuid.UUID
	Name            string
	Scopes          []string
	ProjectIds      []uuid.UUID
	ExpiresAt       time.Time
	RevokedAt       *time.Time
	LastUsedAt      *time.Time
	Email           string
	UserName        *string
	PlatformRole    string
	DisabledAt      *time.Time
	ApprovedAt      *time.Time
	EmailVerifiedAt *time.Time
	OrgStatus       string
}

// tenant: system - resolving a bearer token is how a request learns its org.
func (q *Queries) GetTokenForAuth(ctx context.Context, tokenHash string) (GetTokenForAuthRow, error) {
	row := q.db.QueryRow(ctx, getTokenForAuth, tokenHash)
	var i GetTokenForAuthRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.ProjectIds,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Email,
		&i.UserName,
		&i.PlatformRole,
		&i.DisabledAt,
		&i.ApprovedAt,
		&i.EmailVerifiedAt,
		&i.OrgStatus,
	)
	return i, err
}

const getUserToken = `-- name: GetUserToken :one
SELECT id, user_id, org_id, name, token_hash, prefix, scopes, project_ids, expires_at, last_used_at, last_used_ip, revoked_at, revoked_by, created_via, expiry_notified_at, created_at FROM api_tokens WHERE id = $1 AND user_id = $2
`

type GetUserTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// tenant: system - the caller's own token, by id.
func (q *Queries) GetUserToken(ctx context.Context, arg GetUserTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getUserToken, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.ProjectIds,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedVia,
		&i.ExpiryNotifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :one
INSERT INTO api_tokens (user_id, org_id, name, token_hash, prefix, scopes, project_ids, expires_at, created_via)
VALUES ($1, $2, $3, $4, $5, $6::text[], $7::uuid[], $8, $9)
RETURNING id, user_id, org_id, name, token_hash, prefix, scopes, project_ids, expires_at, last_used_at, last_used_ip, revoked_at, revoked_by, created_via, expiry_notified_at, created_at
`

type InsertAPITokenParams struct {
	UserID     uuid.UUID
	OrgID      uuid.UUID
	Name       string
	TokenHash  string
	Prefix     string
	Scopes     []string
	ProjectIds []uuid.UUID
	ExpiresAt  time.Time
	CreatedVia string
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, insertAPIToken,
		arg.UserID,
		arg.OrgID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.Scopes,
		arg.ProjectIds,
		arg.ExpiresAt,
		arg.CreatedVia,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.ProjectIds,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedVia,
		&i.ExpiryNotifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeviceRequest = `-- name: InsertDeviceRequest :exec
INSERT INTO device_auth_requests (device_code_hash, user_code, client_name, requested_scopes, expires_at)
VALUES ($1, $2, $3, $4::text[], $5)
`

type InsertDeviceRequestParams struct {
	DeviceCodeHash  string
	UserCode        string
	ClientName      string
	RequestedScopes []string
	ExpiresAt       time.Time
}

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) InsertDeviceRequest(ctx context.Context, arg InsertDeviceRequestParams) error {
	_, err := q.db.Exec(ctx, insertDeviceRequest,
		arg.DeviceCodeHash,
		arg.UserCode,
		arg.ClientName,
		arg.RequestedScopes,
		arg.ExpiresAt,
	)
	return err
}

const listOrgTokens = `-- name: ListOrgTokens :many
SELECT t.id, t.user_id, t.org_id, t.name, t.token_hash, t.prefix, t.scopes, t.project_ids, t.expires_at, t.last_used_at, t.last_used_ip, t.revoked_at, t.revoked_by, t.created_via, t.expiry_notified_at, t.created_at, u.email AS user_email, u.name AS user_name
FROM api_tokens t JOIN users u ON u.id = t.user_id
WHERE t.org_id = $1
ORDER BY t.revoked_at IS NOT NULL, t.created_at DESC
`

type ListOrgTokensRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	OrgID            uuid.UUID
	Name             string
	TokenHash        string
	Prefix           string
	Scopes           []string
	ProjectIds       []uuid.UUID
	ExpiresAt        time.Time
	LastUsedAt       *time.Time
	LastUsedIp       *netip.Addr
	RevokedAt        *time.Time
	RevokedBy        *uuid.UUID
	CreatedVia       string
	ExpiryNotifiedAt *time.Time
	CreatedAt        time.Time
	UserEmail        string
	UserName         *string
}

func (q *Queries) ListOrgTokens(ctx context.Context, orgID uuid.UUID) ([]ListOrgTokensRow, error) {
	rows, err := q.db.Query(ctx, listOrgTokens, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgTokensRow
	for rows.Next() {
		var i ListOrgTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.ProjectIds,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.CreatedVia,
			&i.ExpiryNotifiedAt,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTokens = `-- name: ListUserTokens :many
SELECT t.id, t.user_id, t.org_id, t.name, t.token_hash, t.prefix, t.scopes, t.project_ids, t.expires_at, t.last_used_at, t.last_used_ip, t.revoked_at, t.revoked_by, t.created_via, t.expiry_notified_at, t.created_at, o.name AS org_name
FROM api_tokens t JOIN organizations o ON o.id = t.org_id
WHERE t.user_id = $1
ORDER BY t.revoked_at IS NOT NULL, t.created_at DESC
`

type ListUserTokensRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	OrgID            uuid.UUID
	Name             string
	TokenHash        string
	Prefix           string
	Scopes           []string
	ProjectIds       []uuid.UUID
	ExpiresAt        time.Time
	LastUsedAt       *time.Time
	LastUsedIp       *netip.Addr
	RevokedAt        *time.Time
	RevokedBy        *uuid.UUID
	CreatedVia       string
	ExpiryNotifiedAt *time.Time
	CreatedAt        time.Time
	OrgName          string
}

// tenant: system - a user's own tokens, across their organisations.
func (q *Queries) ListUserTokens(ctx context.Context, userID uuid.UUID) ([]ListUserTokensRow, error) {
	rows, err := q.db.Query(ctx, listUserTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTokensRow
	for rows.Next() {
		var i ListUserTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.ProjectIds,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.CreatedVia,
			&i.ExpiryNotifiedAt,
			&i.CreatedAt,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenExpiryNotified = `-- name: MarkTokenExpiryNotified :exec
UPDATE api_tokens SET expiry_notified_at = now() WHERE id = $1 AND org_id = $2
`

type MarkTokenExpiryNotifiedParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) MarkTokenExpiryNotified(ctx context.Context, arg MarkTokenExpiryNotifiedParams) error {
	_, err := q.db.Exec(ctx, markTokenExpiryNotified, arg.ID, arg.OrgID)
	return err
}

const pollDeviceRequest = `-- name: PollDeviceRequest :exec
UPDATE device_auth_requests SET last_polled_at = $1::timestamptz WHERE device_code_hash = $2
`

type PollDeviceRequestParams struct {
	Now            time.Time
	DeviceCodeHash string
}

// tenant: system - a device login has no organisation until it is approved.
func (q *Queries) PollDeviceRequest(ctx context.Context, arg PollDeviceRequestParams) error {
	_, err := q.db.Exec(ctx, pollDeviceRequest, arg.Now, arg.DeviceCodeHash)
	return err
}

const revokeEmptiedTokens = `-- name: RevokeEmptiedTokens :execrows
UPDATE api_tokens SET revoked_at = now()
WHERE org_id = $1 AND project_ids IS NOT NULL AND cardinality(project_ids) = 0 AND revoked_at IS NULL
`

func (q *Queries) RevokeEmptiedTokens(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeEmptiedTokens, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE api_tokens SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND org_id = $3 AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedBy *uuid.UUID
	ID        uuid.UUID
	OrgID     uuid.UUID
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToken, arg.RevokedBy, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserOrgTokens = `-- name: RevokeUserOrgTokens :execrows
UPDATE api_tokens SET revoked_at = now()
WHERE org_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeUserOrgTokensParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

// When someone leaves or is removed from an organisation (V2 s3.4).
func (q *Queries) RevokeUserOrgTokens(ctx context.Context, arg RevokeUserOrgTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserOrgTokens, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserTokens = `-- name: RevokeUserTokens :execrows
UPDATE api_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

// tenant: system - a disabled account loses every token it has.
func (q *Queries) RevokeUserTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tokensExpiringSoon = `-- name: TokensExpiringSoon :many
SELECT t.id, t.org_id, t.name, t.prefix, t.expires_at, u.email, o.name AS org_name
FROM api_tokens t JOIN users u ON u.id = t.user_id JOIN organizations o ON o.id = t.org_id
WHERE t.revoked_at IS NULL AND t.expiry_notified_at IS NULL AND t.expires_at > $1 AND t.expires_at <= $2
`

type TokensExpiringSoonParams struct {
	Now    time.Time
	Before time.Time
}

type TokensExpiringSoonRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	Prefix    string
	ExpiresAt time.Time
	Email     string
	OrgName   string
}

// tenant: system - the expiry reminder sweep (V2 s7.2).
func (q *Queries) TokensExpiringSoon(ctx context.Context, arg TokensExpiringSoonParams) ([]TokensExpiringSoonRow, error) {
	rows, err := q.db.Query(ctx, tokensExpiringSoon, arg.Now, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokensExpiringSoonRow
	for rows.Next() {
		var i TokensExpiringSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.ExpiresAt,
			&i.Email,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = $1::timestamptz, last_used_ip = $2
WHERE id = $3 AND org_id = $4 AND (last_used_at IS NULL OR last_used_at < $5::timestamptz)
`

type TouchAPITokenParams struct {
	Now         time.Time
	Ip          *netip.Addr
	ID          uuid.UUID
	OrgID       uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken,
		arg.Now,
		arg.Ip,
		arg.ID,
		arg.OrgID,
		arg.StaleBefore,
	)
	return err
}
