// Package pooler owns the edge PgBouncer configuration (spec §5.2): it
// renders the [databases] routes and the SCRAM auth file from the metadata
// DB, writes them atomically, and drives the PgBouncer admin console
// (RELOAD, PAUSE, RESUME, KILL).
//
// pgdock-server writes two files into the pooler config directory, which
// every pooler's static pgbouncer.ini pulls in:
//
//	[pgbouncer]
//	auth_file = /etc/pgbouncer/pgdock/userlist.txt
//	...
//	%include /etc/pgbouncer/pgdock/databases.ini
package pooler

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// File names written into the pooler config directory.
const (
	DatabasesFile = "databases.ini"
	UserlistFile  = "userlist.txt"
)

// Route maps a client-facing database name to a backend.
type Route struct {
	Database string // client-facing name, e.g. blog_k2f9
	Host     string // backend host as the pooler reaches it
	Port     int
	// BackendDB is the database name on the backend; empty means Database.
	BackendDB string
	// PoolSize and MaxDBConnections cap pooler-to-backend connections.
	PoolSize         int
	MaxDBConnections int
}

// User is an auth file entry. Secret must be a SCRAM-SHA-256 verifier;
// the pooler never sees plaintext passwords.
type User struct {
	Name   string
	Secret string
}

// Config is everything pgdock-server renders for the poolers.
type Config struct {
	Routes []Route
	Users  []User
}

var (
	identRe = regexp.MustCompile(`^[a-z_][a-z0-9_]{0,62}$`)
	hostRe  = regexp.MustCompile(`^[A-Za-z0-9.\-:\[\]]{1,253}$`)
)

// Render returns the contents of databases.ini and userlist.txt. Entries
// are sorted so unchanged inputs produce byte-identical files. Names and
// hosts are validated rather than escaped: anything unexpected is a bug
// upstream, and must never be able to inject pooler configuration.
func Render(cfg Config) (databases, userlist []byte, err error) {
	routes := append([]Route(nil), cfg.Routes...)
	sort.Slice(routes, func(i, j int) bool { return routes[i].Database < routes[j].Database })
	users := append([]User(nil), cfg.Users...)
	sort.Slice(users, func(i, j int) bool { return users[i].Name < users[j].Name })

	var db bytes.Buffer
	db.WriteString("; Generated by pgdock-server. Do not edit: changes are overwritten.\n[databases]\n")
	seen := map[string]bool{}
	for _, r := range routes {
		if !identRe.MatchString(r.Database) {
			return nil, nil, fmt.Errorf("pooler: invalid database name %q", r.Database)
		}
		if seen[r.Database] {
			return nil, nil, fmt.Errorf("pooler: duplicate route for %q", r.Database)
		}
		seen[r.Database] = true
		backend := r.BackendDB
		if backend == "" {
			backend = r.Database
		}
		if !identRe.MatchString(backend) {
			return nil, nil, fmt.Errorf("pooler: invalid backend database %q", backend)
		}
		if !hostRe.MatchString(r.Host) || r.Port < 1 || r.Port > 65535 {
			return nil, nil, fmt.Errorf("pooler: invalid backend address %q:%d for %q", r.Host, r.Port, r.Database)
		}
		fmt.Fprintf(&db, "%s = host=%s port=%d dbname=%s", r.Database, r.Host, r.Port, backend)
		if r.PoolSize > 0 {
			fmt.Fprintf(&db, " pool_size=%d", r.PoolSize)
		}
		if r.MaxDBConnections > 0 {
			fmt.Fprintf(&db, " max_db_connections=%d", r.MaxDBConnections)
		}
		db.WriteByte('\n')
	}

	var ul bytes.Buffer
	seenUser := map[string]bool{}
	for _, u := range users {
		if !identRe.MatchString(u.Name) {
			return nil, nil, fmt.Errorf("pooler: invalid user name %q", u.Name)
		}
		if seenUser[u.Name] {
			return nil, nil, fmt.Errorf("pooler: duplicate user %q", u.Name)
		}
		seenUser[u.Name] = true
		if !strings.HasPrefix(u.Secret, "SCRAM-SHA-256$") || strings.ContainsAny(u.Secret, "\"\n\r ") {
			return nil, nil, fmt.Errorf("pooler: user %q: secret must be a SCRAM-SHA-256 verifier", u.Name)
		}
		fmt.Fprintf(&ul, "%q %q\n", u.Name, u.Secret)
	}
	return db.Bytes(), ul.Bytes(), nil
}
