-- A small Supabase app, reset on every run: profiles keyed by auth.users,
-- todos with RLS policies on Supabase roles, an extension default, a
-- trigger, and a second schema. Mirrors test/integration/imports_test.go.
DROP SCHEMA IF EXISTS app CASCADE;
DROP TABLE IF EXISTS public.todos, public.profiles CASCADE;
DROP FUNCTION IF EXISTS public.touch_updated_at() CASCADE;
DELETE FROM auth.users WHERE email LIKE '%@fixture.test';
INSERT INTO auth.users (id, email) VALUES
  ('00000000-0000-0000-0000-000000000001', 'ada@fixture.test'),
  ('00000000-0000-0000-0000-000000000002', 'bob@fixture.test');
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  username text UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO public.profiles (id, username) VALUES
  ('00000000-0000-0000-0000-000000000001', 'ada'), ('00000000-0000-0000-0000-000000000002', 'bob');
CREATE TABLE public.todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  ref uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  task text NOT NULL CHECK (char_length(task) > 0),
  done boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS
  $$ BEGIN NEW.updated_at = clock_timestamp(); RETURN NEW; END $$;
CREATE TRIGGER todos_touch BEFORE UPDATE ON public.todos FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own todos" ON public.todos FOR ALL TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
GRANT SELECT ON public.todos TO anon;
GRANT ALL ON public.todos TO authenticated;
INSERT INTO public.todos (user_id, task, done)
  SELECT ('00000000-0000-0000-0000-00000000000' || (1 + g % 2))::uuid, 'task ' || g, g % 3 = 0
  FROM generate_series(1, 120) g;
CREATE SCHEMA app;
CREATE VIEW app.open_todos AS SELECT id, task FROM public.todos WHERE NOT done;
