package integration

import (
	"context"
	"encoding/json"
	"net/http"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"

	"github.com/israel-duff/pgdock/internal/api/gen"
	"github.com/israel-duff/pgdock/test/testenv"
)

// supabaseFixture is a small Supabase app: profiles keyed by auth.users,
// todos with RLS policies on Supabase roles, an extension default, a
// trigger, and a second schema. It is reset on each run.
var supabaseFixture = []string{
	`DROP SCHEMA IF EXISTS app CASCADE`,
	`DROP TABLE IF EXISTS public.todos, public.profiles CASCADE`,
	`DROP FUNCTION IF EXISTS public.touch_updated_at() CASCADE`,
	`DELETE FROM auth.users WHERE email LIKE '%@fixture.test'`,
	`INSERT INTO auth.users (id, email) VALUES
		('00000000-0000-0000-0000-000000000001', 'ada@fixture.test'),
		('00000000-0000-0000-0000-000000000002', 'bob@fixture.test')`,
	`CREATE TABLE public.profiles (
		id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
		username text UNIQUE NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now())`,
	`INSERT INTO public.profiles (id, username) VALUES
		('00000000-0000-0000-0000-000000000001', 'ada'), ('00000000-0000-0000-0000-000000000002', 'bob')`,
	`CREATE TABLE public.todos (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id uuid NOT NULL,
		ref uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
		task text NOT NULL CHECK (char_length(task) > 0),
		done boolean NOT NULL DEFAULT false,
		updated_at timestamptz NOT NULL DEFAULT now())`,
	`CREATE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS
		$$ BEGIN NEW.updated_at = clock_timestamp(); RETURN NEW; END $$`,
	`CREATE TRIGGER todos_touch BEFORE UPDATE ON public.todos FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()`,
	`ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY`,
	`CREATE POLICY "own todos" ON public.todos FOR ALL TO authenticated
		USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)`,
	`GRANT SELECT ON public.todos TO anon`,
	`GRANT ALL ON public.todos TO authenticated`,
	`INSERT INTO public.todos (user_id, task, done)
		SELECT ('00000000-0000-0000-0000-00000000000' || (1 + g % 2))::uuid, 'task ' || g, g % 3 = 0
		FROM generate_series(1, 120) g`,
	`CREATE SCHEMA app`,
	`CREATE VIEW app.open_todos AS SELECT id, task FROM public.todos WHERE NOT done`,
}

func seed(t *testing.T, url string, stmts []string) {
	t.Helper()
	ctx := context.Background()
	c, err := pgx.Connect(ctx, url)
	if err != nil {
		t.Fatalf("connect to the source: %v", err)
	}
	defer c.Close(ctx)
	for _, s := range stmts {
		if _, err := c.Exec(ctx, s); err != nil {
			t.Fatalf("fixture %q: %v", s, err)
		}
	}
}

func sourceURL(t *testing.T, name string) string {
	t.Helper()
	u := os.Getenv(name)
	if u == "" {
		t.Skipf("%s not set; run `make test-integration`", name)
	}
	return u
}

// TestImportSupabase imports a Supabase-shaped project and checks the app
// keeps working against PGDock (the M3 done-when, against the
// supabase/postgres image rather than a hosted project).
func TestImportSupabase(t *testing.T) {
	src := sourceURL(t, "PGDOCK_TEST_SRC_SUPABASE_URL")
	seed(t, src, supabaseFixture)
	e := testenv.Start(t, testenv.Options{})
	e.StartAgent()
	ctx := context.Background()

	var pf gen.ImportPreflight
	if code := e.Do("POST", "/api/v1/imports/preflight", gen.ImportSource{SourceUrl: src}, &pf); code != http.StatusOK {
		t.Fatalf("preflight: %d", code)
	}
	if !pf.Supabase || !strings.HasPrefix(pf.ServerVersion, "17") || pf.SizeBytes == 0 {
		t.Fatalf("preflight: supabase %v version %s size %d", pf.Supabase, pf.ServerVersion, pf.SizeBytes)
	}
	if !slices.Equal(pf.DefaultSchemas, []string{"app", "public"}) {
		t.Fatalf("default schemas: %v", pf.DefaultSchemas)
	}
	for _, sc := range pf.Schemas {
		if sc.Name == "auth" && !sc.Managed {
			t.Fatal("auth should be flagged as Supabase-managed")
		}
	}
	exts := map[string]bool{}
	for _, x := range pf.Extensions {
		exts[x.Name] = x.Allowed
	}
	if !exts["uuid-ossp"] || !exts["pgcrypto"] || exts["pg_graphql"] {
		t.Fatalf("extensions: %+v", pf.Extensions)
	}
	var policy, grant bool
	for _, r := range pf.RoleReferences {
		policy = policy || (r.Kind == "policy" && r.Table == "todos" && slices.Contains(r.Roles, "authenticated"))
		grant = grant || (r.Kind == "grant" && r.Table == "todos" && slices.Contains(r.Roles, "anon"))
	}
	if !policy || !grant {
		t.Fatalf("role references: %+v", pf.RoleReferences)
	}

	var c gen.ProjectCredentials
	if code := e.Do("POST", "/api/v1/imports", gen.ImportRequest{SourceUrl: src, Name: "Todo app", Schemas: pf.DefaultSchemas}, &c); code != http.StatusAccepted {
		t.Fatalf("import: %d", code)
	}
	op := e.WaitOperation(c.Operation.Id)
	log := testenv.FormatLog(op)
	if op.Status != gen.OperationStatusSucceeded {
		t.Fatalf("import: %s %s\n%s", op.Status, deref(op.Error), log)
	}
	if strings.Contains(log, "supabase-source") || strings.Contains(string(mustJSON(t, op.Params)), "supabase-source") {
		t.Fatal("the source password leaked into the operation")
	}
	for _, want := range []string{"verified: 2 table(s), 122 row(s)", "uuid-ossp in extensions", "auth.uid()", "profiles_id_fkey"} {
		if !strings.Contains(log, want) {
			t.Errorf("import log lacks %q:\n%s", want, log)
		}
	}

	// The app's queries work through the pooler with the new credentials.
	app := e.MustConnect(c.Connection.PooledUrl)
	var todos, profiles, open int
	if err := app.QueryRow(ctx, `SELECT (SELECT count(*) FROM todos), (SELECT count(*) FROM profiles), (SELECT count(*) FROM app.open_todos)`).Scan(&todos, &profiles, &open); err != nil {
		t.Fatal(err)
	}
	if todos != 120 || profiles != 2 || open != 80 {
		t.Fatalf("imported rows: todos %d profiles %d open %d", todos, profiles, open)
	}
	var id int64
	var ref string
	if err := app.QueryRow(ctx, `INSERT INTO todos (user_id, task) VALUES ('00000000-0000-0000-0000-000000000001', 'from PGDock') RETURNING id, ref::text`).Scan(&id, &ref); err != nil || id != 121 || len(ref) != 36 {
		t.Fatalf("insert: id %d ref %q %v", id, ref, err)
	}
	var touched bool
	if err := app.QueryRow(ctx, `UPDATE todos SET done = true WHERE id = 121 RETURNING updated_at > now() - interval '1 minute'`).Scan(&touched); err != nil || !touched {
		t.Fatalf("trigger: %v %v", touched, err)
	}
	// Everything belongs to the project role; policies were kept.
	var foreign int
	if err := app.QueryRow(ctx, `SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname IN ('public', 'app') AND c.relowner <> (SELECT oid FROM pg_roles WHERE rolname = current_user)`).Scan(&foreign); err != nil || foreign != 0 {
		t.Fatalf("%d imported relations not owned by the project role (%v)", foreign, err)
	}
	var roles []string
	if err := app.QueryRow(ctx, `SELECT roles::text[] FROM pg_policies WHERE policyname = 'own todos'`).Scan(&roles); err != nil || !slices.Equal(roles, []string{"authenticated"}) {
		t.Fatalf("policy: %v %v", roles, err)
	}
	// auth.uid() reads the JWT claims like Supabase's.
	sess := e.MustConnect(c.Connection.SessionUrl)
	var uid string
	if err := sess.QueryRow(ctx, `SELECT set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000002","role":"authenticated"}', false) IS NOT NULL AND true, auth.uid()::text`).Scan(new(bool), &uid); err != nil || uid != "00000000-0000-0000-0000-000000000002" {
		t.Fatalf("auth.uid(): %q %v", uid, err)
	}
	// The placeholder roles exist but nobody can become them.
	if _, err := app.Exec(ctx, `SET ROLE authenticated`); err == nil {
		t.Fatal("the project role must not be able to SET ROLE authenticated")
	}

	// The source was not modified.
	srcConn, err := pgx.Connect(ctx, src)
	if err != nil {
		t.Fatal(err)
	}
	defer srcConn.Close(ctx)
	if err := srcConn.QueryRow(ctx, `SELECT count(*) FROM public.todos`).Scan(&todos); err != nil || todos != 120 {
		t.Fatalf("source changed: %d todos %v", todos, err)
	}
}

// TestImportPostgres15 imports two schemas from a plain Postgres 15.
func TestImportPostgres15(t *testing.T) {
	admin := sourceURL(t, "PGDOCK_TEST_SRC_PG15_URL")
	seed(t, admin, []string{
		`DROP DATABASE IF EXISTS shop15 WITH (FORCE)`,
		`CREATE DATABASE shop15`,
	})
	src := strings.Replace(admin, "/postgres?", "/shop15?", 1)
	seed(t, src, []string{
		`CREATE EXTENSION pg_trgm`,
		`CREATE TYPE mood AS ENUM ('happy', 'sad')`,
		`CREATE TABLE customers (id serial PRIMARY KEY, name text NOT NULL, mood mood)`,
		`CREATE INDEX customers_name_trgm ON customers USING gin (name gin_trgm_ops)`,
		`INSERT INTO customers (name, mood) SELECT 'customer ' || g, CASE WHEN g % 2 = 0 THEN 'happy'::mood ELSE 'sad' END FROM generate_series(1, 300) g`,
		`CREATE SCHEMA inventory`,
		`CREATE TABLE inventory.stock (sku text PRIMARY KEY, qty int NOT NULL)`,
		`INSERT INTO inventory.stock SELECT 'sku-' || g, g FROM generate_series(1, 40) g`,
		`CREATE MATERIALIZED VIEW inventory.totals AS SELECT sum(qty) AS total FROM inventory.stock`,
		`CREATE SCHEMA scratch`,
		`CREATE TABLE scratch.junk (x int)`,
	})
	e := testenv.Start(t, testenv.Options{})
	e.StartAgent()
	ctx := context.Background()

	var pf gen.ImportPreflight
	if code := e.Do("POST", "/api/v1/imports/preflight", gen.ImportSource{SourceUrl: src}, &pf); code != http.StatusOK {
		t.Fatalf("preflight: %d", code)
	}
	if pf.Supabase || !strings.HasPrefix(pf.ServerVersion, "15") || !slices.Equal(pf.DefaultSchemas, []string{"inventory", "public", "scratch"}) {
		t.Fatalf("preflight: %+v", pf)
	}
	var c gen.ProjectCredentials
	if code := e.Do("POST", "/api/v1/imports", gen.ImportRequest{SourceUrl: src, Name: "Shop 15", Schemas: []string{"public", "inventory"}}, &c); code != http.StatusAccepted {
		t.Fatalf("import: %d", code)
	}
	op := e.WaitOperation(c.Operation.Id)
	log := testenv.FormatLog(op)
	if op.Status != gen.OperationStatusSucceeded || !strings.Contains(log, "verified: 2 table(s), 340 row(s), and 1 sequence(s) match") {
		t.Fatalf("import: %s\n%s", op.Status, log)
	}
	if strings.Contains(log, "skipped some objects") {
		t.Errorf("a plain Postgres import should restore cleanly:\n%s", log)
	}
	app := e.MustConnect(c.Connection.PooledUrl)
	var n, total int
	var scratch bool
	if err := app.QueryRow(ctx, `SELECT (SELECT count(*) FROM customers WHERE name % 'customer 42'), (SELECT total FROM inventory.totals),
		EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'scratch')`).Scan(&n, &total, &scratch); err != nil {
		t.Fatal(err)
	}
	if n == 0 || total != 820 || scratch {
		t.Fatalf("imported: trigram matches %d, total %d, scratch imported %v", n, total, scratch)
	}
	var id int
	if err := app.QueryRow(ctx, `INSERT INTO customers (name) VALUES ('new') RETURNING id`).Scan(&id); err != nil || id != 301 {
		t.Fatalf("insert: %d %v", id, err)
	}

	// A bad schema is refused before anything is created.
	if code := e.Do("POST", "/api/v1/imports", gen.ImportRequest{SourceUrl: src, Name: "Nope", Schemas: []string{"missing"}}, nil); code != http.StatusBadRequest {
		t.Fatalf("missing schema: %d", code)
	}
	if code := e.Do("POST", "/api/v1/imports/preflight", gen.ImportSource{SourceUrl: strings.Replace(src, "pg15-source", "wrong", 1)}, nil); code != http.StatusBadRequest {
		t.Fatalf("bad password: %d", code)
	}
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func mustJSON(t *testing.T, v any) []byte {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return b
}
