package integration

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/israel-duff/pgdock/internal/api/gen"
	"github.com/israel-duff/pgdock/internal/store"
	"github.com/israel-duff/pgdock/test/testenv"
)

// supabaseHobby is a Supabase hobby project running on the real Supabase
// services (deploy/dev/compose.yaml: supa-db, supa-auth, supa-storage):
// users signed up through GoTrue, notes with RLS, and files uploaded
// through storage-api under storage policies.
type supabaseHobby struct {
	t                   *testing.T
	db, auth, storage   string
	anonKey, serviceKey string
	s3Key, s3Secret     string
}

func supabaseHobbyEnv(t *testing.T) *supabaseHobby {
	t.Helper()
	h := &supabaseHobby{t: t, db: os.Getenv("PGDOCK_TEST_SUPA_DB_URL"), auth: os.Getenv("PGDOCK_TEST_SUPA_AUTH_URL"),
		storage: os.Getenv("PGDOCK_TEST_SUPA_STORAGE_URL"), anonKey: os.Getenv("PGDOCK_TEST_SUPA_ANON_KEY"),
		serviceKey: os.Getenv("PGDOCK_TEST_SUPA_SERVICE_KEY"), s3Key: os.Getenv("PGDOCK_TEST_SUPA_S3_KEY"), s3Secret: os.Getenv("PGDOCK_TEST_SUPA_S3_SECRET")}
	if h.db == "" || h.auth == "" || h.storage == "" {
		t.Skip("PGDOCK_TEST_SUPA_* not set; run `make test-integration`")
	}
	return h
}

func (h *supabaseHobby) call(method, url, token string, body io.Reader, contentType string) (int, []byte) {
	h.t.Helper()
	req, err := http.NewRequest(method, url, body)
	if err != nil {
		h.t.Fatal(err)
	}
	req.Header.Set("apikey", h.anonKey)
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		h.t.Fatal(err)
	}
	defer res.Body.Close()
	b, _ := io.ReadAll(res.Body)
	return res.StatusCode, b
}

// signUp makes a user through GoTrue (bcrypt-hashed, confirmed) and
// returns its id and access token.
func (h *supabaseHobby) signUp(email, password string) (uuid.UUID, string) {
	h.t.Helper()
	code, b := h.call("POST", h.auth+"/signup", "", strings.NewReader(fmt.Sprintf(`{"email":%q,"password":%q}`, email, password)), "application/json")
	var out struct {
		AccessToken string `json:"access_token"`
		User        struct {
			ID uuid.UUID `json:"id"`
		} `json:"user"`
	}
	if err := json.Unmarshal(b, &out); code != 200 || err != nil || out.AccessToken == "" {
		h.t.Fatalf("supabase sign-up %s: %d %s", email, code, b)
	}
	return out.User.ID, out.AccessToken
}

func (h *supabaseHobby) bucketExists(id string) bool {
	code, _ := h.call("GET", h.storage+"/bucket/"+id, h.serviceKey, nil, "")
	return code == 200
}

// seed resets and builds the hobby project.
func (h *supabaseHobby) seed() (alice, bob uuid.UUID, aliceAvatar []byte) {
	t := h.t
	ctx := context.Background()
	// Leftovers of an earlier run: every bucket goes.
	_, b := h.call("GET", h.storage+"/bucket", h.serviceKey, nil, "")
	var old []struct{ ID string }
	_ = json.Unmarshal(b, &old)
	for _, o := range old {
		h.call("POST", h.storage+"/bucket/"+o.ID+"/empty", h.serviceKey, nil, "")
		waitFor(t, 30*time.Second, "bucket "+o.ID+" emptied and removed", func() bool {
			code, _ := h.call("DELETE", h.storage+"/bucket/"+o.ID, h.serviceKey, nil, "")
			return code == 200 || code == 404 || code == 400 && !h.bucketExists(o.ID)
		})
	}
	seed(t, h.db, []string{
		`DROP TABLE IF EXISTS public.notes CASCADE`,
		`DELETE FROM auth.users`, // the hobby project's own database
		`DROP POLICY IF EXISTS "own avatars" ON storage.objects`,
		`DROP POLICY IF EXISTS "docs are public" ON storage.objects`,
		`DROP POLICY IF EXISTS "small files" ON storage.objects`,
		`CREATE TABLE public.notes (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users (id) ON DELETE CASCADE,
			body text NOT NULL,
			created_at timestamptz NOT NULL DEFAULT now())`,
		`ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY`,
		`CREATE POLICY "own notes" ON public.notes FOR ALL TO authenticated
			USING ((SELECT auth.uid()) = user_id) WITH CHECK ((SELECT auth.uid()) = user_id)`,
		`CREATE POLICY "signed in can count" ON public.notes FOR SELECT TO public USING (auth.role() = 'service_role')`,
		`CREATE POLICY "admins" ON public.notes FOR SELECT TO authenticated
			USING (EXISTS (SELECT 1 FROM auth.users u WHERE u.id = auth.uid() AND u.email LIKE '%@admin.test'))`,
		`GRANT ALL ON public.notes TO authenticated`,
		`CREATE POLICY "own avatars" ON storage.objects FOR ALL TO authenticated
			USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)
			WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)`,
		`CREATE POLICY "docs are public" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'docs')`,
		`CREATE POLICY "small files" ON storage.objects AS RESTRICTIVE FOR INSERT TO authenticated
			WITH CHECK (coalesce((metadata ->> 'size')::int, 0) < 1000000)`,
	})

	var aliceTok, bobTok string
	alice, aliceTok = h.signUp("alice@hobby.test", "alice-old-password-1")
	bob, bobTok = h.signUp("bob@hobby.test", "bob-old-password-2")
	// Bob also has a phone (Supabase keeps it without the +) and a Google
	// identity.
	seed(t, h.db, []string{
		fmt.Sprintf(`UPDATE auth.users SET phone = '2348031234567', phone_confirmed_at = now() WHERE id = '%s'`, bob),
		fmt.Sprintf(`INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, created_at, updated_at)
			VALUES ('google-sub-1234', '%s', '{"sub":"google-sub-1234","email":"bob@hobby.test"}', 'google', now(), now())`, bob),
	})

	// Notes, written as the users through SQL with Supabase's claims.
	c, err := pgx.Connect(ctx, h.db)
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close(ctx)
	for _, u := range []struct {
		id   uuid.UUID
		body []string
	}{{alice, []string{"alice 1", "alice 2"}}, {bob, []string{"bob 1"}}} {
		for _, b := range u.body {
			if _, err := c.Exec(ctx, `INSERT INTO public.notes (user_id, body) VALUES ($1, $2)`, u.id, b); err != nil {
				t.Fatal(err)
			}
		}
	}

	// Buckets and files through storage-api.
	for _, b := range []string{`{"id":"avatars","name":"avatars","public":false,"allowed_mime_types":["image/*"],"file_size_limit":1048576}`,
		`{"id":"docs","name":"docs","public":true}`} {
		if code, out := h.call("POST", h.storage+"/bucket", h.serviceKey, strings.NewReader(b), "application/json"); code != 200 {
			t.Fatalf("supabase bucket %s: %d %s", b, code, out)
		}
	}
	aliceAvatar = pngOf(t, 64, 48)
	for _, f := range []struct {
		path, token, mime string
		body              []byte
	}{
		{"avatars/" + alice.String() + "/me.png", aliceTok, "image/png", aliceAvatar},
		{"avatars/" + bob.String() + "/me.png", bobTok, "image/png", pngOf(t, 20, 20)},
		{"docs/guides/readme.txt", h.serviceKey, "text/plain", []byte("hello from supabase\n")},
		{"docs/empty/.emptyFolderPlaceholder", h.serviceKey, "text/plain", nil},
	} {
		if code, out := h.call("POST", h.storage+"/object/"+f.path, f.token, bytes.NewReader(f.body), f.mime); code != 200 {
			t.Fatalf("supabase upload %s: %d %s", f.path, code, out)
		}
	}
	// Alice can't write into Bob's folder on Supabase either.
	if code, _ := h.call("POST", h.storage+"/object/avatars/"+bob.String()+"/x.png", aliceTok, bytes.NewReader(aliceAvatar), "image/png"); code < 400 {
		t.Fatalf("supabase let alice write into bob's folder: %d", code)
	}
	return alice, bob, aliceAvatar
}

// TestSupabaseMigration is V4-M36's done-when: a Supabase hobby project is
// migrated, including its users and files, and its users sign in on PGDock
// with their existing passwords.
func TestSupabaseMigration(t *testing.T) {
	h := supabaseHobbyEnv(t)
	alice, bob, aliceAvatar := h.seed()
	e := testenv.Start(t, testenv.Options{})
	e.StartAgent()
	e.ConfigureBackups() // file storage
	ctx := context.Background()

	// 1. The database, through the V1 import.
	var pf gen.ImportPreflight
	if code := e.Do("POST", "/api/v1/imports/preflight", gen.ImportSource{SourceUrl: h.db}, &pf); code != http.StatusOK || !pf.Supabase {
		t.Fatalf("preflight: %d supabase %v", code, pf.Supabase)
	}
	var c gen.ProjectCredentials
	if code := e.Do("POST", "/api/v1/imports", gen.ImportRequest{SourceUrl: h.db, Name: "Hobby", Schemas: []string{"public"}}, &c); code != http.StatusAccepted {
		t.Fatalf("import: %d", code)
	}
	if op := e.WaitOperation(c.Operation.Id); op.Status != gen.OperationStatusSucceeded {
		t.Fatalf("import: %s\n%s", op.Status, testenv.FormatLog(op))
	}
	pid := c.Project.Id
	p, err := store.New(e.DB).GetProject(ctx, pid)
	if err != nil {
		t.Fatal(err)
	}

	// The helper needs backend services.
	var refused gen.Error
	if code := e.Do("POST", "/api/v1/projects/"+pid.String()+"/migrate/supabase", gen.SupabaseMigrationRequest{Step: "policies"}, &refused); code != http.StatusConflict {
		t.Fatalf("migrating without backend services: %d", code)
	}
	var en gen.BackendServicesEnabled
	if code := e.Do("POST", "/api/v1/projects/"+pid.String()+"/services", nil, &en); code != http.StatusAccepted {
		t.Fatalf("enable: %d", code)
	}
	if op := e.WaitOperation(en.Operation.Id); op.Status != gen.OperationStatusSucceeded {
		t.Fatalf("enable: %s\n%s", op.Status, testenv.FormatLog(op))
	}
	var pub string
	for _, k := range en.Keys {
		if k.Key.Kind == gen.ApiKeyKindPublishable {
			pub = k.Value
		}
	}
	ref := *en.Services.Ref
	ed := e.StartEdge()
	api := authAPI{t: t, ed: ed, ref: ref, key: pub}
	waitFor(t, 30*time.Second, "the edge reaches the project", func() bool {
		code, _, _ := ed.Do(ref, "GET", "/data/v1/health", nil, "apikey", pub)
		return code == 200
	})

	step := func(req gen.SupabaseMigrationRequest) string {
		t.Helper()
		var op gen.Operation
		if code := e.Do("POST", "/api/v1/projects/"+pid.String()+"/migrate/supabase", req, &op); code != http.StatusAccepted {
			t.Fatalf("%s: %d", req.Step, code)
		}
		done := e.WaitOperation(op.Id)
		log := testenv.FormatLog(done)
		if done.Status != gen.OperationStatusSucceeded {
			t.Fatalf("%s: %s %s\n%s", req.Step, done.Status, deref(done.Error), log)
		}
		if strings.Contains(log, "supabase-hobby") || strings.Contains(log, h.s3Secret) || strings.Contains(string(mustJSON(t, done.Params)), "supabase-hobby") {
			t.Fatalf("%s: a source secret leaked into the operation", req.Step)
		}
		return log
	}

	// 2. Policies.
	log := step(gen.SupabaseMigrationRequest{Step: "policies"})
	// (The "admins" policy, reading auth.users, didn't survive the import;
	// its log said so.)
	for _, want := range []string{"rewrote 2 of 2 policies", "rewrote 1 column defaults", "now read PGDock's tokens"} {
		if !strings.Contains(log, want) {
			t.Errorf("policies log lacks %q:\n%s", want, log)
		}
	}
	app := e.MustConnect(c.Connection.PooledUrl)
	defer app.Close(ctx)
	var roles []string
	var qual string
	if err := app.QueryRow(ctx, `SELECT roles::text[], qual FROM pg_policies WHERE policyname = 'own notes'`).Scan(&roles, &qual); err != nil ||
		!slices.Equal(roles, []string{store.UserRole(p.DbName)}) || !strings.Contains(qual, "pgd_auth.uid()") {
		t.Fatalf("own notes: %v %s %v", roles, qual, err)
	}
	if err := app.QueryRow(ctx, `SELECT qual FROM pg_policies WHERE policyname = 'signed in can count'`).Scan(&qual); err != nil ||
		!strings.Contains(qual, "pgd_auth.role() = 'service'") {
		t.Fatalf("role policy: %s %v", qual, err)
	}

	// 3. Users: bad source first, then the real one.
	if code := e.Do("POST", "/api/v1/projects/"+pid.String()+"/migrate/supabase", gen.SupabaseMigrationRequest{Step: "users",
		SourceUrl: ptr("postgres://postgres:wrong@" + strings.SplitN(strings.SplitN(h.db, "@", 2)[1], "/", 2)[0] + "/postgres?sslmode=disable")}, &refused); code != http.StatusBadRequest ||
		strings.Contains(refused.Message, "wrong") {
		t.Fatalf("a wrong source password: %d %s", code, refused.Message)
	}
	log = step(gen.SupabaseMigrationRequest{Step: "users", SourceUrl: &h.db})
	if !strings.Contains(log, "copied 2 users (0 were already here)") || !strings.Contains(log, "copied 3 identities") {
		t.Fatalf("users log:\n%s", log)
	}

	// The done-when: they sign in with their Supabase passwords.
	signIn := func(body string) authResult {
		t.Helper()
		return api.post("/auth/v1/signin/password", body)
	}
	r := signIn(`{"email":"alice@hobby.test","password":"alice-old-password-1"}`)
	if r.Code != 200 || r.Session.User.ID != alice {
		t.Fatalf("alice signs in with her Supabase password: %d %s", r.Code, r.Body)
	}
	aliceTok := r.Session.AccessToken
	if r := signIn(`{"email":"alice@hobby.test","password":"not-her-password"}`); r.Code != 400 {
		t.Fatalf("a wrong password: %d %s", r.Code, r.Body)
	}
	r = signIn(`{"phone":"+2348031234567","password":"bob-old-password-2"}`)
	if r.Code != 200 || r.Session.User.ID != bob {
		t.Fatalf("bob signs in by phone: %d %s", r.Code, r.Body)
	}
	bobTok := r.Session.AccessToken
	// Their hashes are argon2id now; Bob's Google identity kept its id.
	admin := e.SharedAdmin(p.DbName)
	defer admin.Close(ctx)
	var argon, bcrypt int
	if err := admin.QueryRow(ctx, `SELECT count(*) FILTER (WHERE encrypted_password LIKE '$argon2id$%'), count(*) FILTER (WHERE encrypted_password LIKE '$2a$%')
		FROM pgd_auth.users`).Scan(&argon, &bcrypt); err != nil || argon != 2 || bcrypt != 0 {
		t.Fatalf("hashes: %d argon2id, %d bcrypt (%v)", argon, bcrypt, err)
	}
	var google uuid.UUID
	if err := admin.QueryRow(ctx, `SELECT user_id FROM pgd_auth.identities WHERE provider = 'google' AND provider_id = 'google-sub-1234'`).Scan(&google); err != nil || google != bob {
		t.Fatalf("google identity: %s %v", google, err)
	}
	if r := signIn(`{"email":"alice@hobby.test","password":"alice-old-password-1"}`); r.Code != 200 {
		t.Fatalf("alice again, on argon2id: %d %s", r.Code, r.Body)
	}
	// A second run keeps what's there.
	if log := step(gen.SupabaseMigrationRequest{Step: "users", SourceUrl: &h.db}); !strings.Contains(log, "copied 0 users (2 were already here)") {
		t.Fatalf("users again:\n%s", log)
	}

	// The data API under the rewritten policies, and the owner default.
	notes := func(tok string) []string {
		t.Helper()
		code, _, body := ed.Do(ref, "GET", "/data/v1/notes?select=body&order=body", nil, "apikey", pub, "Authorization", "Bearer "+tok)
		if code != 200 {
			t.Fatalf("notes: %d %s", code, body)
		}
		var rows []struct{ Body string }
		if err := json.Unmarshal([]byte(dataRows(body)), &rows); err != nil {
			t.Fatalf("notes: %s", body)
		}
		var out []string
		for _, r := range rows {
			out = append(out, r.Body)
		}
		return out
	}
	if got := notes(aliceTok); !slices.Equal(got, []string{"alice 1", "alice 2"}) {
		t.Fatalf("alice's notes: %v", got)
	}
	if got := notes(bobTok); !slices.Equal(got, []string{"bob 1"}) {
		t.Fatalf("bob's notes: %v", got)
	}
	if code, _, body := ed.Do(ref, "POST", "/data/v1/notes", strings.NewReader(`{"body":"alice on pgdock"}`), "apikey", pub,
		"Authorization", "Bearer "+aliceTok, "Content-Type", "application/json"); code != 201 {
		t.Fatalf("alice adds a note: %d %s", code, body)
	}
	if got := notes(aliceTok); len(got) != 3 {
		t.Fatalf("alice's notes after adding one: %v", got)
	}

	// 4. Storage.
	s3 := gen.SupabaseS3{Endpoint: h.storage + "/s3", Region: ptr("local"), AccessKey: h.s3Key, SecretKey: h.s3Secret}
	log = step(gen.SupabaseMigrationRequest{Step: "storage", SourceUrl: &h.db, S3: &s3})
	for _, want := range []string{"2 buckets (2 made now)", "copied 3 files", "recreated 2 of 3 storage policies",
		`storage policy "small files" not copied: it uses storage.objects.metadata`} {
		if !strings.Contains(log, want) {
			t.Errorf("storage log lacks %q:\n%s", want, log)
		}
	}
	fs := files{t: t, ed: ed, ref: ref, key: pub}
	got := fs.do("GET", "/storage/v1/object/avatars/"+alice.String()+"/me.png", nil, aliceTok)
	if got.Code != 200 || !bytes.Equal(got.Body, aliceAvatar) || got.Header.Get("Content-Type") != "image/png" {
		t.Fatalf("alice's avatar on PGDock: %d %s", got.Code, got.Header.Get("Content-Type"))
	}
	if r := fs.do("GET", "/storage/v1/object/avatars/"+alice.String()+"/me.png", nil, bobTok); r.Code == 200 {
		t.Fatal("bob read alice's avatar: the storage policy didn't carry over")
	}
	if r := fs.do("POST", "/storage/v1/object/avatars/"+bob.String()+"/new.png", bytes.NewReader(aliceAvatar), aliceTok, "Content-Type", "image/png"); r.Code != 403 {
		t.Fatalf("alice writes into bob's folder on PGDock: %s", r)
	}
	if r := fs.do("POST", "/storage/v1/object/avatars/"+alice.String()+"/new.png", bytes.NewReader(aliceAvatar), aliceTok, "Content-Type", "image/png"); r.Code != 200 {
		t.Fatalf("alice writes into her folder on PGDock: %s", r)
	}
	if r := fs.do("GET", "/storage/v1/object/public/docs/guides/readme.txt", nil, ""); r.Code != 200 || string(r.Body) != "hello from supabase\n" {
		t.Fatalf("the public doc: %s", r)
	}
	var owner *uuid.UUID
	var n int
	if err := admin.QueryRow(ctx, `SELECT (SELECT owner FROM pgd_storage.objects WHERE path = $1), (SELECT count(*) FROM pgd_storage.objects WHERE path LIKE '%emptyFolderPlaceholder')`,
		alice.String()+"/me.png").Scan(&owner, &n); err != nil || owner == nil || *owner != alice || n != 0 {
		t.Fatalf("owner %v placeholders %d (%v)", owner, n, err)
	}
	if log := step(gen.SupabaseMigrationRequest{Step: "storage", SourceUrl: &h.db, S3: &s3}); !strings.Contains(log, "copied 0 files (0 B); 3 were already here") {
		t.Fatalf("storage again:\n%s", log)
	}
}

// dataRows is a data API response's rows.
func dataRows(body string) string {
	var env struct {
		Data json.RawMessage `json:"data"`
	}
	if json.Unmarshal([]byte(body), &env) == nil && len(env.Data) > 0 {
		return string(env.Data)
	}
	return body
}
